### ISSUE TITLE
Audio > Output device is not saved since updating to 46

### ISSUE THREAD

**Issue by peterge1998** [ChimeraOS/chimeraos#1004]
It did cause no problems for like the last year. But after one of the latest updates, my audio device defaults to family 17 models:
![image](https://github.com/user-attachments/assets/2e014a97-e097-46bc-81e2-ac94e94e00b9)
If I choose the Navi device in settings, the os forgets this after a reboot/suspend. So I currently have to go to audio settings every time, which is quite annoying. Please fix, thx ;)
![image](https://github.com/user-attachments/assets/1c4a6787-773b-4ebd-a6f2-8f4c83e6bbb5)

**Comment by EdwinKM** [comment]
i think i have the same issue. (not sure if it is release 46). But i use the HDMI output. After every reboot it defaults to another output.

**Comment by EdwinKM** [comment]
probably duplicate https://github.com/ChimeraOS/chimeraos/issues/869

**Comment by pastaq** [comment]
Steam is doing something here that we still haven't been able to identify.

**Comment by 200Puls** [comment]
@peterge1998 I had the same problem but could work around it by disabling the onboard audio and integrated graphics in the BIOS so that only the HDMI device remains.
Maybe thats also possible for you until a more permanent solution is found.

**Comment by peterge1998** [comment]
That’s a good idea. Will check it out soon
