### ISSUE TITLE
Rog Ally x, pas de son et de bouton menu

### ISSUE THREAD

**Issue by djvetbo** [ChimeraOS/chimeraos#1005]
Bonjour, je viens d'acquérir une ROG Ally X en remplacement de la ROG Ally Extreme. Je m'aperçois que le son et les commandes ne fonctionnent pas. Pensez-vous qu'une mise à jour sera bientôt disponible pour la console ROG Ally X ? Le système Windows 11 est tellement ridicule à côté de l'excellent ChimeraOS. Merci. Et encore bravo pour le travail effectué

**Comment by pastaq** [comment]
An update specifically for the ROG Ally X is being actively worked on and should be available soon. 



Depuis Google Traduction :
```Une mise à jour spécifiquement destinée au ROG Ally X est en cours d'élaboration et devrait être disponible prochainement.```

**Comment by djvetbo** [comment]
Bonjour, merci au top 👍 , bravo 👏 pour le travail
