### ISSUE TITLE
"Launch Option" is not remembered after reboot

### ISSUE THREAD

**Issue by EdwinKM** [ChimeraOS/chimeraos#1006]
I have game Sackboy. "Launch Option" (Properties -> General -> Launch Option) contains "SteamDeck=0 %command%" by default. Because of the stutters i want to add "-dx11". so "SteamDeck=0 %command% -dx11".
I have to re-apply this change every reboot.

**Comment by alkazar** [comment]
Does the -dx11 option make that much of a difference?

**Comment by EdwinKM** [comment]
yes, AFAIK this is a known issue with unreal games and the Vulkan shaders.

In my case it improved:
  * the start logo, it was stuttery
  * a couple (like 5? for example the kindom of crablantis → Choral Reef) were really unplayable because of real low framerates

In did not really see drawbacks in quality.

**Comment by alkazar** [comment]
Thanks. I also took a look at protondb where there are many similar reports to yours. I added -dx11 as the default.
