### ISSUE TITLE
DualSense Controller Not Working in ChimeraOS 46-1 (fdf7169) and Later

### ISSUE THREAD

**Issue by vbali** [ChimeraOS/chimeraos#1010]
**Description:**
Since upgrading to ChimeraOS 46-1 (fdf7169), my DualSense controller has stopped working properly. Although I can connect the controller, the white LED at the center lights up and I'm unable to control the Steam UI with it. This issue appears to be related to the v6.9.12-chos2 and later kernels, as the controller functions correctly when I downgrade to version 46-1_afbc2cd.

**Steps to Reproduce:**

- Upgrade ChimeraOS to 46-1 (fdf7169) or any later version.
- Connect a DualSense controller via Bluetooth.
- Observe that the controller connects (but the white LED lights up).
- Attempt to navigate the Steam UI using the controller.

**Expected Behavior:**
The DualSense controller should work as expected, allowing navigation within the Steam UI.

**Observed Behavior:**
The controller connects, but does not respond to inputs within the Steam UI.

**Temporary Solution:**
Downgrading to ChimeraOS 46-1_afbc2cd resolves the issue, and the DualSense controller works as expected.

**System Information:**

ChimeraOS version: 46-1 (fdf7169)
Kernel version: v6.9.12-chos2 and later
Controller: Sony PS5 DualSense Controller
MiniPC: Minisforum HX100G

**Comment by pastaq** [comment]
Can you provide the output of `lsusb` please?

**Comment by vbali** [comment]
> Can you provide the output of `lsusb` please?

Sure, here is the output of `lsusb`:

```
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
Bus 001 Device 004: ID 0d8c:0014 C-Media Electronics, Inc. Audio Adapter (Unitek Y-247A)
Bus 001 Device 005: ID 0e8d:7961 MediaTek Inc. Wireless_Device
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 05e3:0625 Genesys Logic, Inc. USB3.2 Hub
Bus 002 Device 003: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub             
Bus 002 Device 005: ID 0951:1666 Kingston Technology DataTraveler 100 G3/G4/SE9 G2/50 Kyson
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 0bda:5442 Realtek Semiconductor Corp. BillBoard Device
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 009 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 009 Device 002: ID 05ac:101d Apple, Inc. USB2 Hub
Bus 009 Device 003: ID 05ac:0250 Apple, Inc. Aluminium Keyboard (ISO)
Bus 009 Device 004: ID 05ac:1114 Apple, Inc. Studio Display
Bus 010 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 010 Device 002: ID 05ac:101e Apple, Inc. USB3 Gen2 Hub
```

**Comment by pastaq** [comment]
There might be an issue with InputPlumber. Try `sudo systemctl disable inputplumber` and reboot.

**Comment by vbali** [comment]
> There might be an issue with InputPlumber. Try `sudo systemctl disable inputplumber` and reboot.

Here's a response you can use to mark the issue as solved:

---

Thank you for the suggestion! Disabling InputPlumber` and then rebooting resolved the issue.

Thanks again for the help!

**Comment by pastaq** [comment]
I'd still like to resolve the issue that caused it. The DS5 should be working with InputPlumber. I can't reproduce the issue with my DS5 though so I'm wondering what is different.

**Comment by vbali** [comment]
> I'd still like to resolve the issue that caused it. The DS5 should be working with InputPlumber. I can't reproduce the issue with my DS5 though so I'm wondering what is different.

I’m happy to help! I agree that it would be good to resolve the root cause of the issue with InputPlumber. I’m not sure what might be different on my end, but I’m happy to provide any logs, system details, or test any suggestions you have to help troubleshoot. Let me know what you need!

**Comment by pastaq** [comment]
This may be related to #980

**Comment by MateyBoi** [comment]
I also had this problem @pastaq , disabling inputplumber solved it for me too.
