### ISSUE TITLE
Incorrect DS4 controller mapping for retroarch based games

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#110]
A user reported that the start button was mapped to left thumbstick down.

There may be something wrong with the included retroarch gamepad mappings.

**Comment by Samsagax** [comment]
Is this still relevant?

**Comment by pastaq** [comment]
Would be a retroarch issue anyway, right?

**Comment by Samsagax** [comment]
Closing as it didn't pick up steam for a while
