### ISSUE TITLE
Unable to see Zip files in Kodi

### ISSUE THREAD

**Issue by Altokos** [ChimeraOS/chimeraos#144]
Hi,

I have an issue with Kodi on GamerOS, I'm trying to install addons via zip files but I can't see them.

Can you help me with this issue ?

Thank you.

**Comment by alkazar** [comment]
What do you mean by "I can't see them"?

**Comment by Altokos** [comment]
I can enter in the folders but there is not any kind of file. When I copy a .zip or .key in /home or /home/gamer they didn't appear, but they are in this folders when I'm connecting with the SSH client.

**Comment by alkazar** [comment]
I see, this could be because Kodi is installed as a flatpak and so it is sandboxed.
Could you try to create a new directory under `/home/gamer` and see if that shows up?
