### ISSUE TITLE
Fresh install fix CEC issues in Kodi

### ISSUE THREAD

**Issue by wallzero** [ChimeraOS/chimeraos#148]
After a fresh install, when using Kodi (flatpak) in GamerOS, Kodi can see my [PulseEight CEC adapter](https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter) without issue. However, after installation, Kodi fails to initialize the CEC adapter. [I discovered that the Kodi users are required to be part of the `uucp` and `lock` groups](https://wiki.archlinux.org/index.php/Kodi#HDMI-CEC) in order for the PulseEight CEC adapter to properly initialize.

I setup SSH, logged in as `gamer`, and added `gamer` to `uucp` and `lock` groups via `sudo usermod -aG uucp,lock gamer`. After restarting GamerOS, Kodi can now initialize the PulseEight CEC adapter.

It would be nice if CEC was working out of the box. I'd recommend part of the install script should include the `gamer` user to the `uucp` and `lock` groups.

**Comment by Samsagax** [comment]
Is this relevant? Can #428 improve the situation?

**Comment by Samsagax** [comment]
Closing as inactive
