### ISSUE TITLE
CEC support in Steam Big Picture

### ISSUE THREAD

**Issue by wallzero** [ChimeraOS/chimeraos#149]
[Steam Big Picture currently does not support CEC controls.](https://github.com/ValveSoftware/steam-for-linux/issues/2817)

[However, it is possible to convert CEC input to `uinput`!](https://github.com/bramp/libcec-daemon)

It would be a great feature of GamerOS was packaged with support for CEC support in Steam Big Picture.

**Comment by Samsagax** [comment]
This might be a cool feature. #428 can be repurposed to fill this gap.
