### ISSUE TITLE
HDMI audio is high-pitched/sped up

### ISSUE THREAD

**Issue by maweki** [ChimeraOS/chimeraos#153]
I have a Sapphire R9-270 and I hadn't gotten HDMI audio to work on my previous setup. With GamerOS it worked right away. Or so I thought.

The audio is high-pitched and sped up (both in the menu and in the LEGO game I tested), which makes me think that the bitrate is wrong. I have no Idea how to best investigate that issue.

**Comment by alkazar** [comment]
Strange, this looks relevant with some things you could try: https://bbs.archlinux.org/viewtopic.php?id=163908

**Comment by Thijzer** [comment]
Hi @alkazar, @maweki,

I had a similar issue, https://github.com/ChimeraOS/chimeraos/issues/172

Audio was sped up on the Sapphire RX570 in combo with older hardware.

This issue is still unresolved, changing to Geforce 750ti and problem was gone for me.

**Comment by Samsagax** [comment]
I'm closing this as it seems to be fixed, but if not, please open it again with a reproducible test on latest versions.
