### ISSUE TITLE
Firefox (Flatpak): Kiosk mode not working

### ISSUE THREAD

**Issue by Tau5** [ChimeraOS/chimeraos#154]
I wanted to use kiosk mode (Which hides the browser interface, like on fullscreen mode) to use netflix with this mode on a custom shortcut but when running firefox, the kiosk mode does not work. 
I tried on my laptop kiosk mode on flatpak firefox and it works so I don't know what's happening

**Comment by alkazar** [comment]
What is the command you are running?

**Comment by Tau5** [comment]
I ran from ssh this command: `DISPLAY=:0 flatpak run org.mozilla.firefox --kiosk example.com` I also created a Steam buddy shortcut that does the same thing (minus the display setting) and it does the same thing: It show the firefox windows with all the browser decorations
![photo_2021-01-09_21-44-44](https://user-images.githubusercontent.com/28908976/104108327-ed674300-52c3-11eb-82ae-cb8be5813292.jpg

There is no output in the terminal

**Comment by alkazar** [comment]
I see the same result when I run firefox on my desktop system. Is the --kiosk option broken?

**Comment by Tau5** [comment]
I tested the --kiosk option on my laptop and it worked as intended, I tested the native and flatpak packages

**Comment by wallzero** [comment]
I have the same issue. Pressing F11 should also toggle Firefox full screen and it doesn't work. I also tried a Firefox plugin to auto full screen ([`Auto Fullscreen`](https://addons.mozilla.org/en-US/firefox/addon/autofullscreen/)) and it also fails.

**Comment by chimera-os-fan** [comment]
I am commenting to say that I also have this issue, even on the most up-to-date version of the OS.

**Comment by Samsagax** [comment]
This can be acchieved now on desktop mode.
