### ISSUE TITLE
Afterglow ps3 wireless controller having weird issues

### ISSUE THREAD

**Issue by Codythedragonrude** [ChimeraOS/chimeraos#158]
for some reason the dpad is out of wack if i press up or down it registers it wrong and the X button acts like it's on turbo mode even the lightest press of the X button presses it multiple times 
this seems to be a gamerOS only issue

**Comment by Samsagax** [comment]
I'll close this one as it seems old. If the issue still persists, please reopen with a reproducible case on latest versions.
