### ISSUE TITLE
Support for OpenRGB / liquidctl

### ISSUE THREAD

**Issue by axelsimon** [ChimeraOS/chimeraos#161]
Hi,
LED lighting is now (sadly?) commonplace on gaming computers, "RGB" as they are often referred to in this context.

It would be useful to be able to control these, to at least avoid the worst case of having the various LED components all do their own thing, one glowing blue, the other doing a rainbow dance and another one just shining a steady white, for instance.

From what i've seen, two free and open source projects make it possible to control these lights:
[OpenRGB](https://gitlab.com/CalcProgrammer1/OpenRGB/) and [liquidctl](https://github.com/jonasmalacofilho/liquidctl) (liquidctl is also available in the [AUR](https://aur.archlinux.org/packages/liquidctl/)).

What would you think of bundling one of these in GamerOS? With some integration into Steam Buddy it could provide a really nice experience.

I have hardly looked at how GamerOS is built, and so i don't really realise how much effort this would entail, but i'd be happy to provide assistance in testing / building this.

Thanks!

**Comment by sharkwouter** [comment]
Well, GamerOS can control the light on the Alienware Steam Machine. Can other types of RGB lights also be controlled with shell commands?Then it may be possible to allow the use of the same interface, even if it would be a bit strange. That's a lot of work, though, and I'm not sure if it is worth doing.

**Comment by axelsimon** [comment]
> GamerOS can control the light on the Alienware Steam Machine

Could you be more explicit, how is this done? When you mention shell commands, do you mean already available out of the box in GamerOS?

Otherwise OpenRGB offers an graphical interface to pick and chose the hue and pattern of the LEDs:
![OpenRGB graphical user interface](https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/uploads/e1d8d4603ecdd04f1acbcf6b2314fc66/OpenRGB_0.31_Device_View.PNG)

It needs to be installed first, which is not something that seems obvious to do, in GamerOS, as it is offered as an appimage.

Liquidctl offers ommands, but again, needs to be installed. As it's available in the AUR, it sounds easier (at least, from my current rough understanding) given GamerOS is based on Arch. No idea how true that is.

**Comment by sharkwouter** [comment]
The lights on the Alienware Steam Machine can be controlled from the Steam settings. There you'll find the Alienware FX menu on these systems. To support this we use [this package](https://aur.archlinux.org/packages/alienware-alpha-wmi) which takes the ``/usr/bin/alienware_wmi_control.sh`` from SteamOS. You can find the archive it is based on here:
http://repo.steampowered.com/steamos/pool/main/s/steamos-base-files/steamos-base-files_2.58.tar.xz

**Comment by axelsimon** [comment]
Thanks. Yes i agree, that GUI would be out of place on a Big Picture based interface.
It would be interesting to see how control for LEDs could be folded into the OS however.

At any rate, i'd be happy to try to install liquidctl for instance and see how that works out. I'll try and figure out how to do that, as a first step.

**Comment by alkazar** [comment]
liquidctl has been included in ChimeraOS for a while now. This is probably the extent of what we can support unless someone wants to create a web based UI as part of the Chimera web app. Closing this for now.
