### ISSUE TITLE
Add Youtube Music 

### ISSUE THREAD

**Issue by coreybruce** [ChimeraOS/chimeraos#167]
Hi I want to suggest my Youtube Music desktop I made as a option for additional software you can install from the web GUI, I want to make a flatpak version so that will work for you since you have flathub packages.

https://gitlab.com/youtube-music/application

I also have a desktop application for Youtube and Twitch.

**Comment by alkazar** [comment]
Thank you for the suggestion. Currently, any additional apps would have to be available on Flathub in order for us to be able to make use of them.

**Comment by coreybruce** [comment]
Glad to help, I'll have to make a flatpaks version so you can add it to the gameros flathub page

**Comment by alkazar** [comment]
You would also have to submit your flatpak to Flathub itself. Although I am sure that shouldn't be difficult.

**Comment by coreybruce** [comment]
yeah I will do that, it's no problem :)

**Comment by Samsagax** [comment]
Maybe try installing `mopidy` music server and their plugins? It can be started as a systemd user daemon. It has a plugin for most music streaming services and you can control it from a variety of clients, including a simple web one.
