### ISSUE TITLE
Setup ISO to allow Secure Boot

### ISSUE THREAD

**Issue by chewvodka** [ChimeraOS/chimeraos#170]
Would love to be able to install this on Atari VCS - PC Mode but the install disk needs to be a secure boot with a signed key.  Any chance to get this?

**Comment by alkazar** [comment]
I don't think it is possible unless you are able to add your own key and sign the kernel yourself.

**Comment by a740g** [comment]
So, disabling secure boot is a requirement? Is UEFI boot a requirement too?

Guess, we should put that here: https://gamer-os.github.io/#requirements

**Comment by chewvodka** [comment]
Seems like that would be a fair addition.  I can install something like Windows 10 or Ubuntu, but not GamerOS/SteamOS/Batocera/RetroPie, etc.  If GamerOS could be "installed" and not "prebuilt", that should work too.

**Comment by alkazar** [comment]
I have added a note to the website. Unless Arch Linux somehow adds secure boot support I don't think this will ever happen. And even then I believe this would limit our ability to use things like dkms.

**Comment by titan-91** [comment]
Both Secure Boot and UEFI can be disabled in the Atari VCS BIOS. It's possible to obtain the BIOS password and set these options. So theoretically UEFI with Secure Boot turned off would work on the VCS? I read on the GamerOS site that using legacy BIOS mode could prevent the installer from working.

https://youtube.com/watch?v=KO350y1f85c

**Comment by PeterSurda** [comment]
Please allow me to make a suggestion. The project could use their own keys, and the user can provision them manually. It doesn't work on all motherboards, but at least for some it would. This would also help for people who have multiple operating systems installed.
