### ISSUE TITLE
Support Joy-Con

### ISSUE THREAD

**Issue by Tau5** [ChimeraOS/chimeraos#175]
The joy and con controllers from the Nintendo Switch should be able to be treated as a single controller when used together

**Comment by alkazar** [comment]
Is this possible to setup on other Linux systems? Perhaps with https://github.com/DanielOgorchock/joycond ?

**Comment by Tau5** [comment]
It seems that it would require to install the AUR package `joycond-git` and maybe also the hid-nintendo kernel module driver, although I have been able to connect one controller and had success on GamerOS

**Comment by Tau5** [comment]
Ok, I got it working on my laptop (With arch).
It needs the following AUR Packages: `hid-nitendo-dkms` and `joycond-git`

Then, to connect the joycons the first time:

1. Extract the grips if you have them on them
2. Press the pair button on the side of the controllers
3. Pair both of the controllers via bluetooth
4. Press the ZL and ZR triggers at the same time
5. They are now a unified controller!

After rebooting or disconnecting the controllers the following procedure is needed to connect them:

1. Press ZL and ZR
2. They are now a unified controller!

I think these procedures are very simple and can be done easily through the Steam interface.

Steam recognizes the controller as a "Generic Controller" but these can be changed to a Pro Controller via redifing the controller mappings through the steam interface which would show better prompts for the buttons and possibly put to sleep the controllers after a while

**Comment by alkazar** [comment]
Is this still a problem in the latest release?
