### ISSUE TITLE
Integrate hid-playstation for extended DualSense support?

### ISSUE THREAD

**Issue by CH3DD4RCF** [ChimeraOS/chimeraos#176]
Now that am officially available kernel module is available, has anyone discussed the possibility of integrating it into GamerOS? Im sure at some point, the kernel module will be in the mainline kernel, but it seems to me it would be worth including in an update to GamerOS without waiting for mainline kernel integration.

**Comment by rshamsnejad** [comment]
A DKMS package is available in the AUR, so it would indeed be very easy to add in the future release :

https://aur.archlinux.org/packages/hid-playstation-dkms/

**Comment by CH3DD4RCF** [comment]
Yeah, I should have mentioned that, I did see that and tried it on my laptop, and it works very well! I’d install it on my HTPC if it also ran just straight arch, but since it’s running on GamerOS, I cant. The drawback of a super stable release system, I suppose. 

Anyway, yeah, it should be easy, and that would get it some nice functionality.

**Comment by rshamsnejad** [comment]
If you want to try it on GamerOS, you can access a shell with these instructions : https://github.com/gamer-os/gamer-os/wiki/GamerOS-Troubleshooting#how-can-i-access-a-shell

Then, run `$ sudo frzr-unlock` to get out of read-only mode, and you'll be able to install it like on regular Arch. We'd love some feedback !

**Comment by CH3DD4RCF** [comment]
Oh, neat! I’ll try that out in the meantime, I didn’t know I could do that lol. I’ll leave my impressions here when I do :>

**Comment by SuperSamus** [comment]
hid-playstation is mainlined since Linux 5.12, this can be closed.
