### ISSUE TITLE
Include compatibility tools (Boxtron, Roberta, Luxtorpeda)

### ISSUE THREAD

**Issue by maweki** [ChimeraOS/chimeraos#189]
There are some compatibility tools besides proton that run games in ScummVM/Dosbox/their native engine.

It would be great if they'd be included in gamerOS

* https://github.com/dreamer/luxtorpeda
* https://github.com/dreamer/roberta
* https://github.com/dreamer/boxtron/

**Comment by sharkwouter** [comment]
Boxtron is already included actually.

**Comment by alkazar** [comment]
I am evaluating luxtorpeda, I will probably include it in the next release. I will take a look at roberta as well.

**Comment by sharkwouter** [comment]
Roberta should be pretty easy to implement. It just uses the system's Scummvm to run games which use it. I'm not sure how many games we'd gain from it, especially since I'm not quite sure if Scummvm has good controller support.

**Comment by alkazar** [comment]
I decided to skip including roberta as it was quite large and I had quite mixed results.
