### ISSUE TITLE
RetroArch on black screen

### ISSUE THREAD

**Issue by wumbowarrior** [ChimeraOS/chimeraos#190]
I'm not sure that I made a change that should have affected RetroArch. I adjusted the steamos-compositor-plus to this value
`
GOODMODES=("1280x720")
#GOODRATES=("60.0" "59.9")
`
and then I manually added some bluetooth controllers using bluetoothctl. Now suddenly when I load a ROM the screen is just black?

**Comment by alkazar** [comment]
Hmm... it is possible retroarch doesn't like the resolution. Some of the scaling in retroarch is a bit wonky sometimes. What particular core are you using? Many are pre-configured to work with close to 1080p resolutions.

**Comment by wumbowarrior** [comment]
You know, it was actually black before I adjusted the resolution. It was very choppy because it was trying to render in 4k, but eventually just went black, so I throttled it to 720p. The Big Picture interface was immediately more responsive, However no matter which core I fire up they are all black even after adjusting the resolution. It might be my display. I think it was working on my desktop monitor.

**Comment by wumbowarrior** [comment]
Issue fixed itself after a period of inactivity. I noticed that I can recreate the problem by trying to load the first level in Halo Reach within the Master Chief Collection. The loading screen freezes and I am forced to hard shutdown the machine. After it comes back up retroarch gives me a black screen for a while. After a while the issue is fixed, but I can't see why that would affect retroarch
