### ISSUE TITLE
Feature Request : Add Samba

### ISSUE THREAD

**Issue by Xenoxis** [ChimeraOS/chimeraos#196]
Hello, i have a request about gamer os ? Will it be possible to add Samba ?
It will be great if we can have the possibility to save/load games from a samba share over the network, to find a ISO directory for emulators, or to install Steams Games.

**Comment by sharkwouter** [comment]
This would require the smbclient to be added, but I'm not quite sure how you could use it. I think you can already load music and movies from a sambe server in Kodi without this. ISOs are currently added through steam-buddy and aren't added manually, not sure if we want to add that.

How would you like to use this? Steam in Big Picture mode can currently only load games from 1 location, which is problematic.

**Comment by Xenoxis** [comment]
Is it possible to add/remove a location from steam configuration by modifying directly the config file (located in .steam/config/config.vdf), in there, you can add manually a location, in big picture mode (tested only on Windows though), you just can choose which directory will be used for games.
I think this can be very useful for person that use a NAS, you can stock your games on it, and then use them with all your computers over the network.
And you can manage your games more easily i think than upload all your games on your gameros pc if your have already set-up a samba share.

**Comment by thekk1** [comment]
> This would require the smbclient to be added, but I'm not quite sure how you could use it. I think you can already load music and movies from a sambe server in Kodi without this. ISOs are currently added through steam-buddy and aren't added manually, not sure if we want to add that.
> 
> How would you like to use this? Steam in Big Picture mode can currently only load games from 1 location, which is problematic.

I am using ChimeraOS on a Mini PC (UM790 Pro) and would like to access my local SMB share too.
I have some Games there, which are not from Steam originaly.

**Comment by thanone2** [comment]
how do you solve this problem in CHIMERAOS not "Windows" this is a chimeraos discussion, any ways have y'all solved this prob' yet?
