### ISSUE TITLE
Bluetooth Connection Lag

### ISSUE THREAD

**Issue by newdawnstudios** [ChimeraOS/chimeraos#199]
When connected via bluetooth there is more than 1 seconds of latency. Also, controller connects after shutting it off and on, but can't control anything on the screen.

Controller:8Bitdo Sn30 Pro+

**Comment by Samsagax** [comment]
Is this issue still relevant? Have you tried newer versions?

If this is still not working for you, please comment adding additional information about your hardware and we will reopen the issue.
