### ISSUE TITLE
Include udev rules for racing wheels

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#204]
Some relevant links:
https://support.feralinteractive.com/en/mac-linux-games/dirt4/faqs/steering_wheels_udev_rules/
https://github.com/berarma/oversteer

**Comment by sharkwouter** [comment]
It seems there is a package for Oversteer on the AUR: https://aur.archlinux.org/packages/oversteer/

**Comment by sharkwouter** [comment]
Udev rule found in Oversteer: https://github.com/berarma/oversteer/blob/master/data/udev/99-logitech-wheel-perms.rules

Seems to contain most wheels.

**Comment by alkazar** [comment]
Also need to add the `usb_modeswitch` package.
