### ISSUE TITLE
Support for bluetooth rtl8761 based devices

### ISSUE THREAD

**Issue by mycroftsnm** [ChimeraOS/chimeraos#209]
I have got an amitosai mts-bt5 bluetooth dongle which uses the realtek rtl8761, gamer-os don't recognize it.
It works after install this [AUR package](https://aur.archlinux.org/packages/rtl8761b-fw/), tested on my personal machine with Arch.

**Comment by Samsagax** [comment]
Firmware is already present on newer versions. Could you test that? If is still not working for you, please comment and we will reopen the issue.
