### ISSUE TITLE
Asus Tuf Gaming B550M network issue

### ISSUE THREAD

**Issue by Mohandevir** [ChimeraOS/chimeraos#220]
Hi!

I got a hardware related issue, specific to my motherboard... I'm unable to connect to the internet with my Asus TUF Gaming B550M motherboard. It refuses to recognize the onboard ethernet adapter (**Realtek RTL8125B 2.5Gb Ethernet**). This issue is known to me even on Ubuntu 20.04 (Pop_OS! 20.04 works great, probably due to an inhouse backport), but I hoped that the latest GamerOS kernel would solve the issue...

Is it possible to update the GamerOS download link? It's still linked to the 2020-10-02 build.

Thanks!

Edit: While trying to install GamerOS there is a "RTL8169: Unknown device" message. So it seems it tries to load the wrong driver.

**Comment by alkazar** [comment]
The October 2020 installer is the latest one that there is. The installer and system image (the latest one having released in late Feb) are completely separate things. The installer could use an update but I am waiting on a few things to settle before I do so. Sorry, but you will have to wait a bit longer.

**Comment by Mohandevir** [comment]
No problem. Thanks.

**Comment by alkazar** [comment]
There is a new installer now (dated 2021-07-01), check it out if you can.

**Comment by Mohandevir** [comment]
Just tested it. Problem solved. Thanks!
