### ISSUE TITLE
Gamer OS missing some font?

### ISSUE THREAD

**Issue by hawari21** [ChimeraOS/chimeraos#222]
Did you guys had a plan to updating some font to work correctly on Gamer OS? some font on steam are missing. I tried to fixing the by installing this with tty terminal : https://aur.archlinux.org/packages/all-repository-fonts/ but it didnt work.

So, maybe in the next update you guys want to add them.

Cheers.

**Comment by alkazar** [comment]
What fonts are missing?

**Comment by hawari21** [comment]
Like steam free emojis, most of them are missing, or blank like this 👩‍🌾 : https://steamcommunity.com/sharedfiles/filedetails/?id=929573621
https://steamcommunity.com/sharedfiles/filedetails/?id=757854761 

Is that possible to fix that?

**Comment by Samsagax** [comment]
@hawari21 is this issue still relevant for you on newer versions? If so, please comment and we will reopen the issue and look for missing fonts.
