### ISSUE TITLE
[Request] Disable PS4 controller touchpad kernel driver

### ISSUE THREAD

**Issue by qchto** [ChimeraOS/chimeraos#223]
Considering DS4 touchpad by deafult is recognized as a regular mouse, sometimes the experience for gaming with bindings for this touchpad is compromised ([here's an example of the reported issue](https://steamcommunity.com/discussions/forum/1/2254560552292685844/)).
I found out that creating a rule in `/etc/X11/xorg.conf.d/30ds4.conf` solved the issue in GamerOS:
```
Section "InputClass"
       Identifier   "ds4-touchpad"
       Driver       "libinput"
       MatchProduct "Wireless Controller Touchpad"
       Option       "Ignore" "True"
EndSection
```
(Please note that the touchpad can be still used through Steam Input both in-game and in-menus/chord configurations.)

**Comment by Protektor-Desura** [comment]
Can you use it still to click OK on certain game setup installs and such, which was kind of the point in my opinion for using it. The PS4 controller with the chatpad attachment means in theory you don't need a mouse or keyboard for anything that might require it during setup/install.

You can also configure the gyro in the PS4 controller to act as a pointer/whatever in games and act as a mouse as well.

**Comment by qchto** [comment]
Just tested with the prompt menu in Batman: Arkham Asylum, and sadly no (I supposed it would be using the Desktop config for those dialogs, but that's not the case in GamerOS). Still having a mouse and left click binding configured on chord config allows for these prompts to be accesible (which is how I always pass them using other controllers).

And if possible, creating the file and commenting the line `#Option       "Ignore" "True"` would make the configuration easier for those of us who want it without affecting the default behaviour (or could be the solution for those wanting to use the DS4 touchpad mouse).

**Comment by Samsagax** [comment]
Is this issue still relevant? Feel free to comment if it is and we will look into it.

**Comment by S1ngl3-x** [comment]
Sorry for the necro but @Samsagax it's still relevant.

I've tried to disable ps4 or ps5 touchpad as mouse  in udev rules according to 

https://wiki.archlinux.org/title/Gamepad#Disable_touchpad_acting_as_mouse

but it doesn't work on ChimeraOs. However it has worked on Fedora immediately on my other pc.

Any suggestions or plan to tackle this on a distro level? Sony is pumping more and more games that work on Linux and which make use of all features the DualSense offers.

**Comment by pastaq** [comment]
That udev rule in the wiki is incomplete, it doesn't match to the event device properly so it is ignored. I just tested this with a DualSense.

```
# Disable DualSense/DualShock touchpad acting as mouse
# USB
# Disable DualSense/DualShock touchpad acting as mouse
# USB
ACTION=="add|change" KERNEL=="event[0-9]*" ATTRS{name}=="Sony Computer Entertainment Wireless Controller Touchpad", ENV{LIBINPUT_IGNORE_DEVICE}="1"
ACTION=="add|change" KERNEL=="event[0-9]*" ATTRS{name}=="Sony Interactive Entertainment DualSense Wireless Controller Touchpad", ENV{LIBINPUT_IGNORE_DEVICE}="1"

# Bluetooth
ACTION=="add|change" KERNEL=="event[0-9]*" ATTRS{name}=="Wireless Controller Touchpad", ENV{LIBINPUT_IGNORE_DEVICE}="1"
ACTION=="add|change" KERNEL=="event[0-9]*" ATTRS{name}=="DualSense Wireless Controller Touchpad", ENV{LIBINPUT_IGNORE_DEVICE}="1"

```

Save this to `/etc/udev/rules.d/72-sony.rules`
run `sudo udevadm control --reload`
then disconnect and reconnect your controller.

**Comment by S1ngl3-x** [comment]
Thank you for the quick response. Unfortunately, your udev rule only worked on dualshock on my Fedora machine, dualsense didn't work.
On ChimeraOs it didn't work for both DualSense/DualShock..

Tried both GamepadUI and Gnome, restarts, multiple usb ports and so on.


If your udev rule works on your machine, maybe my problem is something else and I should start a new issue? Because I've noticed that in gamepad UI my 1 controller shows as 2, 2 as 4...

**Comment by pastaq** [comment]
A lot of folks use the touchpad in desktop mode. There isn't a simple way to reverse a udev rule like this.

**Comment by GasparAM** [comment]
@pastaq The issue bothers me a lot since it not only renders the touchpad unusable but the touchpad buttons as well. I don't think having it on for the sake of desktop mode is a good solution since the funcionality there is quite limited and we lose more than we gain. One solution I can think about is to change the current oneshot session to xorg instead of wayland and add steam as an autostart application. That way steam input will handle the desktop mode and in game mode we'll have the normal controls akin to how the steam deck does it in KDE.

**Comment by pastaq** [comment]
> @pastaq The issue bothers me a lot since it not only renders the touchpad unusable but the touchpad buttons as well.

You can add the udev rule to /etc/udev/rules.d/ and it will persist through updates.

**Comment by blurrred** [comment]
All the touchpad does is get in the way.

Shame seeing this anti-features without the option to disable them.
