### ISSUE TITLE
Steam + non-Steam game library management MVP

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#224]
Allow users to setup secondary drives/partitions for storage of Steam and non-Steam (Steam Buddy) games.

- should have a disk/library management section somewhere in Steam Buddy
- should list all mounted bulk storage drives/partitions and their size in GB
- should allow selection of drive/partition to install games to by default
- should apply the selected default location to the Steam settings for all Steam users
- should use the default installation drive/partition to install non-Steam games to
- should create the necessary directories at the following locations on the root of the disk/partition if they don't already exist:
     chimera/steamapps
     chimera/banners
     chimera/content
     chimera/saves

Consider using https://gitlab.com/qchto/steam-disk-lib-utils

Out of scope for now:
- should list all bulk storage drives/partitions (formatted, mounted, and not mounted)
- should prompt to format a drive if not already formatted
- should auto-mount formatted drives (#46)
- should be able to find and use existing steam and steam buddy libraries, even if in the non-default location
- should list the used and empty space on each drive
- should be able to list all games installed in each library along with their size in GB
- should list game platform in games list (i.e. Steam, GOG, Epic Games, Super Nintendo, etc.)
- should be able to transfer individual games and relevant files between libraries (what does the UI look like?)
- should automatically adjust file/folder permissions... somehow
- should prompt the user to restart Steam to make selection of new default installation drive/partition apply in Steam

**Comment by alkazar** [comment]
Initial research in how to add library folders to Steam:
 - you can add libraries by editing `~/.local/share/Steam/steamapps/libraryfolders.vdf`
 - each entry has a key which is a number starting from "1" with the value being the path to the library (not including the "steamapps" folder)
 - to change the default library, you have to set the `LastInstallFolderIndex` to the index of the desired library in `~/.local/share/Steam/userdata/<steam user id>/config/localconfig.vdf`

**Comment by lennyhans** [comment]
Update, there are a change with the manage of extra steam libraries, so the structure is at the time of this.
```

"1"
        {
                "path"          "<path-to-steam-library>"
                "label"         ""
                "contentid"             "<numeric-id>"
                "totalsize"             "<numeric-size>"
                "apps"
                {
                        "550"           "<game-id>"
                        "570"           "<game-id>"
                        "48700"         "<game-id>"
                        ...
                }
        }
```
this is on `config/libraryfolder.vdf` and `steamapps/libraryfolders.vdf`
