### ISSUE TITLE
Bluetooth dongle firmware

### ISSUE THREAD

**Issue by nosklo** [ChimeraOS/chimeraos#226]
I'm trying to use a bluetooth dongle that uses the `/lib/firmware/rtl_bt/rtl8761b_fw.bin` file, which is not included in GamerOS.

I'd like to upload it (and possibly other firmware for my hardware), and have it copied to the correct path on every update.

**Comment by sharkwouter** [comment]
Which packages includes that file?

**Comment by nosklo** [comment]
I don't know. I got it from the vendor website directly. Here's the website I got the file from:

https://www.xmpow.com/pages/download

I found the linux driver by typing "BH456A" in the search box.

**Comment by Samsagax** [comment]
@nosklo does it work on newer versions? Stated firmware is already present on newest `linux-firmware` package.

If it doesn't work for you please comment and we reopen the issue.
