### ISSUE TITLE
GamerOS 24 upgrade breaks Proton functionality

### ISSUE THREAD

**Issue by gamerosfan** [ChimeraOS/chimeraos#227]
I updated to GamerOS 24 from v23 using built-in updater a couple of days ago.  Process seemed to go fine, but upon restarting, none of my games that require Proton to work will run.  Whether 2D or 3D, newer or older, Proton v5 or v6, doesn't matter.  None of them run.  Games that natively support Linux still run, however.

In attempting to troubleshoot this, I saw that I enabled beta participation under system settings.  I unchecked that, it re-updated then restarted.  No change in Proton function.  I re-checked and unchecked this option a couple times, but I'm still not getting any changes.  Nothing else seems to be wrong with the installation.  Hopefully this can be fixed without a reinstall.

**Comment by alkazar** [comment]
Sorry to hear you are having trouble with the new update. That is strange, myself and others can use Proton games just fine with GamerOS 24 so there must be something more to the issue.

Have you tried validating the proton files? And the steam runtimes as well?

**Comment by alkazar** [comment]
What GPU are you using?

**Comment by gamerosfan** [comment]
Intel integrated graphics

**Comment by alkazar** [comment]
Do any games work with Proton 4.11?

One theory is that the newer Proton versions (which use sandboxing) are not finding the correct GPU driver.

**Comment by gamerosfan** [comment]
I gave up on my previous installation and decided to reinstall GamerOS from scratch this morning.  I'll have to reinstall games and start testing them to see if I'm still having the issue.  However, the fresh install currently isn't booting without me having to manually select it in the boot order, so I've been trying to fix that first.

On a side note, if there's a way to reinstall GamerOS while specifying which version to install, I would gladly go back to v23 at this point.

**Comment by alkazar** [comment]
I pushed a new GamerOS build to our testing channel. Can you give it a shot? It has a newer kernel and mesa.

You can switch to the testing channel by running this command:
`sudo frzr-deploy gamer-os/gamer-os:testing`

**Comment by gamerosfan** [comment]
Thank you for your continued work on this project.  I will test this out when I get a chance (hopefully later today).

**Comment by gamerosfan** [comment]
I attempted to switch to the testing channel as described.  At the first attempt, it looked like it was downloading, but upon finishing, it said the checksum didn't match and aborted the process.

I rebooted and attempted to switch again 2 times.  Each of these times it looked like a connection was being made but then, instead of downloading, it gave the same checksum error and aborted.  

I rebooted yet again, and instead of putting in the command to switch to the testing channel, I put in the command to switch to the stable channel.  It gave the error that it was already on the stable channel, and aborted.  

At this point I don't know what else to do.  I tested more games that used to work with Proton (One Finger Death Punch 2 and Zombie Derby 2).  I can't get these to work post-update.  Native Linux games still work fine.

I have noticed that a couple of games that are labeled as Windows games do currently work, but the consistent thing among these exceptions is that they are visual novel games made with the Ren'Py engine.  This isn't indicated on Steam, but on itch.io, multiple games that are like that have their PC version listed as both Windows and Linux, so maybe the "Windows" version on Steam is secretly Linux compatible due to the engine...?  No clue, but I thought I should point that out.

Example of a Ren'Py engine game with the PC version listed as both Windows and Linux (itch.io): https://ioblack.itch.io/dates-and-wires

**Comment by alkazar** [comment]
There is a bug that once the checksum fails the download will get stuck. To fix that you have to delete the file at `/frzr_root/*.img.tar.xz` so the file can be re-downloaded.

**Comment by gamerosfan** [comment]
Thank you for letting me know. I will try that sometime today or tomorrow.

**Comment by gamerosfan** [comment]
I tried your suggestion.  Long story short, no luck.

First, I tried to FTP in, couldn't access frzr_root, so then I ran a live distro of Linux to access the file system (my main system is Windows).  I couldn't get the file to delete, so changed permissions, deleted, then changed them back.  

Upon restart, it booted into the base Linux partition, but Steam would no longer load and the screen just stayed black with a blinking cursor.  I decided to start from scratch again, tried switching to the testing channel on the fresh install, and had the same checksum error as before.  

Not sure what else to do and feel like I've sunk a lot of time into it.  I appreciate your work, but as I said before, I would gladly go back to v23 at this point.

**Comment by gamerosfan** [comment]
I'm commenting again to say that the recent update to GamerOS/ChimeraOS to v25 seems to have fixed whatever the issue was with Proton in v24.  I haven't redownloaded everything I had yet, but of the games I've checked thus far (the ones I mentioned in previous posts), Proton is working again. 

Thank you for your continued work on this project!

**Comment by alkazar** [comment]
Probably something broke and was fixed in Mesa or some other upstream package. Thanks for letting me know!
