### ISSUE TITLE
Tell Users When Their System Has An Update and Add "Update Later" Option

### ISSUE THREAD

**Issue by ghost** [ChimeraOS/chimeraos#228]
As someone who has limited internet data, automatic update can be really anoyying. I think a good idea to tell users when system has an update and they can choose "update later" option so they can update their system when they have more internet data. Sorry for my English. English is not my native languange. I hope you are understand what i am saying. Thank you for making an awesome GNU+Linux OS

**Comment by chimera-os-fan** [comment]
I'm just commenting to say I think this is a good idea and would welcome more control over the update process.

**Comment by alkazar** [comment]
This is now possible in Deck/Gamepad UI and will be addressed with https://github.com/ChimeraOS/chimeraos/issues/338
