### ISSUE TITLE
Epic games trying to open web pages in the middle of the game.

### ISSUE THREAD

**Issue by dubigrasu** [ChimeraOS/chimeraos#229]
Certain Epic games installed with Steam-Buddy require your permission to link/connect with your Epic account.
They do that by trying to open a web page immediately after the game is started, which can cause the controller to eventually become unresponsive, or even crash the game. Also, after the game is stopped, the extra window opened is still present and not responsive, requiring a Steam/Gameros restart.

A workaround would be to:
- Install with Steam-Buddy the Chromium browser from FlatHub (possibly also Firefox).
- Start the game and after few seconds close it back.
- You will see a web page opened on your Epic account, asking you to accept the agreement. The controller can't be used right now.
- Toggle the compositor from the Steam-Buddy interface (upper right gear icon).
- You can now use the controller to press "Accept". Once you do that, it will never bother you again.
- Go back to the Steam-Buddy interface and restart Steam.

Example of games affected: Killing Floor 2, Remnant: From the Ashes.

**Comment by alkazar** [comment]
This should be fixed in ChimeraOS 31. The web pages will open in the Steam browser in the background.
