### ISSUE TITLE
Exit shortcut not working in non-steam games

### ISSUE THREAD

**Issue by esaudet** [ChimeraOS/chimeraos#235]
Hi,

I just installed gameros and I experience an issue when I try to quit some non-steam games via the steam overlay. The exit shortcut seems to work fine in native steam games, proton steam games and flatpak apps. However, it is not working for other apps like emulators (Ryujinx and retroarch in particular) and epic games titles (like RocketLeague). When I click on exit, nothing happens and the game is not exited.

One workaround is to use steam-buddy to restart steam or kill the process directly from the command line.

Am I missing something?

Thanks!

**Comment by alkazar** [comment]
I can confirm this issue. This may be a Steam bug.

Since it also affects the "Exit Game" option in Steam Buddy, perhaps the way non-Steam games are launched in Steam has changed. I will have to investigate.

**Comment by alkazar** [comment]
I just updated to the latest Steam client beta and this appears to be fixed.

Steam Buddy is still affected though.

**Comment by alkazar** [comment]
Well, the problem actually persists. But now at least seems to work with Retroarch for some reason.

I filed this issue with Valve: https://github.com/ValveSoftware/steam-for-linux/issues/7857

**Comment by alkazar** [comment]
This doesn't appear to be an issue anymore.
