### ISSUE TITLE
[Suggestion] Bundle ChimeraOS with Jellyfin

### ISSUE THREAD

**Issue by Tau5** [ChimeraOS/chimeraos#236]
Jellyfin is an open-source media server which where one can watch shows and movies locally stored on the server or on the network. It's basically like a self-hosted Netflix, it has a user system which keeps track of movie and show progress so you can continue where you left.
Jellyfin also has the advantage of being able to be uses on multiple platforms and progress is synchronized, so for example, if you start watching a show in the computer and then continue watching on you phone, you'll continue from the point you left without doing anything.
I think this is a great addition for ChimeraOS, Jellyfin provides a web-based setup which steam-buddy could redirect to when enabling Jellyfin. And you could use Jellyfin in ChimeraOS from a web browser.

You can [try a demo of Jellyfin here](https://demo.jellyfin.org/stable)

I suggest this because I have been struggling thinking about uninstalling ChimeraOS and installing another OS for Jellyfin at the expense of the gaming side of the OS. For now I have been using a combination of the FTP Server and Kodi in my phone, but this has the disadvantage that progress in shows is not shared.

The best way I think this could be implemented is including a toggle or button on steam-buddy to enable Jellyfin, when enabled, it would redirect to the setup website.

**Comment by alkazar** [comment]
GamerOS includes podman which lets you run docker containers. There is a jellyfin docker image you can install and use.
