### ISSUE TITLE
Unable to run Epic Games

### ISSUE THREAD

**Issue by chimera-os-fan** [ChimeraOS/chimeraos#239]
I previously mentioned in [this issue](https://github.com/ChimeraOS/chimera/issues/144) that I couldn't get anything from Epic Games to run.  In addition to validating Proton and Steam Runtimes, I checked ProtonDB and system requirements for everything I've tried.  It doesn't matter, everything I've tried from Epic Games just won't run, and I don't know what else to try, hence my post.  

Some games, like Cave Story+, don't bring up any error and just go back to the Steam Big Picture interface.  Others, like Absolute Drift, display a runtime error.  Yet others, like Sonic Mania, display "Unable to initialise Epic services."  This is with or without Proton parameters (i.e. "PROTON_USE_WINED3D=1 %command%") and regardless of Proton version used.  

In looking for information, I found [this article](https://www.gamingonlinux.com/2020/10/steamos-like-linux-distribution-gameros-has-a-new-release-adds-in-epic-game-store-support/) which says this OS uses [Legendary](https://github.com/derrod/legendary) to run Epic Games.  Is that accurate?  Should arguments in Legendary be used where one can input parameters for Proton?  Sorry if this doesn't make sense; the more I try to find a solution the more confused I get.  

I also came across [this article](https://www.gamingonlinux.com/2021/06/heroic-games-launcher-for-epic-games-sees-a-small-bug-fix-release-ahead-of-the-big-1-8) about a tool for running Epic games on Linux; not sure if of use, but adding anyway.  I hope someone has some advice or a fix.  Thank you for reading.

**Comment by alkazar** [comment]
Sorry to hear you are having trouble.

I was able to install and run the following EGS games successfully just now:
 - Absolute Drift
 - Horizon Chase Turbo
 - AER Memories of Old
 - Enter the Gungeon
 - Creature in the Well

The following games did not work for me:
 - Sonic Mania
 - Cave Story+


Not every game will work, but you should be able to at least play some games.

We do use Legendary to manage EGS games. Heroic also uses Legendary but isn't something we can use with ChimeraOS due to being targeted for couch gaming.

My questions for you:
1. What GPU are you using?
2. Are you able to run any Steam games with Proton 5.13?
3. What is the runtime error that Absolute Drift displays?

**Comment by chimera-os-fan** [comment]
Thank you for your response and your continued work on this project.  I took pictures of the error I received from running "Absolute Drift" and uploaded here because imgur was giving me issues.  

[This is the error](https://user-images.githubusercontent.com/83927222/124363419-a599f680-dc2a-11eb-84f0-82a3ed7637ab.jpg) I receive when trying to run "Absolute Drift" from Epic Games on ChimeraOS.  Proton versions tried include 4.11, 5.13, and 6.3.

[This is the result](https://user-images.githubusercontent.com/83927222/124363409-9c108e80-dc2a-11eb-999e-d6c000cf1e18.jpg) of clicking "Yes" from the above image.  If "No" is selected, then the game exits back to the main interface.  

After trying to open one of the files shown in the above image, [this is the error I got](https://user-images.githubusercontent.com/83927222/124363416-a16dd900-dc2a-11eb-91fa-5461bdfbbc17.jpg).

I realize I may not be of much help as the only games I have on my Epic account are the ones they've given away for free.  On top of that, I've intentionally tested games that don't take too long to download and are on the lower end of hardware requirements.  It's hard to troubleshoot, however, when "Rocket League" is as unresponsive as "Cave Story"  🤷‍♀️

To answer your other questions:
- GPU is Intel Integrated Graphics (my CPU/GPU is on the lower end of minimum listed specs for the OS, but with 12GB of RAM can run a variety of games very well)
- The majority of games I run using Proton I do so with either 5.13 or 6.3


Please let me know if you have any other questions or suggestions I should try.  Thanks again.

**Comment by alkazar** [comment]
From that error, it looks like Absolute Drift is launching correctly, but your hardware does not support the required graphics features.

Not sure why the `PROTON_USE_WINED3D=1` does not help.

**Comment by Samsagax** [comment]
Why are you trying to run a Linux native game through proton is a little beyond me but have you tried Proton 4.11? The only protondb report seems to be using that one.

**Comment by alkazar** [comment]
> Why are you trying to run a Linux native game through proton is a little beyond me but have you tried Proton 4.11? The only protondb report seems to be using that one.

It is an Epic Games Store game, so there is only a Windows version available.

**Comment by chimera-os-fan** [comment]
I have "Absolute Drift" on both Epic and GOG (giveaways) but it's the Windows version on both.  I also get the same errors regardless of which version I try.  My system meets the requirements, so still not sure.  Also, most Epic games that I've tried just exit back to the system interface rather than give an error, so that's even harder to troubleshoot.

**Comment by alkazar** [comment]
Which Intel processor do you have? Older ones do not support the full set of Vulkan features required to run Proton. I suspect this is the problem in your case. Windows system requirements will not necessarily represent what you need to run the same game on Linux.

**Comment by chimera-os-fan** [comment]
Sorry for the delayed response; been busy with things.  I'm not sure of the exact processor but know it's a core i5 running at 3.4 GHz.  The PC is definitely older (think it came out 4-5 years ago), but I'm not complaining because it was free.  Most Windows games I play with this require "PROTON_USE_WINED3D" to run, but they run well with it.

**Comment by alkazar** [comment]
Can you try this:

Open ~/.config/steamos-compositor-plus and add the following line:

export PROTON_USE_WINED3D=1

Then restart the computer.

That should enable the option globally.

**Comment by chimera-os-fan** [comment]
Sorry for not replying sooner, but it's going to be a few days before I can let you know how this turned out.  

I turned on the PC yesterday after not having used it for a week and let it auto-update.  Then, when it restarted, it looked like everything had reset to defaults.  Default video resolution, login screen, everything at first glance looked like it had been wiped.  

Strangely, the wifi password was saved, so something was still there, but upon logging back in to Steam, nothing seems installed anymore.  Every game I tried looking at said it needed to be installed. As my internet isn't great, I haven't gotten around to reinstalling games, and part of me wonders if I should reinstall the OS.

I'll let you know once I've tried your suggestion.  Thank you.

**Comment by chimera-os-fan** [comment]
So, I ended up reinstalling the OS again.  Fresh install, set-up preferences and such, and then followed through on your last suggestion.  

Success.

I can finally play games from Epic, and more games from GOG, after adding the line to ~/.config/steamos-compositor-plus (yay!).  For whatever reason, entering "PROTON_USE_WINED3D=1" on an individual game's launch option works for Steam games, but apparently is ignored on Epic and GOG entries. 

Here are Epic games I got working as of now: 
- Absolute Drift (Epic and GOG)
- Horizon Chase Turbo
- Creature In The Well
- Bridge Constructor: Walking Dead
- Hell Is Other Demons
- Minit
- Overcooked 2

These still don't work:
- Cave Story +
- Sonic Mania
- Among Us
- Sludge Life 

Thanks again for all your work on this project.
