### ISSUE TITLE
No Bluetooth Menu

### ISSUE THREAD

**Issue by godtoall82** [ChimeraOS/chimeraos#243]
Just replaced Windows with ChimeraOS. Install was smooth but when I go into the settings, there is no option for Bluetooth. It was working with Windows before switching over so there isn’t an issue with the module. Anyone else have this problem?

**Comment by Samsagax** [comment]
> Just replaced Windows with ChimeraOS. Install was smooth but when I go into the settings, there is no option for Bluetooth. It was working with Windows before switching over so there isn’t an issue with the module. Anyone else have this problem?

Which Bluetooth hardware do you have? Maybe is a missing firmware. Did it work on any other GNU/Linux distribution?
Would you be able to test via SSH to the system to see if the bluetooth driver is working and the daemon is running?

**Comment by godtoall82** [comment]
> > Just replaced Windows with ChimeraOS. Install was smooth but when I go into the settings, there is no option for Bluetooth. It was working with Windows before switching over so there isn’t an issue with the module. Anyone else have this problem?
> 
> Which Bluetooth hardware do you have? Maybe is a missing firmware. Did it work on any other GNU/Linux distribution?
> Would you be able to test via SSH to the system to see if the bluetooth driver is working and the daemon is running?

So I installed Ubuntu to see if I ran into the same issue and I did, no Bluetooth. I then reinstalled Windows and Bluetooth worked. Maybe the module isn’t compatible with Linux? 

I am using the onboard Wi-Fi/Bluetooth adapter that came with the Asrock B550 gaming ITX mobo.

**Comment by Samsagax** [comment]
I think you'll have to give a little more detail about the adapter. What's the output of `lspci` and `lsusb`? Most Bluetooth adapters are part of a combo with wifi and there are others that are USB connected. Maybe is a case of missing firmware or you'll need an off-tree kernel module. Either way we need to know which specific model it is to help you further.

**Comment by godtoall82** [comment]
> I think you'll have to give a little more detail about the adapter. What's the output of `lspci` and `lsusb`? Most Bluetooth adapters are part of a combo with wifi and there are others that are USB connected. Maybe is a case of missing firmware or you'll need an off-tree kernel module. Either way we need to know which specific model it is to help you further.

Network controller: Intel WiFi 6 AX200 (rev 1a)

How can I check the firmware?

**Comment by Samsagax** [comment]
> Network controller: Intel WiFi 6 AX200 (rev 1a)

Firmware for that card is already baked into the build and those a re well supported. So I think the issue is another well documented BIOS/Firmware bug affecting some of the 500 series motherboards with USB power (I had faced it myself)

Try this: turn off the PC completely, then unplug it for a few minutes, replug it and power on. Then test again with any live CD distro. [There has been reported](https://bbs.archlinux.org/viewtopic.php?id=257478) that this issue is pseudo-random and that fixes it temporarily.

I think AMD found a bug about this not so long ago in AGESA (a binary blob that controls the chip) and you should check if your MoBo has a version post 1.2.0.1 for it to work without issues. Needless to say, the BIOS flash itself is a risky procedure and you should be careful.

**Comment by godtoall82** [comment]
> > Network controller: Intel WiFi 6 AX200 (rev 1a)
> 
> Firmware for that card is already baked into the build and those a re well supported. So I think the issue is another well documented BIOS/Firmware bug affecting some of the 500 series motherboards with USB power (I had faced it myself)
> 
> Try this: turn off the PC completely, then unplug it for a few minutes, replug it and power on. Then test again with any live CD distro. [There has been reported](https://bbs.archlinux.org/viewtopic.php?id=257478) that this issue is pseudo-random and that fixes it temporarily.
> 
> I think AMD found a bug about this not so long ago in AGESA (a binary blob that controls the chip) and you should check if your MoBo has a version post 1.2.0.1 for it to work without issues. Needless to say, the BIOS flash itself is a risky procedure and you should be careful.

This got it working. Unplugged for an hour, nothing. Updated the BIOS, nothing. Then unplugged for an hour AFTER the BIOS update and Bluetooth is now working. 

Thanks for your help!
