### ISSUE TITLE
Need to add redirect/grab for backwards compatible gameros.local address

### ISSUE THREAD

**Issue by freddyyeddy** [ChimeraOS/chimeraos#246]
I had to search and made a guess that  it was now chimeraos.local now instead. Would also be awesome to get a change log highlight on first boot of update on the device so users could know about these little changes in the future.

**Comment by alkazar** [comment]
The change log is an interesting idea. You can sort of get that if you join the Steam group.

**Comment by Samsagax** [comment]
The same anouncement can be done in the release notes here in GitHub, maybe we should try that.

**Comment by alkazar** [comment]
> The same anouncement can be done in the release notes here in GitHub, maybe we should try that.

Release notes are already linked to in the GitHub release. I don't think many people actually look at the releases since you can't download the releases directly anyway.
