### ISSUE TITLE
Kernel patch

### ISSUE THREAD

**Issue by cwalker** [ChimeraOS/chimeraos#250]
Hello!
I will try add usbip client (virtualhere) on chimeraos.
But an error occurs when starting the device.
https://www.virtualhere.com/content/android-server-client-archlinux
It is possible to apply this kernel patch and rebuld usbip modules?

**Comment by Samsagax** [comment]
Hello @cwalker.
We use the default Linux kernel without patches from ArchLinux. If that patch can make it into mainline we will include it that way. I see you are trying to use ChimeraOS in a VM, we currently don't support it as we use it to test but not regular usage.
The Xbox drivers for the dongle are present and should work as in any other Linux distribution.

**Comment by cwalker** [comment]
No, i'm not use VM.
This is Steam Remote Play (enabled in ChimeraOS)  + Steam Link (Android TV app).
Need usbip connection for use XBOX Adapter and BT controller.

**Comment by Samsagax** [comment]
Oh. I see.
The best way to support it is to that patch to be accepted upstream. We may break something else if we poke around commenting random code. Nevertheless if you are keen on doing it you can compile it yourself, but first you would need to unlock frzr:
`$ sudo frzr-unlock`
Then you will have an ArchLinux system you can use to experiment.

Also I'm not that familiar with Xbox controllers and their variants but maybe you can report to the xpadneo and xow developers that may help you further.

**Comment by virtualhere** [comment]
This is Michael from VirtualHere. I have patched the kernel and it has been accepted into mainline and the fix will be released in 5.15
