### ISSUE TITLE
Unable to rotate screen for PC handheld One X Player

### ISSUE THREAD

**Issue by project-sbc** [ChimeraOS/chimeraos#251]
Hi, I’m trying to rotate the screen left to accommodate the portrait display in my one x player gaming handheld with intel xe i7 1165g7. Using the shell I was unable to xrandr —rotate left for my output, error crtc 0 failed. I’m also unable to get to the desktop after enabling in the settings.

**Comment by project-sbc** [comment]
Thanks in advance

**Comment by alkazar** [comment]
How is the screen rotated by default?

You can customize the rotation by editing
~/.config/steamos-compositor-plus

You can uncomment and change ROTATION
to left, right, or normal.

There is no desktop mode.

**Comment by project-sbc** [comment]
Thanks for the feedback! I modified the last line to ROTATION=“LEFT”

and there wasn’t any change

I then tried adding the native display resolution 2560x1600 display so I uncommented that and added 2560x1600

Still no change, did I enter something incorrect?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Samsagax** [comment]
Did you restarted your PC/session after the change?

**Comment by project-sbc** [comment]
Yes I have rebooted after every change

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by project-sbc** [comment]
I made a video if diagnosing it makes it easier

https://youtu.be/_I8TYF735GY


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Samsagax** [comment]
You mentioned you tried using xrandr. For it to work from a Terminal you need to provide the appropriate `DISPLAY` environment variable like so:
`$ DISPLAY=:0 xrandr -o left`
Could you test if it works?

**Comment by alkazar** [comment]
You need to put:
ROTATION=left

**Comment by project-sbc** [comment]
Display=:0 xrandr -o left yields an error of failed to changed screen configuration

changing config file doesn’t change it either

**Comment by Samsagax** [comment]
> Display=:0 xrandr -o left yields an error of failed to changed screen configuration
> 
> changing config file doesn’t change it either

Be aware that capitalization is important. Linux (and most OS apart from DOS-based ones) are case-sensitive.

**Comment by project-sbc** [comment]
Thanks for the feedback, incorrect capitalization yields a “can’t open display” error, which is different than the correct syntax

**Comment by Samsagax** [comment]
Does it run with root privileges (i.e. sudo)?

`$ DISPLAY=:0 sudo xrandr -o left`

**Comment by project-sbc** [comment]
Fixed it, I had to uncomment the good resolution and good rates and add the screen resolution to the list in the steamos compositor plus. The touchscreen did not rotate, is there a way to rotate that in that config file?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Samsagax** [comment]
Great that worked for you. You might need to fiddle around with xorg.conf file specific for that device. Both screen and touchscreen rotation can be set up by it.

For reference: https://wiki.archlinux.org/title/Tablet_PC#Rotation

**Comment by project-sbc** [comment]
Thanks for your help, will close this
