### ISSUE TITLE
[Request] Add driver from AUR rtl88x1bu

### ISSUE THREAD

**Issue by lennyhans** [ChimeraOS/chimeraos#253]
Hi, had to fight every update installing this driver, do you think it is possible to add it to the drivers available?

It requires dkms.

Thanks in advance!

**rtl88x2bu AUR** : https://aur.archlinux.org/packages/rtl88x2bu-dkms-git/

**Comment by Samsagax** [comment]
I think it can be possible. Did you manage to install it and make it work?

**Comment by lennyhans** [comment]
Yeah,
1. Unlock frzr
2. Install git
3. Get de AUR repo
4. Update system
5. Install base-devel
6. Install packages dkms linux-headers bc
7. makepkg
8. Install the compiled package

Done.

Now, make it work with the installer I am not sure, I saw that `frzr` is a AUR package, so maybe I it easy enough to add it there but I do not know what about the dkms and the headers.
