### ISSUE TITLE
Issues with EA Games

### ISSUE THREAD

**Issue by godtoall82** [ChimeraOS/chimeraos#256]
I downloaded some EA games from the Steam Store and when playing, the games lose focus and the Origin Client keeps popping in and out. It's making the games unplayable. Also, the EA games seem to only recognize my DS4 controller, not my Steam controller. When I try to use the Steam controller, the controls show keyboard and mouse. Any fixes for these?

**Comment by HaydenS3** [comment]
Not a developer, but this sounds like an issue with Proton. You can check out [https://www.protondb.com/](url) to see gaming reports for any game on steam. Hopefully the reports can help you fix your issue.

**Comment by alkazar** [comment]
This should be fixed now. I modified the SteamOS compositor to select windows in a more stable manner (order of appearance).

Please re-open if this is still an issue.
