### ISSUE TITLE
How to downgrade? + How to turn off upgrades?

### ISSUE THREAD

**Issue by linuxgaming** [ChimeraOS/chimeraos#262]
Is there a way to downgrade from 25 to 24 and make it stay (so it doesn't upgrade by itself)?
frzr-deploy seems to only understand stable/unstable and not a specific version, so how else can I do it, maybe manually (download gameros-24_d5ee4b6.img.tar.xz but then what)?

**Comment by Samsagax** [comment]
Downgrades are not supported. But what specific bug do you have that requires a downgrade?

**Comment by linuxgaming** [comment]
I'm just tired of fixing stuff after every upgrade (thus the question how to turn them off). This time specifically, all proton games and flatpack games (minecraft...) stopped working. I tried some of that: https://github.com/ChimeraOS/chimeraos/issues/247 but with not luck. I figured I could just downgrade to the last-working-version but apparently not...

**Comment by alkazar** [comment]
When Nvidia drivers are upgraded, you have to re-install Minecraft so that flatpak picks up the latest Nvidia driver updates.

For proton games, you may be affected by an issue in Steam. Try disabling shader caching.

**Comment by Samsagax** [comment]
Can you test if in current testing build the problem persists? (You can go back from testing to stable)
`$sudo frzr-deploy chimeraos/chimeraos:testing` 

to go back: `$sudo frzr-deploy chimeraos/chimeraos:stable`

**Comment by linuxgaming** [comment]
"When Nvidia drivers are upgraded, you have to re-install Minecraft so that flatpak picks up the latest Nvidia driver updates."

that was the case with previous upgrades and of course I did that, but didn't help this time

"Can you test if in current testing build the problem persists? (You can go back from testing to stable)"

yes, I did that before creating the issue, no, it didn't change anything :-( 

All proton games and minecraft were stuck on the loading screen (the blue one with three blinking stripes). Native games work normally.

Now, I reverted all the changes and redeployed the stable version, as well as opted-out of steam beta, minecraft works but proton games give the

**Comment by linuxgaming** [comment]
So anyway, getting back on track, what is the best way to turn off system upgrades? Can I just remove/rename some script etc?

**Comment by Samsagax** [comment]
To stop updates entirely you need to disable the `frzr-autoupdate.timer` from systemd.
I would highly recommend against doing that. The best course of action is to figure out what are your issues and work them out for future releases so they won't affect you (and potentially other users).
