### ISSUE TITLE
Retroarch Crashing on GameCube Emulation

### ISSUE THREAD

**Issue by HaydenS3** [ChimeraOS/chimeraos#264]
I've been unable to get any GameCube games running through steam-buddy. Specifically I've been trying to get Mario Kart Double Dash running. I've tried using both the scrubbed nkit version of the iso and the original, both crash before the core launches. 

When running `gc MarioKartDoubleDash.iso` from the command line it throws the following error:
`terminate called after throwing an instance of 'std::system_error'`
`what():  Invalid argument`
`/usr/share/steam-buddy/bin/launcher: line 49:  3171 Aborted                 (core dumped) retroarch --appendconfig "${RETRO_CONFIG}|${CORE_CONFIG}" --libretro /usr/lib/libretro/${RETRO_CORE}_libretro.so "$@"`

Is this an upstream RetroArch issue or something I can fix locally?

**Comment by alkazar** [comment]
I suspect your GPU does not support Vulkan and you may need to set RetroArch to use OpenGL instead.

Are you able to play any games for other consoles?
What GPU are you using?

**Comment by HaydenS3** [comment]
I am using an RX580 and I have been able to run Dreamcast, NES, N64, and Genesis.

**Comment by alkazar** [comment]
Okay, then it is not a Vulkan issue. The same game works for me, so it could be your ROM. Have you tried other GameCube games?

**Comment by HaydenS3** [comment]
I haven't tried other games (my download and upload speeds are not the best). The two ROMs I tried were Mario Kart Double Dash from both Vimm's Lair and CDRomance. I can try downloading and testing other ROMs, do you have another source for ROMs that may work better?

**Comment by alkazar** [comment]
Sorry, I cannot provide information on where to download ROMs.

Could it be that your download or the upload to ChimeraOS was corrupted?
What is the md5sum of your .iso file on ChimeraOS?

**Comment by HaydenS3** [comment]
97f9ebc39ab4244e419848793988561a  MarioKartDoubleDash.iso

The hashes match from my laptop and my pc running ChimeraOS. I also installed Dolphin on my laptop and the ROM worked normally there. I'm thinking this has to rule out any issue with the ROM itself.

**Comment by alkazar** [comment]
So I dusted off my old AMD GPU (RX 570) and was able to reproduce.
For some reason Nvidia works, but not AMD :shrug: 

I was able to get GameCube working by forcing RetroArch into OpenGL mode.
I'll default to OpenGL for GameCube in the next release.

For now you can drop the following in `~/.config/steam-buddy/gc.cfg`:
```
dolphin_efb_scale = "x3 (1920 x 1584)"
input_player1_analog_dpad_mode = "0"
input_player2_analog_dpad_mode = "0"
input_player3_analog_dpad_mode = "0"
input_player4_analog_dpad_mode = "0"
video_driver = "gl"
```

**Comment by HaydenS3** [comment]
Amazing, thank you so much!
