### ISSUE TITLE
Issue playing local multiplayer on GameCube

### ISSUE THREAD

**Issue by HaydenS3** [ChimeraOS/chimeraos#265]
It seems only one controller works on the GameCube emulator. I was able to recreate this issue on my Ubuntu laptop with the Flatpak install of Retroarch. I was also able to fix the issue on my laptop following the advice given here: [https://forums.libretro.com/t/solved-dolphin-gamecube-2-players/13686/2](url). 

I would apply the same fix to my system running ChimeraOS, but I am unable to find `Dolphin.ini`. On my laptop it was located in `/home/user/.var/app/org.libretro.RetroArch/config/retroarch/saves/User/Config/Dolphin.ini`

Things I have tried on my ChimeraOS system:
Creating the `Dolphin.ini` in  `/home/gamer/.local/share/steam-buddy/saves/gc/User/Config/`
Creating `User/Config/Dolphin.ini` in `/home/gamer/.config/retroarch/saves`

**Comment by HaoleCake** [comment]
I was originally having the same issue but I was able to edit a `Dolphin.ini` generated from Retroarch on my PC using the same method you posed and placed it into `/.local/share/steam-buddy/saves/gc/User/Config`. That seems to have fixed it for me as I am now able to play with two controllers.

**Comment by HaydenS3** [comment]
After copying the Dolphin.ini file from my laptop to my ChimeraOS machine it worked flawlessly. Before I had only created the file with those SIDevice values. Thank you so much!
