### ISSUE TITLE
Wake-On-Lan is not working

### ISSUE THREAD

**Issue by cbodenst** [ChimeraOS/chimeraos#266]
Hi,

first I want to say thanks for all the work behind chmeraos.

My problem is that i can not use the steam link app to wake my chimeraos box, since the driver for my network device has WOL disabled.

I found patches/fixes for this issue and I think I would be able to install it on a normal Arch installation but since chimeraos uses frzr i am not sure whats the best way to update the kernel driver.

The PKGBUILD can be found here:
https://github.com/jhwshin/alx-wol-dkms

Any suggestions how the patch could be applied and is it possible to integrate it into a future release?

**Comment by alkazar** [comment]
I don't think we will be able to apply this. Would have to try to get it upstreamed.

**Comment by pastaq** [comment]
There is an AUR package. https://aur.archlinux.org/packages/alx-wol-dkms
Could be a candidate for the post-install script blacklist/enable
