### ISSUE TITLE
Unable to Alt-Tab into other windows when needed

### ISSUE THREAD

**Issue by chowder3907** [ChimeraOS/chimeraos#270]
When another window opens (for example the window to login to a microsoft account through the bedrock launcher) there is no way to switch over to it leaving a few apps useless.

**Comment by alkazar** [comment]
> > That's right. There isn't. The compositor won't allow it. Is a single window only compositor so only the last window gets focus.
> > That why "Launchers" are a pain.
> 
> I feel like launchers are a pretty important thing to have be functional in a PC gaming distro

I feel like launchers have no place on a gaming console, which is what ChimeraOS is trying to replicate.

That being said, if it is a windowing issue, you can temporarily switch out to a more desktop-like windowing system that has alt-tab. Just open the Chimera app, go to the "Actions" page and select "Window mode".
