### ISSUE TITLE
RetroArch Configuration - Dolphin RGUI

### ISSUE THREAD

**Issue by Deividms11** [ChimeraOS/chimeraos#273]
How can I enable the RGUI configuration menu during GameCube games on dolphin? I was able to do it before but now I can't re-enable it. Already tried change some lines in the retroarch.cfg file but nothing has worked.

**Comment by alkazar** [comment]
It has always been disabled. The quick menu interferes with the Steam overlay.

You could probably launch RetroArch directly and configure a new button combination to open it.

What do you need to use the quick menu for?

**Comment by Deividms11** [comment]
I was able to stretch 4:3 to 16:9 avoiding the black bars. I searched for this option at the cfg file but didn't find the line to do it yet.

**Comment by alkazar** [comment]
Some GameCube games support 16:9 natively, but you have to activate it in
the game's options.

The config file doesn't contain all the options. You have to lookup the
available options in the libretro documentation.

I'll look it up for you when I have some more time, if you can't find it.

**Comment by Deividms11** [comment]
Thank you so much!!! You don't need to hurry, I'm still enjoying the system playing my other games! ChimeraOS is awesome!!

**Comment by Samsagax** [comment]
Closing as old. If it is still relevant, open up again. Be aware that RetroArch configurations can be edited in cfg files if needed.
