### ISSUE TITLE
Support for ntfs-3g and ldmtool

### ISSUE THREAD

**Issue by esaudet** [ChimeraOS/chimeraos#283]
I share a NTFS drive with a windows installation and it would be nice if we can add support for `ntfs-3g` and `ldmtool` packages. 
At every new release, I have to install these packages manually using pacman.

**Comment by alkazar** [comment]
My understanding from everything I have read is that the majority of games do not work when run from an ntfs file system. Furthermore, the new kernel included in ChimeraOS 28 (5.15) includes a native ntfs driver. Have you tried using that?

**Comment by esaudet** [comment]
Indeed it's working really well with the new NTFS3 driver! No need of `ntfs-3g` anymore... For `ldmtool` I understand that it is just a custom need for me at this time because my windows drive is using a dynamic disk.  Maybe I can convert it to a standard disk to completely resolve the issue. 

In the meantime, is there a way to hook a post upgrade script on a new realease?

Thanks!

**Comment by alkazar** [comment]
No, there is not.
