### ISSUE TITLE
Gamescope & Pipewire

### ISSUE THREAD

**Issue by aleksasiriski** [ChimeraOS/chimeraos#287]
Is there any plan on switching from steamos-compositor-plus to gamescope session? As well as pipewire for audio?

**Comment by Samsagax** [comment]
The problem with Gamescope is that it won't work on Nvidia cards, no matter what we or Valve do, unless Nvidia supports some vulkan extensions that currently doesn't.

As for pipewire, all is there, just need to pull the trigger on pipewire-pulse package and drop pulseaudio. As far as I've tested it works flawlessly.

**Comment by alkazar** [comment]
I have tried switching to pipewire and it resulted in broken audio. Maybe I will try again at some point.

**Comment by aleksasiriski** [comment]
> I have tried switching to pipewire and it resulted in broken audio. Maybe I will try again at some point.

Would you consider perhaps switching to booster from mkinitcpio and linux-zen?

**Comment by aleksasiriski** [comment]
> The problem with Gamescope is that it won't work on Nvidia cards, no matter what we or Valve do, unless Nvidia supports some vulkan extensions that currently doesn't.
> 
> As for pipewire, all is there, just need to pull the trigger on pipewire-pulse package and drop pulseaudio. As far as I've tested it works flawlessly.

Could there perhaps be a Gamescope version of ISO for ChimeraOS, or in the installer for people to choose?

**Comment by Samsagax** [comment]
> Could there perhaps be a Gamescope version of ISO for ChimeraOS, or in the installer for people to choose?

The default ChimeraOS image ships Gamescope session already but is not turned on by default. You can switch with these commands:

```
$ sudo systemctl disable lightdm.service
$ sudo syatemctl enable gamescope@tty1.service
```

Then reboot. The change will persist updates of the distribution.
