### ISSUE TITLE
RZ608 MT7921K WiFi Support for Aya Neo Pro/Retro Power

### ISSUE THREAD

**Issue by pastaq** [ChimeraOS/chimeraos#288]
The Aya Neo Pro and Retro Power come with a newer revision of the WiFi/BT module than the standard version. The RZ608 MT7921K uses the same driver, but the alias for the revision is not in the kernel driver that is shipped in the latest release. As network connectivity is required for the install to complete, this prevents install of ChimeraOS on this version of the device.

Possible Solutions:
Implement the module patch that adds support in the kernel from here: https://patchwork.kernel.org/project/linux-wireless/patch/84ab45bf42f57fd0301c156ffc11d0fe330ff1f8.1636857817.git.deren.wu@mediatek.com/

Implement a udev/modprobe rule as specified in the following thread: https://askubuntu.com/questions/1376871/rz608-mt7921k-wireless-lan-driver-is-not-supported-on-ubuntu-18-04

relevant portions, two files will be needed: 
/etc/modprobe.d/rz608.conf
alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e

/etc/udev/rules.d/99-rz608.rules
SUBSYSTEM=="drivers", DEVPATH=="/bus/pci/drivers/mt7921e", ATTR{new_id}="14c3 0608"

I have been able to install Manjaro on the AN Pro using the udev/modprobe method, but the installer for chimeraos doesn't show any networks after implementing a temp alias via echo 14c3 0608 > /sys/bus/pci/drivers/mt7921e/new_id or with the files method above.

I am willing to test and/or help implement a fix via a PR. I will just need direction from the community which of these two methods, or an additional one I haven't mentioned here, would be best for the project.

**Comment by alkazar** [comment]
I was hoping this would be in the 5.16 kernel, but looks like it won't be.

We don't have the infrastructure/setup for custom building the kernel or kernel modules.

I think the options are:
 - wait for kernel support
 - implement the udev/modprobe rules

**Comment by Samsagax** [comment]
Why not starting with the modprobe+udev rule and when the kernel keeps up just remove it?

**Comment by alkazar** [comment]
> Why not starting with the modprobe+udev rule and when the kernel keeps up just remove it?

That makes sense, assuming the hack works, which we haven't yet been able to confirm.

**Comment by pastaq** [comment]
Workaround had to be implemented in both the installer-media and ChimeraOS repo's. I was able to connect to WiFi and install with these changes.

**Comment by alkazar** [comment]
@pastaq amazing, thank you!

**Comment by alkazar** [comment]
@pastaq Do you happen to know if this change also enables bluetooth to work?

**Comment by pastaq** [comment]
> @pastaq Do you happen to know if this change also enables bluetooth to work?

It doesn't as far as I can tell. No BT device shows up in the BT menu. I believe this is an issue with all the versions of this device driver. From the Arch Wiki it shows BT not working on all devices. https://wiki.archlinux.org/title/AYA_NEO_2021

**Comment by Susurrus** [comment]
I've been trying to maintain the Arch wiki page and did a little cleanup today: https://wiki.archlinux.org/title/AYA_NEO_2021. Feel free to let me know if there's any extra details I should add.

**Comment by pastaq** [comment]
> I've been trying to maintain the Arch wiki page and did a little cleanup today: https://wiki.archlinux.org/title/AYA_NEO_2021. Feel free to let me know if there's any extra details I should add.

The only thing I would change is the PRO BT module requires the same workaround that the WiFi module does, as its the same physical card/driver.

**Comment by Susurrus** [comment]
Added, thanks!
