### ISSUE TITLE
Latest installer gave me a blinking cursor after restart

### ISSUE THREAD

**Issue by Thijzer** [ChimeraOS/chimeraos#291]
Hi,
I can't install the lastest ChimeraOS anymore on my system.
Over the restart prompt, my computer restarted with a blinking cursor.

My system
```
Xeon E3-1200 v2/Ivy Bridge
16GB DDR3
Asus P8H61-I
Dell Geforce 750 TI
```

I was able to install this system in the past.

**Comment by Thijzer** [comment]
This might be a serious issue as I had no issues in the past installing on this system.

**Comment by alkazar** [comment]
This is with a clean install? Or did you experience this issue after an update?

**Comment by Thijzer** [comment]
No clean install comming from chimeraos-2022.01.03-x86_64.iso

**Comment by alkazar** [comment]
Can you try the old installer?

https://github.com/ChimeraOS/install-media/releases/download/2021-07-01/chimeraos-2021.07.01-x86_64.iso

**Comment by Thijzer** [comment]
Ok I will

**Comment by Thijzer** [comment]
@alkazar yup the old installer works. Solved my problem.

**Comment by Thijzer** [comment]
I will close this issue, but you might want to point the website to the old installer.
Thanks for the quickest response ever @alkazar :)
I just prepped my device for a second hand sale, node 202 + ChimeraOS and a steam controller.
Will this sell? We will find out!
