### ISSUE TITLE
ChimeraOS Won't Boot Following Clean Install

### ISSUE THREAD

**Issue by titan-91** [ChimeraOS/chimeraos#293]
When installing ChimeraOS on a blank internal SATA hard drive, the OS will not boot when the machine is restarted. I can run other Arch based distributions such as GamerOS (before the merge to ChimeraOS) with the same UEFI settings on the machine. When checking the partitions following installation, the 512MB FAT partition is present along with the main ChimeraOS partition, but the EFI boot file(s) are not present. To be specific, the EFI/BOOT directories were not installed normally containing syslinux.efi and bootx64.efi. 

I would like for someone to confirm if the below change to the frzr download/update utility may have caused it. Or if I'm doing something wrong. I was, however, able to get the OS to boot by installing on top of an existing Ubuntu drive because the required EFI partition, directories, and files were already present. 

frzr-bootstrap
don't install to EFI/syslinux anymore

**Comment by Samsagax** [comment]
Maybe [this commit](https://github.com/ChimeraOS/frzr/commit/94ae0729521704797d1f00543eac76565eea895e) is the one to blame?

**Comment by alkazar** [comment]
frzr-bootstrap now installs to EFI/BOOT instead of EFI/syslinux

Perhaps you still have the old UEFI boot entry which is trying to look in the old location?

**Comment by titan-91** [comment]
> Maybe [this commit](https://github.com/ChimeraOS/frzr/commit/94ae0729521704797d1f00543eac76565eea895e) is the one to blame?

Yes, that's the one I identified.



> frzr-bootstrap now installs to EFI/BOOT instead of EFI/syslinux
> 
> Perhaps you still have the old UEFI boot entry which is trying to look in the old location?

Possibly, but the UEFI boot list on the PC showed two frzr entries and neither worked. I deleted those and tried to add a new one then determined the EFI/BOOT directories were not present after installation.

**Comment by alkazar** [comment]
There should be no `frzr` boot entries. To boot Chimeraos you should select the disk you installed it to in the bios boot options.

> Possibly, but the UEFI boot list on the PC showed two frzr entries and neither worked. I deleted those and tried to add a new one then discovered the EFI/BOOT directories were not present after installation.

Double check you are looking at the right partition and that you didn't perform a legacy BIOS install.

**Comment by alkazar** [comment]
I was not able to reproduce. Most likely the issue is that you selected the old boot entries. Another possibility is it could be hardware/bios specific.

**Comment by titan-91** [comment]
Good to know. I didn't see any other place where this was mentioned so I will close this issue. Thanks for the insight.
