### ISSUE TITLE
Can't access system information for ProtonDB

### ISSUE THREAD

**Issue by mdeguzis** [ChimeraOS/chimeraos#294]
Is there a way to get this? I've long been frustrated by not being able to post my feedback on ProtonDB. Without a desktop mode, it's hard to even work around this. Any thoughts? I've tried parsing the commands on `steam -console` > console tab on my laptop, steamcmd, and other various options.

My request to Valve did not get any traction: https://github.com/ValveSoftware/steam-for-linux/issues/5917

**Comment by alkazar** [comment]
There is a command built in that outputs system information in a format protondb accepts:
`/usr/share/chimera/bin/system-info`

The idea is to eventually hook this up so it is accessible from the chimera web app, just hasn't been done yet.

**Comment by mdeguzis** [comment]
I was working on this exact thing thank you so much! I'll probably be able to get around the dependency if this not a monstrous one.

**Comment by mdeguzis** [comment]
Is ChimeraOS purposefully removing keys? Most packages after `sudo frzr-unlock` get key errors
```
Packages (1) archlinux-keyring-20220125-1

Total Download Size:   1.01 MiB
Total Installed Size:  1.43 MiB
Net Upgrade Size:      0.08 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 archlinux-keyring-20220125-1-any                          1036.5 KiB  1440 KiB/s 00:01 [###################################################] 100%
(1/1) checking keys in keyring                                                          [###################################################] 100%
(1/1) checking package integrity                                                        [###################################################] 100%
error: archlinux-keyring: signature from "Christian Hesse <eworm@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/archlinux-keyring-20220125-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.

```

**Comment by alkazar** [comment]
Nope. Not sure what the trouble could be, installing packages usually works after `frzr-unlock`.

**Comment by alkazar** [comment]
Alternatively, you could switch to the testing channel which has ChimeraOS 30 where this issue has been fixed.

You can switch with: `sudo frzr-deploy chimeraos/chimeraos:testing`

**Comment by mdeguzis** [comment]
We can consider this closed since a solution was presented.
