### ISSUE TITLE
unable to login into account

### ISSUE THREAD

**Issue by coreybruce** [ChimeraOS/chimeraos#296]
Hey guys I just wanted to report a weird issue, I am unable to login into my steam account on ChimeraOS but obviously on my PC or on my phone I have no problems but when I login with the correct details it will say it's wrong.

I even did a password reset and changed to a shorter one while also double checking to make sure it was correct.

**Comment by mwprado** [comment]
I can't log in either. I only see a blue screen.

**Comment by mdeguzis** [comment]
> I can't log in either. I only see a blue screen after the last update (31)

This may be a separate issue. See https://github.com/ChimeraOS/chimeraos/wiki/ChimeraOS-Troubleshooting#after-steam-logs-me-in-i-get-a-blank-blue-screen and open a new issue if you still encounter issues.

**Comment by mwprado** [comment]
> > I can't log in either. I only see a blue screen after the last update (31)
> 
> This may be a separate issue. See https://github.com/ChimeraOS/chimeraos/wiki/ChimeraOS-Troubleshooting#after-steam-logs-me-in-i-get-a-blank-blue-screen and open a new issue if you still encounter issues.

You're right! I can login again.

**Comment by alkazar** [comment]
Is this still an issue or was the blue screen issue noted above?

**Comment by coreybruce** [comment]
I'd have to check if I still have the issue

**Comment by Samsagax** [comment]
> I'd have to check if I still have the issue

@coreybruce did you check if it still the case. If it is, feel free to comment and we will reopen the issue.

**Comment by coreybruce** [comment]
I'll have to download the latest version and check, I will get back to you

**Comment by coreybruce** [comment]
Well I was booting it up after installation but it's failing to boot..

![Uploading IMG20220527211352.jpg…]()

**Comment by coreybruce** [comment]
![IMG20220527211352](https://user-images.githubusercontent.com/8393780/170689586-8430c0fa-2d48-4ff1-9f38-6b0d344b06dc.jpg)

**Comment by Samsagax** [comment]
That is a new issue. Could you please report it in a new ticket? We know about it and we are investigating it but we need some more info.
Are you booting from an USB by any chance? That seems to be problematic in some cases with the implementation of external libraries.

Cc @pastaq

**Comment by coreybruce** [comment]
Yeah I'll start a new issue for this and yeah I installed it on a portable USB 3 drive but the old version didn't have a issue with it
