### ISSUE TITLE
Implementation of quick suspend / resume

### ISSUE THREAD

**Issue by marcelschoen** [ChimeraOS/chimeraos#297]
I heard that Valve implemented a proper quick suspend / resume feature in SteamOS. This is a big issue for a mobile device like the Aya Neo. I have currently ChimeraOS running on it, and it's great, but this one issue is a real problem when your game doesn't allow you to quicksave at any given moment. Not to mention that after switching the Neo off you'll have to restart the game from scratch. 

So my question is if it's feasible, and possibly even planned, to bring such a feature to ChimeraOS?

**Comment by pastaq** [comment]
Issue resolved by #300

**Comment by alkazar** [comment]
Suspend/resume when pushing the power button was enabled in ChimeraOS 32.
