### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by massatt212** [ChimeraOS/chimeraos#301]
gnome-disk-utility

can make mounting external disk much easier
i have 2TB of games on an external and i had to uninstall chimeraOS.

**Comment by alkazar** [comment]
That wouldn't be usable with Big Picture Mode.

**Comment by massatt212** [comment]
What's the easiest way to mount extra hdds?

**Comment by mdeguzis** [comment]
You can SSH into the host and mount drives on the CLI. Adding them to Steam is another story, but some discussion has happened around it. Something I was interested in tackling myself in the near future, but would need to run it by @alkazar with a PR or something of that nature.
