### ISSUE TITLE
Many Chimera actions do not work

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#318]
e.g.
 - restart steam
 - performance overlay
 - steam overlay

This is due to the use of sxhkd which is Xorg specific.
We should switch to https://github.com/waycrate/swhkd which works with both Xorg and Wayland.

**Comment by pastaq** [comment]
Additionally, sxhkd remains enabled and spams journalctl with failure messages when switching to gamepadui. ```chimera-session gamepadui``` and ```chimera-session-use-gamescope``` should stop/disable the sxhkd service until swhkd is implemented.
