### ISSUE TITLE
Night mode does not work

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#319]
Works with `steam -gamepadui -steampal -steamos3 -steamdeck`

**Comment by TobiPeterG** [comment]
Hey there,
I'm developing an OS for jupiter based on openSUSE Aeon. Night mode doesn't work in gamescope, could you maybe provide a hint what fixed it? :)

**Comment by TobiPeterG** [comment]
> You need the hdr patches for it to work on newer gamescope versions.

Thank you very much for your answer :)
Unfortunately, I couldn't really find a lot about this online. Do you mean the HDR kernel patches? There are multiple sources I found (I guess you mean the second one?):
https://gitlab.com/evlaV/linux-integration/-/commits/6.1/features/amd-hdr-colorimetry/?ref_type=heads
https://gitlab.freedesktop.org/JoshuaAshton/linux-hdr/-/commits/josh-hdr-colorimetry

Have a nice day :)
