### ISSUE TITLE
Bluez 5.64 breaks Bluetooth

### ISSUE THREAD

**Issue by micahvdm** [ChimeraOS/chimeraos#324]
V32 included Bluez 5.64 which has a bug that breaks Bluetooth for some cards. I managed to resolve by updating bluez to 5.64-2. The update was released a few hours ago, might be worth pushing a fix.

**Comment by alkazar** [comment]
Thanks for bringing this to our attention. I don't want to push another release so soon. It will also take a while to validate a new OS image.

**Comment by micahvdm** [comment]
Yeah that sounds wise. Maybe a note on the changelog on how to fix it if anyone encounters it. It’s strange though because looking at the changelog, it says bluez 5.64-2 but on both times that I did a clean install, it installed 5.64. Maybe it’s something upstream that wasn’t pulling through…

**Comment by alkazar** [comment]
> Steps fwiw: sudo systemctl status bluetooth.service (to verify the service failed to start)
> 
> sudo mount -n -o remount,rw sudo mkdir /var/lib/pacman sudo pacman Sy (to update repo data) sudo pacman -Sdd bluez --overwrite "*" (to _only_ update bluez in a way that could probably cause damage to your system and is no doubt frowned on)

For future reference you don't need to do all that to get to a read-write system. You can simply do `sudo frzr-unlock`.

**Comment by Samsagax** [comment]
I think this is fixed on v33. Feel free to reopen if not.

**Comment by Mohandevir** [comment]
I know I'm not using ChimeraOS in a standard way, but I installed it on a Sager NP8678 (laptop) to bring it on the road... Bluetooth fails to initialize. It's got the Killer NT1535 with BT card. Tried connecting two different types of usb bt dongle (ASUS and another one that I can't identify. It  dIdn't work either. Any cue?

Thanks!

**Comment by RandomNinjaAtk** [comment]
I also ran into this issue, updating bluez also solved it for me, it would be nice if the image was updated with it...
