### ISSUE TITLE
Big Picture Mode flickering in desktop session

### ISSUE THREAD

**Issue by cwalker** [ChimeraOS/chimeraos#328]
I have a issue with home streaming in desktop session:
Screen flickering every 4-5 seconds.
It's old nvidia bug: https://github.com/ValveSoftware/steam-for-linux/issues/4351

nvidia-settings --assign="AllowFlipping=0" - resolve issue

Can add this package in chimeraos?
https://archlinux.org/packages/extra/x86_64/nvidia-settings/

**Comment by Samsagax** [comment]
Is this issue still relevant? The nvidia kernel driver has been updated a couple of times now. I'm closing this one for now. Feel free to reopen if the problem persists.
