### ISSUE TITLE
Change locale 

### ISSUE THREAD

**Issue by dza89** [ChimeraOS/chimeraos#330]
I'm getting am/pm time in Steam which seems to be caused by the locale set in arch:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Because the filesystem is mounted as read-only i cannot run locale-gen. 
I can think of some nasty ways to solve this but I cannot imagine i'm the only one with this problem.
What is the proper way to solve this?

**Comment by alkazar** [comment]
I think you will have to wait for the new UI to become standard. It includes an option for a 24 hour clock.

**Comment by dza89** [comment]
Thanks, that sounds interesting.
But that doesn't solve the actual problem, where is makes sense to be able to set the locale somewhere, probably during install, like other os-es. There is probably a good reason why this option isn't there though..

**Comment by Samsagax** [comment]
I think maybe we can generate all locales that steam supports (they are not as many). Then the switch should be as simple as a conf file.

**Comment by Samsagax** [comment]
Fixed on v37
