### ISSUE TITLE
Wifi (and Ethernet) not detected in steam UI

### ISSUE THREAD

**Issue by benklop** [ChimeraOS/chimeraos#331]
I have installed ChimeraOS on a dedicated machine with a wifi card installed, and steam doesn't seem able to detect the wifi card. I have an Ethernet cable attached temporarily, and it doesn't show that detected either, though it does work.

I was hoping to give this box to a friend who is moving and doesn't have a lot of Linux or PC experience. It would be very convenient if they could actually use WiFi with it.

Nmtui on the console does appear to work, but that's not going to be a good option for someone without the know how.

**Comment by benklop** [comment]
This is happening on v31

**Comment by benklop** [comment]
Just upgraded to v32 and this still appears to be the case

**Comment by benklop** [comment]
Additionally this makes it impossible to actually see the IP address, so makes it rather difficult to use the phone interface

**Comment by jasonmccollum** [comment]
I ran into this as well on a fresh install this weekend. Steam UI shows no network card detected, but is able to download games just fine. In my case, it was resolved by restarting the machine and now I can see network info just fine. Presumably, connecting to `chimeraos.local` would work since the OS is able to access the internet, but can't test it now since it's no longer doing this on my machine.

**Comment by benklop** [comment]
on this machine multiple reboots have not (yet) resolved the issue. I have modified a systemd script to persist nmtui on VT1 to work around the issue, but I wish i didn't have to.

**Comment by Samsagax** [comment]
Could you check if Network manager service is running? And if it is, could you check if it didn't spew any errors or warnings?

**Comment by alkazar** [comment]
Is this still an issue with the latest release?

**Comment by benklop** [comment]
sorry about not replying months ago! Network Manager was running, i was able to use nmtui to configure wifi just fine, but not the steam gui.

I no longer have this box in my posession, I was building it for a friend of my son. it's now a few thousand miles away.

**Comment by alkazar** [comment]
Thanks for the follow up. I guess I'll close this for now since there is nothing actionable.
