### ISSUE TITLE
ChimeraOS needs an easy option to install to a portable HDD/SSD

### ISSUE THREAD

**Issue by charlesRedwoodPlains** [ChimeraOS/chimeraos#335]
Hello :)

**FEATURE REQUEST**
_ChimeraOS needs an easy option to install to a portable HDD/SSD_

On Windows this can easily be done with Rufus and ticking the "Windows-to-go" feature. However steam games run better on Linux and it would be preferable to have a portable Linux rather than a portable Windows.

Here are two links where you can create a portable Ubuntu (the steps are tedious and difficult and hardly any users will go to such trouble):

- https://medium.com/@abrarahmedsyed/how-to-create-a-truly-portable-plug-n-play-ubuntu-installation-on-an-external-ssd-hdd-7aaadc7d796a
- https://www.58bits.com/blog/2020/02/28/how-create-truly-portable-ubuntu-installation-external-usb-hdd-or-ssd

**Comment by alkazar** [comment]
You can already install to an external disk in the same way that you install to an internal disk.

**Comment by charlesRedwoodPlains** [comment]
It's actually quite a difficult process to do that. Try following those
links i sent through and they will show you what i mean.

Creating a truly portable installation is not easy or fast right now.

**Comment by alkazar** [comment]
You are making assumptions. ChimeraOS is not Ubuntu.

The ChimeraOS installer:
1. always installs the boot loader to the target disk
2. does not add or manipulate UEFI boot entries

Therefore the installation produced is portable. I have just tested this to be sure.
