### ISSUE TITLE
Overlay and menus are not scaled correctly on displays above 800p

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#336]

**Comment by pastaq** [comment]
This issue was partially resolved with the recent Steam Client update. The default ```chimera-session gamepadui``` on v32 functions as intended with 800p UI scaling on larger resolutions. I have not tested with alternative flags or additional configs such as adding -steamos3.

**Comment by alkazar** [comment]
The scaling always worked when not using -steamos3 & -steamdeck options. Using -steamos3 & -steamdeck options continues to cause poor scaling even with the latest client.

**Comment by Samsagax** [comment]
To fix the scaling issue for the game overlay disable "OpenGL Composer" under the Developer options. That will make it work even when `-steamos3` and `-steamdeck` options are enabled.

(Thanks to j0rge on discord!)

**Comment by alkazar** [comment]
This issue appears to be resolved in recent Steam client versions.
