### ISSUE TITLE
Screen Rotation on Win Max

### ISSUE THREAD

**Issue by FlexibleToast** [ChimeraOS/chimeraos#339]
The screen on the GPD Win Max displays in portrait (rotated) during install. When it begins the SteamOS install it is still rotated in portrait, but now also has a weird ghosting effect and shows 4 images overlaid on each other. Makes it nearly impossible to see what is on the screen. I tried setting `~/.config/steamos-compositor-plus` to `ROTATION=right`, per the guide [here](https://github.com/ChimeraOS/steamos-compositor-plus/blob/master/README.md#configuration). That had no effect. I then saw Arch has a [wiki page](https://wiki.archlinux.org/title/GPD_Win_Max) for the Win Max and it explains that there isn't a correct screen configuration and you need to manually create a EDID file for it. However, when I tried to create it, I couldn't because the system is mounted read-only.

**Comment by alkazar** [comment]
Looks like you could put the EDID file anywhere. Try putting it somewhere under /etc
