### ISSUE TITLE
Catch All - Blank Screen Of Blue Deep Dive - What does actually NOT cause the issue?

### ISSUE THREAD

**Issue by Zeitwaechter** [ChimeraOS/chimeraos#344]
Hello everyone, I hope to do an effort for the whole community with this, as this seems necessary.

I would like to know what actually _not_ to do within SteamOS overlay, as it feels like it can't go on _as is_.

Issues that cause it (whatever _it_ exactly is) cannot just be fixed by accepting `visibility: hidden` - if you get my CSS pun - or deleting a file and resetting Steam files via terminal.

Okay, good, now please hear me out first.

## The Test System In Question

- CPU: Intel i7-4790
- RAM: 16GB DDR3 (2x8GB)
- GPU: Some old AMD R7 200 series card / AMD RADV TAHITI
- m.2: Some Western Digital stick (GPT formatted+btrfs)

So, besides the m.2 it's as old as it gets.

I currently do control the system via mouse and keyboard.
Only one display is attached - via GPU.

## Software Stack

The system is freshly installed today and `frzr-unlocked`. But no `pacman -Syu` was done. 

`pacman -S fish` was utilized and is used as main shell though, but not set as default for `gamer` or `root`.

I do tend to change the keyboard layout after I login via terminal.

(It might cause hitting ESC to not do what it should do after it.. hrmn...)

## The Known Causes Of The Blank Screen Or Nothingness UI Issue

Name it how you want, I don't care :paintbrush: 

Anyway, the known causes:

1. The issue with the blank screen can come from just activating Steam Play for "all other titles" in the settings menu of the Steam overlay, and then just selecting e.g. Proton 7.0-2. On the (forced) restart after that the UI does not show anymore.
2. This can also happen on "just" changing the steam server download region via UI, after first login and having a forced restart of Steam afterwards. 
3. Maybe the proclaimed cause of the multi GPU setup.. I don't know what to think about it.. but this sounds only SteamOS UI related.
4. You cannot login with your user via terminal anymore (also SSH, yes), due to well.. whatever.. check #231, if you got this as well (I appreciate any other _user_ input on that issue(!))

I can actually redo the steps and get the same result all the time (not checked for No. 4). It's sadly not so fun.

## "Workarounds"

1. `rm ~/.local/share/Steam/config/config.vdf && steam-runtime --reset`
2. `rm ~/.local/share/Steam/config/config.vdf && steam-runtime --reset`
3. `rm ~/.local/share/Steam/config/config.vdf && steam-runtime --reset`
4. Setup ChimeraOS anew

Then restart your PC manually by powering it off and on again - or by simply clicking "Restart Steam" via Steam Buddy Web Interface.

Type `ip a` on your ChimeraOS systems' terminal, if you do not know how to see the IP of your system.

Steam Buddy is the best and fastest way to go - API/Socket calls, yay.

#### Related to Known Cause No. 1

1. Games themselves do download
2. Select a Proton Version that is not already set within your `CompatToolMapping` section of your `config.vdf`
    - Checking the `config.vdf` first revealed that e.g. `GE-Proton7-10` is not set yet, but `GE-Proton7-9` is.
    - If you select e.g. `GE-Proton7-10` via SteamOS Overlay "it" does add a new entry with an `priority` that is not `209`, like the rest, but `75` and a config that is `""`. 
        - It also tends to add it with an ID of `0`, at the top/bottom of `CompatToolMapping` (depending on when you take a look at it, if you have rebooted first)
    - Selecting another Proton version, like `GE-Proton7-18` does only change the entry "0", nothing else seems to differ.
    - Restart Steam via Steam Buddy - no download was queued.
3. Select a Proton Version - like `GE-Proton7-9` - that is already set within your `CompatToolMapping` section of your `config.vdf`
    - No difference in behaviour or issue, like with the previous approach for an entry that was not yet referenced.
4. Just removing the entry afterwards, does not fix the issue of not seeing the UI after the restart of Steam.
5. Checking the `config.vdf` file on my normal Arch Linux system, the file is way longer, but other than that it does not seem differently formated, only ordered. The "0" is also just the selected version of Proton that I want to set for the whole system as default.

## Debugging

If you want me to debug this issue further, I would like you to tell me where to go.

Steps to reproduce should also be added to the projects' wiki - afterwards, of course, if we got something useful out of it.

I simply won't send nor post files, due to how non-accessible the systems are between each other.

## Summary

This issue description might seem sarcastically at first glance - and I'm feeling like it, being as frustrated as I am right now -, but it's really an honest attempt to fix this issue on a large scale, once and for all, with what can be done here.

Whatever happens here, is not exactly helping folks to "just" game with ChimeraOS after initial setup.

I personally have no issue with just using my main system to play games - a "normal" Desktop Arch Linux.
But having said that, it would not help my guests in any way, that come over to play with me some games, that cannot be played simply via split screen or - also _not_ an option for this use case - Steam Play Together.

I would like us to get rid of that negative feeling and do something benefitial for everyone.

Cheers :)

**Comment by alkazar** [comment]
We modify `config.vdf` on every boot, applying game tweaks. I wonder if that process is somehow failing occasionally and causing the issue?

You could try disabling that functionality and seeing if the problem occurs. Since it is not immediately reproducible it will be hard to tell though.

You can disable the feature by editing `/usr/bin/steam-tweaks`. Just comment out the line that reads `chimera --update --tweaks`.
Note that you will lose almost all chimera functionality, like Proton GE, shortcuts, and the game tweaks.

**Comment by alkazar** [comment]
Since you have an AMD GPU, you could try the following.

The next time this happens, try running `chimera-session gamepadui` to switch to the new gamepad/deck UI. It would be informative to see if that UI is also affected by this issue or if it is just Big Picture.

**Comment by Zeitwaechter** [comment]
I just wanted to drop by to let you know that I have not forgotten about this.

It's just the daily stuff.. Steam Deck arrived, too much work and the weather's too hot to tinker around.

I will reply in full _soon TM_ - and by that I mean no disrespect, in any way possible.

**Comment by alkazar** [comment]
I wonder if this will continue to be a problem now that we have switched to using the Steam Deck client.

**Comment by Zeitwaechter** [comment]
Hey, thanks for forwarding this information.

I will check it out :+1:

**Comment by Zeitwaechter** [comment]
That's it for testing for today. 

I will take another look tomorrow evening if there can be something done about this typical lightdm issue.. hmn.

**Comment by alkazar** [comment]
> it seems lightdm can't detect the display. Old SteamOS UI did load correctly before chaning, though.

You tried switching to the new gamepad/deck ui? That requires and AMD gpu which it sounds like you may not have?

**Comment by Zeitwaechter** [comment]
Hmm? Sure, it's a Tahiti XT ("It's a magical place"; _AMD Radeon HD 7900_) series based one - actually a [R9 280X](https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_R5/R7/R9_200_series) if `lspci` is correct with that.

So yeah, it's quite old (2012), but most games still run "fine". Good enough for a guest system anyways :+1: 
If anything there are probably codecs and tech missing on the GPU that are expected with the current day AMD/GPU setups.
But at least this was my previous setup until summer last year, with Arch Linux.

If I run `Xorg :0 -configure` and then `X -config /root/xorg.conf.new` it does start a blank screen on TTY0, which does seem to me like it's at least starting correctly.

There is also no xorg config by default though, not under `/etc/X11/xorg.conf.d` nor `/etc/X11/` if this even matters for the ChimeraOS setup, no matter the `chimera-session` mode.

---

- Switching back via `chimera-session bigpictures` does work out of the box, it's displayed correctly.
- But then, like before, after logging in, changing some settings and after rebooting, the big pictures login screen does again only show the mouse and nothing to select as a user again/not logging in.
- This mode also does not setup any xorg config files and the `/var/log/Xorg.0.log` does only look different at the very end.

---

Also, here attached are the stated logs:

- [lpci.grep.log](https://github.com/ChimeraOS/chimeraos/files/9312336/lpci.grep.log)
- [gamescope-stdout.gamepadui.log](https://github.com/ChimeraOS/chimeraos/files/9312338/gamescope-stdout.gamepadui.log)
- [Xorg.0.gamepadui.log](https://github.com/ChimeraOS/chimeraos/files/9312342/Xorg.0.gamepadui.log)
- [Xorg.0.bigpictures.log](https://github.com/ChimeraOS/chimeraos/files/9312344/Xorg.0.bigpictures.log)

I do not think these are in any way helpful, but that's it for today.

**Comment by alkazar** [comment]
I am now pretty certain this is a Steam client issue that happens when your credentials expire.

I noticed that Gamepad UI doesn't appear to be affected and correctly prompts you for your password. It is unlikely that Valve will ever fix this for BPM.

**Comment by Zeitwaechter** [comment]
Allright, thank you very much for having looked into the issue for so long! :+1: 

I have bought a new AMD GPU for my guest system just last week and will at least report back on how it behaves, after I have setup the whole thing.

Not sure if this will be happening this weekend though, might take another week.

You know, end of the year business stuff, and such :S

Cheers until then! :)

**Comment by Zeitwaechter** [comment]
So, finally it is time for my reply:

Well, changing the GPU did help in the end :)
It was just too old :+1:
