### ISSUE TITLE
Switching chimera to dekstop or gamepadui makes an endless loop ofnloading

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#345]
So I installed chimeraOS on my gpd win 2 because the place I work at doesn't allow windows laptops or Linux or anything with a desktop that isn't a Mac or a mobile phone, I thought it would be cool to pretend to have a steam deck on my win 2 and call it "gpd deck 2" but it causes endless loop of loading unless I switched it back to big picture mode

**Comment by pastaq** [comment]
Were you connected to the internet when you attempted to switch? Switching requires downloading a different client version than BPM does.

**Comment by houku** [comment]
Idk how to cancel the closed but I was connected to wifi

**Comment by alkazar** [comment]
It is possible that gamescope doesn't work with the Intel graphics chip in this device.
