### ISSUE TITLE
 Bluetooth service fails to init on boot (gamepad ui) (v33)

### ISSUE THREAD

**Issue by ryandavidmercado** [ChimeraOS/chimeraos#346]
**Current behavior**: After navigating to Settings > Bluetooth in the gamepadui, the top-level Bluetooth toggle is greyed out and disabled, preventing search and pairing of Bluetooth devices. SSH'ing into the system and running journalctl reveals the following relevant information, logged at boot: 

```
Jun 10 14:08:04 chimeraos systemd[1]: Starting Bluetooth service...
Jun 10 14:08:04 chimeraos systemd[550]: bluetooth.service: Failed to set up mount namespacing: /run/systemd/unit-root/var/lib/bluetooth: No such file or directory
Jun 10 14:08:04 chimeraos systemd[550]: bluetooth.service: Failed at step NAMESPACE spawning /usr/lib/bluetooth/bluetoothd: No such file or directory
Jun 10 14:08:04 chimeraos systemd[1]: bluetooth.service: Main process exited, code=exited, status=226/NAMESPACE
Jun 10 14:08:04 chimeraos systemd[1]: bluetooth.service: Failed with result 'exit-code'.
```

This behavior persists upon re-flashing the install media w/ a fresh copy of the ChimeraOS installer and re-installing the operating system to the boot drive.

**Expected behavior**: Navigating to Settings > Bluetooth reveals a working Bluetooth toggle.

**Steps to reproduce**:
1. $ chimera-session gamepadui
2. Navigate to Steam > Settings > Bluetooth; observe the disabled toggle

**Hardware specs**:
Computer: Minisforum HM90
Processor: Ryzen 9 4900H
Graphics: Vega 8
Wireless/BT card: Mediatek MT7921k

**Comment by pastaq** [comment]
Possible workaround:
```
sudo /usr/lib/bluetooth/bluetoothd
ctrl+c
sudo systemctl start bluetooth
reboot
```

**Comment by ryandavidmercado** [comment]
@pastaq I can confirm that the workaround was successful on my machine

**Comment by alkazar** [comment]
How can that work around work if `/usr/lib/bluetooth/bluetoothd` does not exist?

**Comment by pastaq** [comment]
Not sure. Looking into it, it seems like it was a bluez issue affecting users on other OS's.
https://bbs.archlinux.org/viewtopic.php?id=274969
https://forum.endeavouros.com/t/bluetooth-not-starting/25138/3
https://superuser.com/questions/1716226/failed-to-start-bluetooth-service

It was patched for 5.64-2: https://github.com/archlinux/svntogit-packages/commit/ec96253dff1d9892879cd4682840817fff817236

**Comment by 200Puls** [comment]
I have to fight with this from time to time. Havent tried upgrading bluez yet. Might give it a go. 
@alkazar  Any idea when a new release will be published?

**Comment by alkazar** [comment]
New release is out now, but it seems to be a mixed bag for bluetooth. For some bluetooth works, for others, it does not.
