### ISSUE TITLE
ChimeraOS does not start after installation

### ISSUE THREAD

**Issue by JorgeEMX** [ChimeraOS/chimeraos#348]
Hello,

It appears these messages when turning on the PC but does nothing else.
![2022-06-17](https://user-images.githubusercontent.com/6845831/174402099-40bd3ade-5f1a-440c-9423-a076e839b1d3.jpg)

The PC has 2 SSD disks, it has been tried to install on both disks and the result is the same.

Can help us?

**Comment by alkazar** [comment]
What GPU do you have?

**Comment by JorgeEMX** [comment]
> What GPU do you have?

PCI port: ATI Radeon HD 4670
My motherboard has integrated Intel GMA 3100 graphics.

**Comment by alkazar** [comment]
Oh my, that is way too old and not supported.

Supported GPUs are listed on the download page:
Nvidia GTX 900 / AMD RX 400 / Intel HD Graphics 500 series or newer

**Comment by JorgeEMX** [comment]
Oh, my hardware is very old, thanks for the information!
