### ISSUE TITLE
Rumble / Haptics on OneXPlayer

### ISSUE THREAD

**Issue by SteinCK** [ChimeraOS/chimeraos#349]
Anyone have issues with haptics / rumble working via ChimeraOS / SteamOS ?

My Haptics Settings menu is blank in Steam OS Settings./ Controller / Haptics Settings for my OneXplayer with built in controller - AMD mini 5800u 1200p.

**Comment by alkazar** [comment]
I am not sure what menu you mean.

Haptics did not work for me until I turned off steam input.
Does that fix it for you?

**Comment by bashu** [comment]
how to turn off steam input in BPM ?

**Comment by Samsagax** [comment]
This is fixed on v38
