### ISSUE TITLE
Mounting Additional HDD For Steam Library Doesn't Work

### ISSUE THREAD

**Issue by dave-tucker** [ChimeraOS/chimeraos#353]
## Summary
Following the instructions on the FAQ [here](https://github.com/ChimeraOS/chimeraos/wiki/FAQ#i-have-more-than-one-hard-drive-or-solid-state-disk-how-can-i-use-that-for-steam-games) does not result in the disk being mounted.

I read the progress on #237 and had assumed this was supported.

## My Setup

Chimera OS 33
512GB SSD
I have a 2TB disk attached via SATA which is `sda1`
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda           8:0    0   1.8T  0 disk 
└─sda1        8:1    0   1.8T  0 part 
nvme0n1     259:0    0 465.8G  0 disk 
├─nvme0n1p1 259:1    0   511M  0 part /frzr_root/boot
│                                     /boot
└─nvme0n1p2 259:2    0 465.3G  0 part /var
                                      /home
                                      /frzr_root
                                      /
```

### Issue 1
Running `init-meda.sh` fails due to the bug that was fixed here: 
https://github.com/ShadowBlip/steam-removable-media/commit/85fe8a74024c5c585a42eb34656e75fbb3f0320a

Since this was fixed a few days after ChimeraOS 33, I'll assume the fix will ship in the next update.

### Issue 2

I can work around the first issue by manually adding the UUID to `/etc/removable-libraries` and run `systemctl start media-mount@sda1` then the volume is correctly mounted.

However, the mount does not persist on reboot.

The issue is likely to because the udev rules only allow for USB devices, which given the package is called **steam-removable-media** makes sense.

To make this work for a non-usb disk I added another udev rule like this:

```
[gamer@chimeraos ~]$ sudo cat /etc/udev/rules.d/99-media-mount-phys.rules 
# Originally from https://serverfault.com/a/767079
# Modified from SteamOS 3 99-sdcard-mount.rules
# Run a mount script through systemd for permanent devices

KERNEL=="sd[a-z][0-9]", ENV{ID_FS_UUID}=="2fd83daa-d8ea-4c29-a535-8222abf91ff5", ACTION=="add", RUN+="/bin/systemctl start media-mount@%k.service"
KERNEL=="sd[a-z][0-9]", ENV{ID_FS_UUID}=="2fd83daa-d8ea-4c29-a535-8222abf91ff5", ACTION=="remove", RUN+="/bin/systemctl stop media-mount@%k.service"
```

I'm not sure if this should be added as a feature to the package upstream when calling `init-media.sh`,

**Comment by pastaq** [comment]
I think that was just an oversight. I'll work on a fix for this, thanks.

**Comment by pastaq** [comment]
Should work now with https://github.com/ShadowBlip/steam-removable-media/commit/cc621d031e11cab704554bdaa987b95e620eb137

Can you remove your new udev rule and upgrade the package to verify?

```
sudo frzr-unlock
sudo pacman -Sy yay
yay -Sy steam-removable-media
```

**Comment by dave-tucker** [comment]
Sure I'll give that a try later today... but I'm not hopeful.
I did originally remove the `SUBSYSTEM=usb` from the udev rules and ended up booting to an emergency terminal.
I assume it's because the udev rule would also then match against `nvme0n1p1` and `nvme0n1p2` :sweat:

**Comment by dave-tucker** [comment]
> Sure I'll give that a try later today... but I'm not hopeful.

I stand corrected! It works :tada: 

```
sudo frzr-unlock
sudo pacman -Sy yay
yay -Sy fakeroot
yay -Sy steam-removable-media-git
```

**Comment by pastaq** [comment]
> Sure I'll give that a try later today... but I'm not hopeful. I did originally remove the `SUBSYSTEM=usb` from the udev rules and ended up getting dumped into an emergency terminal. I assume it's because the udev rule would also then match against `nvme0n1p1` and `nvme0n1p2` 😓

That's because the --no-block wasn't in the previous udev rule, which we found caused the emergency terminal issue if installed on a USB HDD. 

Glad it worked out and I appreciate the feedback.

**Comment by Sturmlocke86** [comment]
> > Sure I'll give that a try later today... but I'm not hopeful.
> 
> I stand corrected! It works tada
> 
> ```
> sudo frzr-unlock
> sudo pacman -Sy yay
> yay -Sy fakeroot
> yay -Sy steam-removable-media-git
> ```
> 
> Thanks for fixing this so quickly

Was facing the same issue and this worked like a charm. Thanks for sharing!
