### ISSUE TITLE
Audio distorted and loud

### ISSUE THREAD

**Issue by oystermon** [ChimeraOS/chimeraos#357]
Hi I recently installed chimera OS on my mini PC and got really bad distorted and loud audio.

I realised there were a couple of people having the same issue on discord and also found this thread on reddit with the solution:
https://libreddit.nl/r/ChimeraOS/comments/uxqk2c/hdmi_audio_issue/

It didn't really fully list the steps on how to solve it, so i thought I write it here:

1. Log in to steam big picture, then enter the terminal by pressing Ctrl+Alt+F2
2. Enter the username/pass (gamer/gamer)
3. Type `sudo frzr-unlock`
4. Install pavucontrol by typing `pacman -S pavucontrol`
5. Type `pacmd` (you can use help to get a list of commands)
6. Type `dump-volumes` to check the volume levels - in my case my sink 0 and sink 1 were at 10000%
7. Type `set-sink-volume 0 0x10000` and `set-sink-volume 1 0x10000` to set both sinks to 100%
8. Type `dump-volumes` again to verify
9. Reboot by typing `reboot`
10. After the reboot I found that I needed to launch a game to check that it works correctly

As mentioned in the reddit post if you change the inputs you need to re-do the steps again, and I read that if chimera OS updates all these settings will be lost.

Thanks.

**Comment by MiningMarsh** [comment]
Ass another workaround, I found that setting the input to Surround 5.1 or 7.1 fixes the issue and doesn't seem to have any adverse effect on my stereo setup, it just gets downmixed back to stereo.

**Comment by oystermon** [comment]
I tried that (I assume you set it in Steam Big Picture?) and unfortunately it didn't work for me (I tested it by switching between TV and internal PC speakers then back to TV.. and setting 5.1)

Maybe it's because I have pauvcontrol installed?

**Comment by SSchott** [comment]
Just did what you wrote, and fixed it for me :+1:

**Comment by MiningMarsh** [comment]
I needed to fix this earlier and today and wanted to mention that you don't need to unlock chimera and install pavucontrol, amixer is preinstalled.

You can accomplish the same setting update with `amixer set Master 100%` after sshing in.

**Comment by alkazar** [comment]
Another alternative is to use `pulsemixer`, which is also included by default.

Anyone have ideas on how to enforce this automatically? We could clamp the volume level on session startup but this wouldn't cover the case when you change the audio output through the Steam UI.

**Comment by SSchott** [comment]
I have no clue about how the distro is being built, but couldn't one add a post installation hook command to make sure the volume is 100% in the manifest?

**Comment by MiningMarsh** [comment]
> Another alternative is to use `pulsemixer`, which is also included by default.
> 
> Anyone have ideas on how to enforce this automatically? We could clamp the volume level on session startup but this wouldn't cover the case when you change the audio output through the Steam UI.



> Another alternative is to use `pulsemixer`, which is also included by default.
> 
> Anyone have ideas on how to enforce this automatically? We could clamp the volume level on session startup but this wouldn't cover the case when you change the audio output through the Steam UI.

Looking at the pulseaudio modules, they have the following one listed:
```
module-match

Adjust the volume of a playback stream automatically based on its name.

table
    The regular expression matching table file to use (defaults to ~/.pulse/match.table) 

The table file should contain a regexp and volume on each line, separated by spaces. An example:

^sample: 32000

The volumes of all streams with titles starting with sample: are automatically set to 32000. (FYI: All sample cache streams start with sample:)
```

It seems like this could be implemented as a universal match along the lines of `^.*: 100` or similar in a pre-bundled match table.

**Comment by benklop** [comment]
is this the steam client adjusting the volume to rediculous gain levels? it certainly is annoying.. lately i've had to change this at every boot.

**Comment by mdeguzis** [comment]
Same here:

![PXL_20230123_205313353.jpg](https://user-images.githubusercontent.com/3931917/214147716-a1edbfca-96c4-4f3d-a2e2-1c9c6c339c3a.jpg)

**Comment by InvisibleFunction** [comment]
I am experiencing this issue as well. I found this other other issue not related to chimeraOS at all where using steam big picture mode to configure audio outputs also ended up setting the volume to 10000%

https://old.reddit.com/r/SteamDeck/comments/x98u1o/sound_issues_with_upgraded_jsaux_dock_on_2014/

Perhaps this implies that it's a bug in Steam? I'm not really sure how all the pieces of this go together.
