### ISSUE TITLE
Gamepad UI mode keeps wanting updates

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#360]
So I installed chimera os on my Aya neo, and went to check about updates because I thought maybe it needs manual updates,

I checked for updates and I got "steam deck os stable update nothing to see here"

So I updated and checked again,

Same result

If you can clarify how the updates work in gamepad mode that would be nice

**Comment by pastaq** [comment]
This is a bug that will be resolved in the next *actual* update to v34, which should come out soon. For now you can ignore the update warnings.

**Comment by houku** [comment]
Just to clarify, will the update happen automatically or will I need to tell it to update in gamepad UI?

**Comment by pastaq** [comment]
It will happen automatically when a release is available and require a reboot once completed.

**Comment by alkazar** [comment]
Fixed in latest release.
