### ISSUE TITLE
WiFI performance degraded compared to other distros

### ISSUE THREAD

**Issue by pastaq** [ChimeraOS/chimeraos#370]
WiFi performance has been noted to be particularly slow on some MediaTek and Realtek WiFi modules when compared to the same hardware on other distros (PopOS and HoloISO namely). We need to investigate the cause and attempt to find a solution.

Incomplete list of possibly affected hardware:
Latest Asus Zephyrus Laptop
Aya Neo handhelds with RZ608/MT7921K
OXP Handhelds with RZ608/MT7921K

**Comment by pastaq** [comment]
Possible causes:

Some recommendations are to disable MAC address randomization:
https://wiki.archlinux.org/title/NetworkManager#Configuring_MAC_address_randomization

archwiki article 
https://wiki.archlinux.org/title/Frequently_asked_questions#Why_is_my_internet_so_slow_compared_to_other_operating_systems?

**Comment by Samsagax** [comment]
Could you please test the current unstable image? It contains disabled MAC randomization.

**Comment by pastaq** [comment]
Currently download on my aya neo at 45MB/s. chimeraos-35_01a35f3

**Comment by Samsagax** [comment]
Will close it as solved for now. If stutters come around again, please reopen.
