### ISSUE TITLE
Steam UI crashes when testing microphone while using bluetooth

### ISSUE THREAD

**Issue by mstavridis** [ChimeraOS/chimeraos#375]
Steam UI crashes when I click the test microphone while using bluetooth under voice. So far I have only tested it with a bluetooth headset connected. I did notice it crashed when I was in that settings menu with the headset not connected. Later today I will do more testing and list out the infromation.

I am not even sure if this issue is related to ChimeraOS or Arch Linux. Is there specific log file I can pull or take a look at for this?

**Comment by Samsagax** [comment]
Closing as it had no answer.
