### ISSUE TITLE
Stuck boot on fresh install of ChimeraOS

### ISSUE THREAD

**Issue by sjdrc** [ChimeraOS/chimeraos#379]
After a fresh install of ChimeraOS, screen gets stuck at `[drm] VT-d active for gfx access`. I am unable to switch TTYs or do anything other than rebooting with the power button.

![ChimeraOS boot screen](https://user-images.githubusercontent.com/6028151/184505011-993a1d09-8dd6-404b-b4d6-3cf3981790b4.jpeg)

I would usually manage to resolve issues like this by adding `nomodeset` to the boot flags. However I have been unsuccessful in either getting an edit menu when booting, or locating the file to edit from the arch installer ISO.

System details:
- Intel i9-12900
- Nvidia RTX A5000

What version of the Nvidia drivers are installed? Perhaps they are not new enough for my GPU?

**Comment by sjdrc** [comment]
Don't know why I couldn't see it before but the boot config file is at `/boot/EFI/BOOT/syslinux.cfg`. I added `nomodeset` to the `append` line and now I am no longer stuck at the point shown in the OP.

I am now able to switch ttys, but the boot messages on tty6 never clears and after running `chimera-session` it just takes me back to the incomplete boot process.

**Comment by Samsagax** [comment]
I think you are in an (still unsupported) hybrid graphics configuration. Those unfortunately are hit n miss. Since you are able to enter a TTY, could you report on what does Xorg.0.log reports?

**Comment by sjdrc** [comment]
Looked earlier in `dmesg` and saw that the Nvidia driver hadn't loaded correctly.

Fixed the issue by adding `ibt=off` to the boot flags - see https://github.com/NVIDIA/open-gpu-kernel-modules/issues/256#issuecomment-1138851460.

**Comment by hashnag** [comment]
Just to chime in: I had the exact same issue. Adding ibt=off workes great. Thanks!

**Comment by InvisibleFunction** [comment]
Still the case on a new install with a 2070.

I also did a “steam os upgrade” whatever that is and I had to apply this fix again.

**Comment by alkazar** [comment]
Note: `ibt=off` is now included in the kernel parameters written by frzr 0.11.2

**Comment by Samsagax** [comment]
Should be fixed in upcoming release
