### ISSUE TITLE
home button on aya neo sometimes stops working and idk how to fix it

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#386]
so, idk how, it just happens randomly,  but sometimes the home button stops working when im in gamepadUI, and when i go to big picture, it still doesnt work, i tried restarting and no luck,

idk how to even replicate it because i just dont touch it and it happens sometimes

**Comment by pastaq** [comment]
Can you provide a few more details?

1.) ChimeraOS version
2.) Aya Neo model
3.) output of `journalctl -u handycon` after this happens?
See https://github.com/ChimeraOS/chimeraos/wiki/Troubleshooting#-how-can-i-access-a-shell for how to get the journal output
4.) What sort of things you're typically trying to do when it crashes. In game, attempting to use the webui for chimera, after waking from sleep, etc.

I recently made a pretty big rewrite that will be introduced in v35 that solves a lot of these crashes of the controller. I'll need to see the log to know if those fixes will solve it for you in the next  update or if I need to make additional changes.

**Comment by pastaq** [comment]
> so, idk how, it just happens randomly, but sometimes the home button stops working when im in gamepadUI, and when i go to big picture, it still doesnt work, i tried restarting and no luck,
> 
> idk how to even replicate it because i just dont touch it and it happens sometimes

I'll need more info to solve this. Is it still an issue for you?

**Comment by aarron-lee** [comment]
I can confirm that I have the same issue on my Aya Neo Air Pro, ChimeraOS 37.

My home button stops working, and instead starts acting like a mouse cursor that is always moving upwards towards the top of the screen.

In contrast, the quick settings menu button does not suffer from this issue, it's been very reliable.

For now I've manually worked around this issue by manually adding a `LEFTCTRL + 1` handygccs combination, and mapping it to the `LC` button on the Aya Neo Air Pro. `CTRL + 1` can open the home menu while quick settings are open, so I've been pressing `quick settings button > LC button` for to access the home menu.

**Comment by pastaq** [comment]
I'll attempt to replicate this on my AIR. Do you have any indication of how long this takes to manifest or what the conditions are that this tends to happen in?
