### ISSUE TITLE
Xbox series x/s controller vibration not working in games, any fix?

### ISSUE THREAD

**Issue by bashu** [ChimeraOS/chimeraos#390]
Connected via dongle (xow/xone), cuz bluetooth is not working in Chimera OS

**Comment by alkazar** [comment]
Try turning off Steam Input. It can interfere with rumble.

You can do this globally in the settings or per game under "Manage Game" -> "Controller Options".

**Comment by bashu** [comment]
to @alkazar can you confirm that rumble (xone controllers) is working at all? Can you please name few games where it's working out-of-the box ? 

For example "Little Nightmare" listed as verified, but no vibro on my XOne controller

**Comment by bashu** [comment]
to @alkazar I've just tried native Tomb Raider with both on and off steam input, but still no vibration

**Comment by bashu** [comment]
managed to get vibration working via bluetooth, but it's always works at 100% of its power, making it even worse

**Comment by glothriel** [comment]
@bashu How did you connect controllers via dongle? The dongle does not work for me at all, no flashing light, etc, just some messages in `dmesg`, that do not seem to reflect the reality.

**Comment by bashu** [comment]
I don't remember, try to insert dongle after OS booted, click the button on a dongle, then double click on X logo button on controller. Try to insert dongle, before booting the OS.

I don't have ChimeraOS installed, but I will try chimera again when Deck/GamePad UI will be ready and stable

**Comment by glothriel** [comment]
Thanks for help guys. It turned out to be a problem with extension cord. It for some reason worked on windows, but on linux I had to plug the dongle directly into USB port. So currently everything works!

**Comment by alkazar** [comment]
This seems to have been fixed in a recent Steam client release. Closing.
