### ISSUE TITLE
Steam BPM can not find any of my bluetooth devices

### ISSUE THREAD

**Issue by bashu** [ChimeraOS/chimeraos#391]
subj, another question how can I check if bluetooth is working at all?

**Comment by alkazar** [comment]
This is a known issue. Steam is turning bluetooth off by default and there is no option in BPM to turn it on. There will be a workaround in the next release.

**Comment by bashu** [comment]
to @alkazar so you saying Chimera OS + Steam works with wired controllers only ?

**Comment by alkazar** [comment]
This started happening after we switched to using the Steam Deck client in ChimeraOS 34. We did this to fix other issues with games not starting and to pick up game fixes that were aimed at the Steam Deck.

You can work around the bluetooth issue by switching to gamepad UI (`chimera-session gamepadui`) and enabling bluetooth in the settings, but gamepad UI only works if you have an AMD GPU.

Alternatively,  you can edit `~/.local/share/Steam/config/config.vdf` by adding the System section shown below under the top-level "InstallConfigStore" section of the file:

```
        "System"
        {
                "Bluetooth"
                {
                        "enabled"               "1"
                }
        }
```

**Comment by bashu** [comment]
is it possible to force install ChimeraOS 33?

**Comment by Samsagax** [comment]
> is it possible to force install ChimeraOS 33?

It can not but even then it won't work because the client is updated independently of the system itself. And Valve doesn't care about BPM for a while now in favor of the newer GamepadUI. The problem is they didn't break it until now. We are working around issues but eventually all would converge to GamepadUI.

**Comment by bashu** [comment]
managed to get vibration working via bluetooth, but it's always works at 100% of it power, making it even worse

**Comment by bashu** [comment]
I want to thank everyone for their hard work, I am going to watch for updates and will try it again in year or two when Gamepad UI will be usable.

**Comment by bashu** [comment]
to @alkazar, I can confirm that this one not an issue in latest Chimera OS (atleast v36)
