### ISSUE TITLE
is there planned nintendo ds / 3ds / wiiu support

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#410]
so i like chimera for the idea of console, despite some issues i had (home button stops working suddenly sometimes)

but there are a lot of nintendo ds and 3ds games i wanna replay and chimera doesnt have that option rn, so i was wandering if it is planned or not

**Comment by alkazar** [comment]
This is not currently planned. DS and 3DS are complex to configure in a good way for out of the box play. Many games require a mouse for example. The dual screens are also an issue. Wii U has similar issues plus has the added complexity of not being available in RetroArch. These platforms are left for users to add on their own for now.

I am open to suggestions though.

**Comment by Samsagax** [comment]
Closing as not planned.
