### ISSUE TITLE
Unable to run the game installed through EPIC Store

### ISSUE THREAD

**Issue by milescui** [ChimeraOS/chimeraos#416]
Unable to run the game installed through EPIC Store.

There are the same problem in GamepadUI or Desktop Mode.

Test game: Fall Guys
System version: ChimeraOS 35

**Comment by MrCraigen** [comment]
Have you tried other games?  Because Fall Guys has Easy Anti cheat which has not turned on support for Linux

**Comment by milescui** [comment]
> 
Thank you for your recovery, I tried the game without Anti cheat.

**Comment by alkazar** [comment]
Please try one of the Verified Epic games found here: https://chimeraos.org/games
