### ISSUE TITLE
Gamescope crashes constantly

### ISSUE THREAD

**Issue by BoukeHaarsma23** [ChimeraOS/chimeraos#418]
Using Ryzen 3200G, my chimeraOS install keeps crashing during gameplay. It just restarts to gamepadUI.

coredump:
https://pastebin.com/KAgFTy9t
Gamescope std-out:
https://pastebin.com/zb1wFLn9

Seems to be related to a DRM error. The assert fails in Gamescope.

**Comment by Samsagax** [comment]
Is this reproducible on latest build? Closing for now, but feel free to open it with new logs if applicable.
