### ISSUE TITLE
no sound on steam deck

### ISSUE THREAD

**Issue by fuckshitrosoft** [ChimeraOS/chimeraos#421]
it just says auto_null in the settings for audio

**Comment by mindtheegab** [comment]
probably because we are not running the neptune kernel and the audio fix is not upstreamed afaik adding it its not trivial though since chimeraos is readonly

**Comment by fuckshitrosoft** [comment]
well i wanted to use the music player in big picture mode cant use that if there is no sound

**Comment by mindtheegab** [comment]
Yes it's not ideal ,I tried earlier to install the steamdeck kernel but I got an error will add details later(a dependency with liquidctl anyway)

**Comment by mindtheegab** [comment]
[gamer@chimeraos ~]$ sudo pacman -S jupiter/linux-neptune jupiter/linux-neptune-headers jupiter/linux-firmware-neptune jupiter/jupiter-hw-support rumpowered/sc-controller
[sudo] password for gamer: 
Sorry, try again.
[sudo] password for gamer: 
error: could not register 'multilib' database (database already registered)
resolving dependencies...
looking for conflicting packages...
:: linux-firmware-neptune and linux-firmware are in conflict. Remove linux-firmware? [y/N] y
:: python-hid and python-hidapi are in conflict. Remove python-hidapi? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing python-hidapi breaks dependency 'python-hidapi' required by liquidctl

**Comment by mindtheegab** [comment]
tried to update before trying again but that breaks the OS. ([FAILED]Failed to mount ]boot)

**Comment by fuckshitrosoft** [comment]
sad

**Comment by fuckshitrosoft** [comment]
until this can be fixed i have to boot into big picture on steam os manually instead of automatically

**Comment by alkazar** [comment]
The latest unstable ChimeraOS build has the 6.0 kernel which should have support for audio on the Steam Deck so switching to the neptune kernel shouldn't be necessary. I suspect there is only some configuration or firmware required, but don't yet know what is needed to enable audio on the Steam Deck.

**Comment by fuckshitrosoft** [comment]
thats cool i will test the unstable chimeraos build

**Comment by fuckshitrosoft** [comment]
i switched to unstable on the steamdeck and the sound doesnt work but it seems to recoginize the microphone for some reason

**Comment by fuckshitrosoft** [comment]
i went into the dekstop mode and there was  a dummy output for sound and some microphone in the sound settings

**Comment by fuckshitrosoft** [comment]
and i just  learned the sound works on unstable if i plug in jack headphones but not with the steamdeck speakers

**Comment by stvweb02** [comment]
So, when I had this issue with HoloISO, I just had to copy the firmware folder from the Steam Deck recovery image to the firmware folder. Is there any way to do something like that with ChimeraOS?

**Comment by fuckshitrosoft** [comment]
> So, when I had this issue with HoloISO, I just had to copy the firmware folder from the Steam Deck recovery image to the firmware folder. Is there any way to do something like that with ChimeraOS?

thats usefull to know now i could just install arch linux and setup arch linux the way i wanted it and copy the firmware  that doesnt fix the chimeraos bug but its a solution to the problem i had

**Comment by Samsagax** [comment]
> So, when I had this issue with HoloISO, I just had to copy the firmware folder from the Steam Deck recovery image to the firmware folder. Is there any way to do something like that with ChimeraOS?

Which files did you copy over?

**Comment by DarkenLX** [comment]
> > So, when I had this issue with HoloISO, I just had to copy the firmware folder from the Steam Deck recovery image to the firmware folder. Is there any way to do something like that with ChimeraOS?
> 
> Which files did you copy over?

Whatever they are the files would likely be in (if you mount the recovery image on Ubuntu with disk image mounter. So adjust the path accordingly) rootfs/usr/lib/firmware

**Comment by alkazar** [comment]
This issue has been resolved in a previous release.
