### ISSUE TITLE
Aya Neo Air Pro Controller not recognized by game - Final Fantasy VII Remake

### ISSUE THREAD

**Issue by aarron-lee** [ChimeraOS/chimeraos#422]
## Device:
Aya Neo Air Pro (5825u)
## Game:
~~Triangle Strategy~~ Seems to be fixed as of ChimeraOS 38
Final Fantasy VII Remake
## OS:
~~Chimera OS 35~~
ChimeraOS 38
## Bug Description:
~~Triangle Strategy refuses to recognize both the built-in controller and external controllers. It only recognizes the built-in controller if I set the controller layout to keyboard + mouse joystick.~~

~~When I tried to replicate this issue on my ChimeraOS HTPC in the living room, it had no issues recognizing an external controller. Same for my Steam Deck with SteamOS.~~

~~My naive guess here is that the game detects a keyboard of some sort, and assigns it to player one. gamepadui does have a reorder controller option, but it's only for controllers, not keyboards.~~

Triangle strategy now recognizes built in controller on Aya Neo Air pro, still not recognized for Final Fantasy VII Remake

**Comment by pastaq** [comment]
This may depend on how the game detects/handles input. Do you have this issue if you plug in a keyboard to your HTPC?

**Comment by aarron-lee** [comment]
> This may depend on how the game detects/handles input. Do you have this issue if you plug in a keyboard to your HTPC?

@pastaq Just tested on the HTPC with ChimeraOS 35, no issues. It freely swapped between keyboard and controller.

Seems that this is a problem specific to the Aya Neo Air Pro with ChimeraOS 35. I also tried disabling Steam Input on the Aya Neo Air Pro for the game, which made no difference.

**Comment by pastaq** [comment]
It may be a conflict with HandyGCCS. What happens if you stop handycon.service?

**Comment by aarron-lee** [comment]
> It may be a conflict with HandyGCCS. What happens if you stop handycon.service?

I was playing around with the handygccs.conf, and accidentally saved a typo that seems to have broke the service on reboot. Checking the handycon.service's status via systemctl indicated that it had failed.

I decided to test Triangle strategy while in this state, no dice; the game still fails to recognize the controller.

Also, I have discovered another game with the same issue, Final Fantasy VII Remake Intergrade

**Comment by aarron-lee** [comment]
Just wanted to report that the controller is now recognized for Triangle Strategy, but not FFVII Remake. Unsure of what fixed the issue for Triangle Strategy, this is on ChimeraOS 38

**Comment by Samsagax** [comment]
Seems to be game-specific. maybe the client or proton update fixed it?

**Comment by Samsagax** [comment]
Can you test latest unstable or testing images?

**Comment by aarron-lee** [comment]
updated + tested on 39, seems to be working fine now
