### ISSUE TITLE
Occasional multiple detected controllers when no external controllers attached

### ISSUE THREAD

**Issue by aarron-lee** [ChimeraOS/chimeraos#423]
## Device:
Aya Neo Air Pro (5825u)
## OS
Chimera OS 35
## Bug Description:
After multiple suspend-resume cycles, gamepadui sometimes detects multiple instances of the built-in controller. This is not consistent, it only sporadically happens.

These leads to doubling of inputs in certain menus, such as in the Crankshaft TDP menu, etc.

## Workaround / temp fix
System reboot or restart steam client

**Comment by aarron-lee** [comment]
Photos:

![20221019_062449](https://user-images.githubusercontent.com/9145965/196667257-616d2c8b-4d60-468f-b62c-2051dfcefad1.jpg)
![20221019_062523](https://user-images.githubusercontent.com/9145965/196667250-f832057b-4bd4-4081-8621-dec13034504a.jpg)

**Comment by pastaq** [comment]
Does this issue still occur if you disable steam input for the controller?

**Comment by aarron-lee** [comment]
> Does this issue still occur if you disable steam input for the controller?

I'll try this next time I encounter the issue. This issue hasn't really been much of an issue for me, since the games I play are single player and ignore the 2nd controller.
