### ISSUE TITLE
some app won't invoke OSK in desktop mode

### ISSUE THREAD

**Issue by EricFL1998** [ChimeraOS/chimeraos#429]
heroic game launcher, edge, etc won't open OSK, also the OSK on ayaneo air is too small and hard to press, can you not just implement the gamepadui OSK to desktop mode like steamos does. or atleast add a controller shortcut to manually open OSK

**Comment by EricFL1998** [comment]
turns out steam is not run on default when in desktop mode

**Comment by peterge1998** [comment]
> turns out steam is not run on default when in desktop mode

Ye, i am facing the same problem when trying to use my steam controller in desktop mode. On holoiso/steamdeck it does work because steam is started sutomaticallx. How did you solve this? I think about creating a new issue...

**Comment by Samsagax** [comment]
We don't start steam automatically but is something you can do on your own and will survive across updates. Be aware that Gnome has its own OSK and will pop up automatically when no keyboard is present. You can add a shortcut with your controller to pop it up in the settings.

**Comment by peterge1998** [comment]
Whats the best way to add it autostart ? On desktop (fedora) I am using Startup Applications from Tweaks.

**Comment by Samsagax** [comment]
You need to add a desktop file to auto start under your users `.config` directory.
For reference: https://wiki.archlinux.org/title/XDG_Autostart

**Comment by peterge1998** [comment]
`cd /etc/xdg/autostart/ && sudo ln -s /usr/share/applications/steam.desktop .`
