### ISSUE TITLE
dekstop and gamepad made flickering when accessing

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#439]
so i recently installed chimera on an asus vivobook x515ma and aya neo 2021, and the installer was good and all,

when i went to access the gamepadui, the screen was flikering on the laptop, and when i changed to desktop, the screen was flikering still, but changing the display resolution seemed to fix it, and theres no flikering in my aya neo in gamepad

**Comment by Samsagax** [comment]
Seems to be a problem with modesetting in that particular laptop and graphics stack version. Could you test if the same happens in current testing image?
Here is how to switch between channels: https://github.com/ChimeraOS/chimeraos/wiki/Development#contributing--testing
