### ISSUE TITLE
external storage doesnt work

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#440]
so i recently installed chimera on an asus vivobook x515ma and aya neo 2021, and the installer was good and all,

however, theres a bug is external storage, i connected an external hard drive and its found in gnome disks, but not in gnome files, so i cant transfer my roms and such if i want to use retrodeck, (i know i can use the chimera web app, but its an example), installing a different file manager on laptop didnt seem to find the external storage, my aya neo on gamepadui doesnt seem to find external storage either, and phones arent found in gnome files either, and neither in disks

**Comment by Samsagax** [comment]
Should be fixed on testing image. You can switch to it [as described here](https://github.com/ChimeraOS/chimeraos/wiki/Development#contributing) or just wait for it to be released Soon(tm)
