### ISSUE TITLE
gamepadui/steam issues

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#441]
there seem to be some issues in launching some games and exiting them, i tried to play rising hell epic games edition and protondb says its platnium and it wont launch, and closing doesnt work, launching steam games work but exiting them is also not working well and gave a very long load of exit, 
in big picture mode, rising hell epic games wont launch and goes to games menu, 

and launching half life opposite force launched perfect and closed perfect

another bug in big picture and gamepad on aya neo, is that the mouse keeps jumping around, sometimes its at the botton and while moving it can jump to a different location

**Comment by alkazar** [comment]
Protondb is relevant only for the Steam version of a game. There is no guarantee that the the Epic version will work.
