### ISSUE TITLE
New Install, Black Screen on First Boot

### ISSUE THREAD

**Issue by dbooher2011** [ChimeraOS/chimeraos#444]
I'm trying to install ChimeraOS but after going through the whole process, I just get a black screen and it doesn't get to the window to sign into steam. Top left corner has the white underline. It does have the normal linux boot but nothing else after that. I'm trying to install it on a ASRock Nuc Box-1165g7. From my understanding, it does not have dual graphics. I do have a 2.5 inch hdd installed but that is the secondary device and not what I'm installing ChimeraOS on. None of the keyboard combos work to get into a command line interface.

**Comment by Samsagax** [comment]
Can you test latest image? Currently v38 is in testing, so you can switch to it [as described here](https://github.com/ChimeraOS/chimeraos/wiki/Development#contributing). That image has some patches to the intel driver.

**Comment by Samsagax** [comment]
Is this issue still relevant? Could you test current testing or unstable channels? Those have some fixes for intel hardware.
