### ISSUE TITLE
Change Refresh rate

### ISSUE THREAD

**Issue by peterge1998** [ChimeraOS/chimeraos#446]
After installing ChimeraOS and testing it, I found no way to change the refresh rate in Gamepad UI.
I found [this old issue](https://github.com/ChimeraOS/chimeraos/issues/125), which includes a link which explains to change GOODRATES in ~/.config/steamos-compositor-plus. However, this is not working for me.
After changing GOODRATES to "120.0" in ~/.config/steamos-compositor-plus:
I use the Steam Deck UI, and in the Deck's right hardware menu it's still showing the frame rate cap for 15 | 30 | 60 | unlimited.
I used https://github.com/theVakhovskeIsTaken/holoiso/issues/360 before, but I just came to Chimera because it supports auto updates :)

**Comment by alkazar** [comment]
steamos-compositor-plus is for Big Picture Mode. It is not used when using Gamepad UI.

Do you not see a resolution and refresh rate selection in the Gamepad UI/Steam options?

It doesn't look like there is a way to set refresh rate through gamescope options. The -r option mentioned in your link is for nested refresh rate and doesn't look like it will actually set the monitor's refresh rate.

That being said, you should be able to customize how gamescope is launched by setting the `GAMESCOPECMD` variable in any file you create inside `~/.config/environment.d/`.

See `/usr/bin/gamescope-session` for the default gamescope command.

**Comment by peterge1998** [comment]
> See `/usr/bin/gamescope-session` for the default gamescope command.

```
[gamer@chimeraos ~]$ /usr/bin/gamescope --help
...
  -r, --nested-refresh           game refresh rate (frames per second)
...
```
I guess this is what I need to change. One question tho:
I can not edit `/usr/bin/gamescope-session`, even not as root (`sudo -i`).
How can I then edit the variable's content?
Even if I set it up in `~/.config/environment.d/`, it would get overwritten by the if statement in `/usr/bin/gamescope-session` correct?
What is the best way to modify the content in chimeraos?

**Comment by Tolan87** [comment]
@peterge1998 
you need to name the file like this **refresh-rate.conf**.

And that should be the correct content in there.

`GAMESCOPECMD="gamescope -e --generate-drm-mode fixed --xwayland-count 2 \
-O *,eDP-1 --default-touch-mode 4 --hide-cursor-delay 3000 \
--fade-out-duration 200 \--force-orientation left"

STEAM_DISPLAY_REFRESH_LIMITS=60,120
`

**Comment by peterge1998** [comment]
@Tolan87 
That does not work for me. The right hardware menu gives me the option to lock at 60 or 120 fps, but this has no effect on the games at all, they stay at 60. Even when increasing the games frame rate limit (tested with Hell Pie and 120 fps and testufo running in firefox).

**Comment by peterge1998** [comment]
Okay, when I change the resolution via display > resolution to like 2560x1440@120, it displays 120 during the loading screen. If i am in main menu and select to run at 120 fps in the games settings, its still locked at 60 :/

**Comment by ruineka** [comment]
> Okay, when I change the resolution via display > resolution to like 2560x1440@120, it displays 120 during the loading screen. If i am in main menu and select to run at 120 fps in the games settings, its still locked at 60 :/

Adding -r 120 to `/usr/bin/gamescope-session` might work.

**Comment by peterge1998** [comment]
> Okay, when I change the resolution via display > resolution to like 2560x1440@120, it displays 120 during the loading screen. If i am in main menu and select to run at 120 fps in the games settings, its still locked at 60 :/

After changing the display and rebooting it boots like this. Any idea?
![IMG_20221223_222420_781](https://user-images.githubusercontent.com/47355238/209406713-fa822517-d953-484e-bee8-611e125e3314.jpg)

**Comment by peterge1998** [comment]
Okay, running chimera-session bigpicture works. Switching back to gamepadui brings up the same screen...

**Comment by Samsagax** [comment]
Are you using `--generate-mode fixed` in your arguments? That seems like a sync issue.

**Comment by peterge1998** [comment]
> Are you using `--generate-mode fixed` in your arguments? That seems like a sync issue.

Wait what? You mean switching with chimera-session gamepadui --generate-mode fixed? That does not work

**Comment by Samsagax** [comment]
> Wait what? You mean switching with `chimera-session gamepadui --generate-mode` fixed? That does not work

I mean in the gamescope command.

**Comment by peterge1998** [comment]
> Are you using `--generate-mode fixed` in your arguments? That seems like a sync issue.

Basically, all I would like to do now is to reset gamepadui back to default

**Comment by peterge1998** [comment]
This is quite complicated, I described two problems in one issue... First I would like to solve gamepadui

**Comment by Samsagax** [comment]
Remove any configuration files under `~/.config/environment.d` and the default session will be used (assuming you are in gamepadui session)

**Comment by peterge1998** [comment]
Removing everything in ~/.config/environment.d still shows 2 mangohuds: https://github.com/ChimeraOS/chimeraos/issues/446#issuecomment-1364344357

**Comment by Samsagax** [comment]
> Adding -r 120 to `/usr/bin/gamescope-session` might work.

How did you do this then?

**Comment by ruineka** [comment]
> This is quite complicated, I described two problems in one issue... First I would like to solve gamepadui

Indeed, what is concerning is your issue is resembling another issue I'm seeing on other devices as well after recent steam client updates. We have been trying to identify what exactly is causing it because we've been getting reports (I've seen first hand myself) about gamepad UI locking up on reboots etc. Sometimes with black screens other times at the "verifying installation" screen.

It's possible the refresh rate change caused it in your case, simply removing the `-r 120` added to `/usr/bin/gamescope-session` could be done to confirm this if it works after.

**Comment by peterge1998** [comment]
> How did you do this then?

Wait I did not do this at all because I was facing the other problem

**Comment by peterge1998** [comment]
> Indeed, what is concerning is your issue is resembling another issue I'm seeing on other devices as well after recent steam client updates. We have been trying to identify what exactly is causing it because we've been getting reports (I've seen first hand myself) about gamepad UI locking up on reboots etc. Sometimes with black screens other times at the "verifying installation" screen.
> 
> It's possible the refresh rate change caused it in your case, simply removing the `-r 120` added to `/usr/bin/gamescope-session` could be done to confirm this if it works after.

I did not add anything to `/usr/bin/gamescope-session`, just in ~/.config/environment.d, which I removed...

**Comment by ruineka** [comment]
> > Indeed, what is concerning is your issue is resembling another issue I'm seeing on other devices as well after recent steam client updates. We have been trying to identify what exactly is causing it because we've been getting reports (I've seen first hand myself) about gamepad UI locking up on reboots etc. Sometimes with black screens other times at the "verifying installation" screen.
> > 
> > It's possible the refresh rate change caused it in your case, simply removing the `-r 120` added to `/usr/bin/gamescope-session` could be done to confirm this if it works after.
> 
> I did not add anything to `/usr/bin/gamescope-session`, just in ~/.config/environment.d, which I removed...

Oh okay...darn so the steam client bug is haunting us yet again...

**Comment by peterge1998** [comment]
> Oh okay...darn so the steam client bug is haunting us yet again...

if I can do anything, let me know :)

**Comment by ruineka** [comment]
> > Oh okay...darn so the steam client bug is haunting us yet again...
> 
> if I can test anything, let me know :)

Sure thing thanks. For now if you could manage to get us the `.gamescope-stdout.log` and `.steam-stdout.log` located in your /home/gamer directory that might help.

You might have to get to the desktop to grab these files. `steamos-session-select plasma` should get you to the desktop.

**Comment by peterge1998** [comment]
Wait, plasma from the command is linked to a gnome session because its plasma in steamos 3.0? Funny :D

```
[gamer@chimeraos environment.d]$ chimera-session gamepadui
Switching to gamepadui
Removed "/home/gamer/.config/systemd/user/default.target.wants/sxhkd.service".
[gamer@chimeraos environment.d]$ date
Fri Dec 23 11:56:47 PM CET 2022

[gamer@chimeraos ~]$ cat .gamescope-stdout.log
wlserver: [backend/headless/backend.c:82] Creating headless backend
wlserver: [libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
wlserver: [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
wlserver: [libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
wlserver: [backend/session/session.c:110] Successfully loaded libseat session
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 6600 (RADV NAVI23)': queue family 1
vulkan: physical device supports DRM format modifiers
drm: opening DRM node '/dev/dri/card0'
drm: Immediate flips are not supported by the KMS driver
drm: found new connector 'HDMI-A-1'
drm: found new connector 'DP-3'
drm: found new connector 'DP-2'
drm: found new connector 'DP-1'
drm: Connectors:
drm:   HDMI-A-1 (connected)
drm:   DP-3 (disconnected)
drm:   DP-2 (disconnected)
drm:   DP-1 (disconnected)
drm: selecting connector HDMI-A-1
drm: selecting mode 2560x1440@120Hz
vulkan: supported DRM formats for sampling usage:
vulkan:   0x34325241
vulkan:   0x34325258
vulkan:   0x3231564E
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:18] Starting headless backend
wlserver: [backend/libinput/backend.c:87] Starting libinput backend
wlserver: [backend/libinput/events.c:95] Added Power Button [0:1]
wlserver: [backend/libinput/events.c:95] Added Power Button [0:1]
wlserver: [backend/libinput/events.c:95] Added STMicroelectronics obins anne keyboard  [1155:22288]
wlserver: [backend/libinput/events.c:95] Added STMicroelectronics obins anne keyboard  [1155:22288]
wlserver: [backend/libinput/events.c:95] Added Logitech Gaming Mouse G502 [1133:49970]
wlserver: [backend/libinput/events.c:95] Added Logitech Gaming Mouse G502 Keyboard [1133:49970]
wlserver: [backend/libinput/events.c:95] Added Valve Software Steam Controller Keyboard [10462:4418]
wlserver: [backend/libinput/events.c:95] Added Valve Software Steam Controller Mouse [10462:4418]
wlserver: [backend/libinput/events.c:95] Added Eee PC WMI hotkeys [0:0]
wlserver: [backend/libinput/backend.c:133] libinput successfully initialized
wlserver: [xwayland/server.c:92] Starting Xwayland on :0
wlserver: [xwayland/server.c:92] Starting Xwayland on :1
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55abb4e93d20 (res 0x55abb4ae32e0)
wlserver: [xwayland/server.c:250] Xserver is ready
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55abb49c09c0 (res 0x55abb50a1d70)
wlserver: [xwayland/server.c:250] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 47
wlserver: Updating mode for xwayland server #0: 2560x1440@120
pipewire: renegotiating stream params (size: 2560x1440)
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55abb4ef2120 (res 0x55abb4f478c0)
xwm: Rejecting WM_CHANGE_STATE to ICONIC for window 0x400007
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55abb4d72210 (res 0x55abb4a09ef0)
radv: Updated the per-vertex VRS rate to '0'.
wlserver: [types/wlr_surface.c:748] New wlr_surface 0x55abb4d72810 (res 0x55abb486e790)

[gamer@chimeraos ~]$ cat .steam-stdout.log
steam.sh[34305]: Running Steam on chimeraos 37　(1877cb7) 64-bit
steam.sh[34305]: STEAM_RUNTIME is enabled automatically
setup.sh[34376]: Steam runtime environment up-to-date!
steam.sh[34305]: Steam client's requirements are satisfied
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Loaded SDL version 2.27.0-p7692409
ComputeStartupMode: forcing gamepadui via cliInstalling breakpad exception handler for appid(steam)/version(1671675017)
Fontconfig warning: line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
steamwebhelper.sh[34477]: Runtime for steamwebhelper: defaulting to /home/gamer/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
steamwebhelper.sh[34477]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
steamwebhelper.sh[34477]: CEF sandbox already disabled
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
WARNING: using plain als gain get
CAppInfoCacheReadFromDiskThread took 359 milliseconds to initialize
Local Device Found
  type: 28de 1142
  path: /dev/hidraw0
  serial_number:  - 0
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    0

Local Device Found
  type: 28de 1142
  path: /dev/hidraw1
  serial_number:  - 0
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    1

!! Steam controller device opened for index 0.
Local Device Found
  type: 28de 1142
  path: /dev/hidraw2
  serial_number:  - 1
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    2

!! Steam controller device opened for index 1.
Local Device Found
  type: 28de 1142
  path: /dev/hidraw3
  serial_number:  - 2
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    3

!! Steam controller device opened for index 2.
Local Device Found
  type: 28de 1142
  path: /dev/hidraw4
  serial_number:  - 3
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    4

!! Steam controller device opened for index 3.
Installing breakpad exception handler for appid(steam)/version(1671675017)
privileged write polkit:auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValueToFileAsUser: steamos-priv-write failed /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValuetoFileAsRoot: failed to write to /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
sh: line 1: /usr/bin/steamos-polkit-helpers/jupiter-dock-updater: No such file or directory
536870913
privileged write polkit:auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Error: BWriteValueToFileAsUser: steamos-priv-write failed /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write: auto -> /sys/class/drm/card0/device/power_dpm_force_performance_level
Local Device Found
  type: 28de 1142
  path: /dev/hidraw0
  serial_number:  - 0
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    0

Error: BWriteValuetoFileAsRoot: failed to write to /sys/class/drm/card0/device/power_dpm_force_performance_level: auto
privileged write polkit:15000000 -> /sys/class/hwmon/hwmon2/power1_cap
Error: BWriteValueToFileAsUser: steamos-priv-write failed /sys/class/hwmon/hwmon2/power1_cap: 15000000
privileged write: 15000000 -> /sys/class/hwmon/hwmon2/power1_cap
Error: BWriteValuetoFileAsRoot: failed to write to /sys/class/hwmon/hwmon2/power1_cap: 15000000
Installing breakpad exception handler for appid(steam)/version(1671675017)
Local Device Found
  type: 28de 1142
  path: /dev/hidraw0
  serial_number:  - 0
  Manufacturer: Valve Software
  Product:      Steam Controller
  Release:      1
  Interface:    0

ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
ATTENTION: default value of option vk_xwayland_wait_ready overridden by environment.
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
Installing breakpad exception handler for appid(steam)/version(1671675017)
```

**Comment by peterge1998** [comment]
Update: Vampire survivor runs at 120 fps, at least its reported by mangohud

**Comment by Samsagax** [comment]
Closing as seems to be fixed
