### ISSUE TITLE
Mouse jumping around when using steam input

### ISSUE THREAD

**Issue by houku** [ChimeraOS/chimeraos#447]
When I set in games that need steam input, the mouse keeps jumping around even if I move very minimally, 

It happens in both steam and flatpak games, but not when using actual mouse and keyboard,

**Comment by alkazar** [comment]
This is in Gamepad UI or the old BPM?

**Comment by Samsagax** [comment]
Is this issue still relevant? Does it still happens in current testing image?

**Comment by houku** [comment]
This issue is still happening
