### ISSUE TITLE
Create a live system for evaluation purposes

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#45]
Because GamerOS requires a dedicated system, it is difficult for people to try it out. Enable users to try out GamerOS by creating a live system that can easily be installed to a USB drive.

Furthermore, the system should automatically mount other disks on the system and search out other Steam libraries and automatically add them to the Steam library (if possible) or link to an existing Steam folder.

Question: what to do if there are more than one Steam folders found? Perhaps link to the one that is the largest or has the most games installed?

**Comment by sharkwouter** [comment]
I might be possible to just mount a temporary filesystem as /home. What would the idea behind the live system be? Would it be a usb image with a bootloader? Does it need to have persistent data? Would DVD support be desirable?

**Comment by alkazar** [comment]
I was thinking it could try to find an existing Steam directory on any attached disks and try to use the games there. If none are found, it could use whatever space is on the usb device. Bonus points if we can also get this to work with Windows Steam libraries, but that would pose some problems for games with native Linux versions.

Persistent data is probably not necessary but would be nice.

DVD support is probably unnecessary.

**Comment by eiglow** [comment]
I think it should only try to find Steam libraries at default locations, and beyond that, let the user specify library locations. Allow the use of multiple libraries, much like how Steam already handles it.

![image](https://user-images.githubusercontent.com/16441870/67918786-b5f40580-fbed-11e9-8007-8e39c966bbce.png)

**Comment by alkazar** [comment]
After thinking about this again, I am not sure if it is a good idea to use existing Steam game libraries. GamerOS automatically applies tweaks to games and modifies Steam settings. When a user decides to go back to their library with their original OS, GamerOS might have messed up the user's custom game configurations.

**Comment by TeamLinux01** [comment]
Would it be possible to mount the extra drives as Read-Only and put an OverlayFS on top of it, so that it can make temporary changes?

**Comment by alkazar** [comment]
This will probably never happen.
