### ISSUE TITLE
Wake on Lan

### ISSUE THREAD

**Issue by peterge1998** [ChimeraOS/chimeraos#450]
https://github.com/ChimeraOS/chimeraos/issues/102
https://github.com/ChimeraOS/chimeraos/issues/266

Any news about wol? Would really like to see it implemented

**Comment by alkazar** [comment]
Wake on Lan was enabled in #102

**Comment by peterge1998** [comment]
>  Wake on Lan was enabled in #102

It did not work for me when i tried to test it a few days ago. Do i have to enable anything?

**Comment by alkazar** [comment]
Sorry, I don't know. It could be things have changed since it was implemented or perhaps there is something specific about your hardware.

Take a look here for a start:
https://wiki.archlinux.org/title/Wake-on-LAN

**Comment by peterge1998** [comment]
Never mind, it's working fine using this app: https://f-droid.org/en/packages/com.elektropepi.bootboi/.
