### ISSUE TITLE
HandyGCCS Gyro Activation

### ISSUE THREAD

**Issue by Alexmjacobs** [ChimeraOS/chimeraos#453]
Apologies I am new to this.

My understanding is HandyGCCS is now baked in from version 34? - The button mapping works great but I can't seem to activate gyro with any button presses.

On Holoiso 4 once installed it was a long press on "esc" to activate, but would stutter and was unusable.

I am on an Aya Neo founder.

I thought perhaps only the button mapping was implemented so tried to install HandyGCCS from source in console but the "git" command was not recognized. Then I tried installing locally and the "make" command was not recognized.

Then I thought maybe I need to install "base-devel" with pacman to install things on console (sudo pacman -s base-devel) but got "failed to initialize alpm library"

Anyway as you can see I am a nube and am trying to do my due diligence before posting.

Chimera OS is awesome and I would appreciate any help that can be given. Thanks!

**Comment by Nik123456789010** [comment]
This helps me on my Aya Neo Air: https://github.com/ShadowBlip/HandyGCCS/issues/26#issuecomment-1364409643
