### ISSUE TITLE
How to turn on FPS / FSR menu?

### ISSUE THREAD

**Issue by bashu** [ChimeraOS/chimeraos#457]
Is it possible to turn on FPS / FSR menu in gamepadui in latest chimera?

![word-image-7](https://user-images.githubusercontent.com/144783/208221983-f998c640-474b-458e-85aa-aa23e444c0d0.png)

**Comment by Samsagax** [comment]
Yes. But won't show in the client unless you enable it in the same menu (scroll down)

**Comment by bashu** [comment]
How can I enable this popup menu?

**Comment by Samsagax** [comment]
> How can I enable this popup menu?

Either navigate "up" and click on the battery icon or do Guide+A (PS+X in PS controllers). Also, holding up Guide (Or PS button) will show you all the guide chords the client admits.

**Comment by bashu** [comment]
I don't have battery icon on my stationary gaming pc, nor does holding up guide does anything

**Comment by Samsagax** [comment]
If you only have a keyboard I think is CTRL+2

**Comment by bashu** [comment]
> If you only have a keyboard I think is CTRL+2

I have only gamepad (xbox one via bluetooth) and mouse (wireless)

**Comment by bashu** [comment]
can you confirm that it (FPS/FSR menu) exists in chimera's version of gamepadui at all? any proofs? How come it's not available on my machine?

**Comment by Samsagax** [comment]
I need some more info to answer your last question:
- Are you on gamepadui?
- Does your Steam client answers correctly to guide button? (might be an entirely different issue if not)

As for the rest they come up as a little rude. But here is proof:
![2022-12-17-122033](https://user-images.githubusercontent.com/798775/208248966-1236a764-d16f-4ff7-ad04-498f9760ebd5.jpg)

**Comment by bashu** [comment]
ok, I see you have portable device with a battery inside, but I have stationary machine. 

Answering your questions:
* yes, enabled via ssh (don't remember the command, but found it here on the wiki)
* when I push the guide button (big X on xbox controller) it shows side menu (Home, Library, Downloads, and etc)

**Comment by bashu** [comment]
> As for the rest they come up as a little rude.

I am sorry you got offended, English is not my primary language. What sounds neutral in my tongue language, may sound rude after translation.

**Comment by Samsagax** [comment]
What does Guide+A and Guide+X do to you?

**Comment by bashu** [comment]
> What does Guide+A and Guide+X do to you?

Nothing

**Comment by Samsagax** [comment]
Weird... Could you switch to Steam beta client and see if that changes anything?

**Comment by bashu** [comment]
Yes, I switched to Steam beta via Settings menu, but nothing happend. Guide+X doesn't work.

**Comment by bashu** [comment]
> There appears to be some kind of bug concerning this right now. Try instead of holding Guide, just tapping Guide and then tapping the second button after a very short delay. This has been working for me.

Can confirm it works this way, but it still a bug

**Comment by frzifus** [comment]
Works for me too. But @bashu are you able to open the on screen keyboard?

**Comment by uejji** [comment]
> Works for me too. But @bashu are you able to open the on screen keyboard?

Try opening the OSK while running a game or app.  It works for me then.
