### ISSUE TITLE
Nvidia HDMI Audio distortion

### ISSUE THREAD

**Issue by whosnick** [ChimeraOS/chimeraos#460]
Fresh install with ChimeraOS 37.
Nvidia Geforce RTX 3080 HDMI Audio is really loud and distorted, every sound is just an ghastly crackling loud noise.

**Comment by Samsagax** [comment]
You have been hit with audio volume set to 10000. Enter a TTY, log in with default credentials (gamer/gamer) and do:
`$ pamixer --set-volume 60`

Should work fine afterwards.

**Comment by whosnick** [comment]
Oh ok thanks. If 10000 is the default volume for all Nvidia High Definition Audio HDMI drivers, maybe this commandline should run by default during installation.

**Comment by Samsagax** [comment]
It is a bug somewhere in the sound stack. Happens once in a while, the default volume should never be anything outside the range [0-100].

Anyway the alsa restore and save volume should kick in now and keep it on check from now on.

Closing as resolved

**Comment by bashu** [comment]
It's hardly resolved, I still have that problem. The only solution I found so far is to uninstall ChimeraOS
