### ISSUE TITLE
Proton Setting don't save in Tertis Effects Connected

### ISSUE THREAD

**Issue by Nik123456789010** [ChimeraOS/chimeraos#463]
Hi! The Problem starts that Tetris first start with don't recognizing my Steamuser. Then i set Proton 7 at Compatibility, it works. But after a system restart have to go to the Settings, Compatibility , then check and uncheck. Because without that Tetris will not start and fall back to BicPicture or GampadUi. Sorry to bother you with this one title, this problem a haven't under HoloISO. (i like chimera for his slacker build). Because Blossom Tales for example works fine. My System is a Aya Neo Air.

**Comment by alkazar** [comment]
Sounds like an issue with the Steam client.

**Comment by Nik123456789010** [comment]
OK. I reinstalled Chimera OS, the same behavior. Maybe there will be an update from Valve for the Client. Thank you.

**Comment by Nik123456789010** [comment]
After an reinstall of Chimer OS again i have started an Emulator Game first, this installs Proton 7, and then the Problem with Tetris was gone. Steamclient Version looks the same, from Dez. 22
