### ISSUE TITLE
Shutdown fails after installing decky

### ISSUE THREAD

**Issue by danyi** [ChimeraOS/chimeraos#465]
I installed the decky-loader on chimeraos, which caused the computer to fail to shut down. It seems that something is stuck in the background
What do I need to do to help with the investigation

**Comment by pastaq** [comment]
This is a problem with decky not managing created threads properly and you should post on their issues page.  ChimeraOS doesn't package or provide support for decky directly.

**Comment by Samsagax** [comment]
Closing as not supported
