### ISSUE TITLE
Install Steam os

### ISSUE THREAD

**Issue by McWalters00** [ChimeraOS/chimeraos#468]
How do we install Steam deck ui on chimera os (I’m on aya neo air) and is it compatible with this console?

**Comment by Samsagax** [comment]
https://github.com/ChimeraOS/chimeraos/wiki/FAQ#how-can-i-access-the-new-steam-deck-ui-or-the-desktop

**Comment by McWalters00** [comment]
> https://github.com/ChimeraOS/chimeraos/wiki/FAQ#how-can-i-access-the-new-steam-deck-ui-or-the-desktop

But how to use the terminal on big picture? (I’m not very good at that 😂)

**Comment by Samsagax** [comment]
In that same page: https://github.com/ChimeraOS/chimeraos/wiki/FAQ#how-can-i-access-the-terminal-from-chimeraos

**Comment by aarron-lee** [comment]
It's hidden away in troubleshooting, but if you want access to a terminal without a separate machine, you can use: https://github.com/ChimeraOS/chimeraos/wiki/Troubleshooting#option-2-not-recommended

> If you can’t use another computer to SSH into your ChimeraOS box, the other option is to plug a keyboard, and hit CTRL+ALT+F2 to switch from the GUI to a TTY terminal. When you’re finished, to switch back to the GUI, hit CTRL+ALT+F7.

> The default username/password is gamer/gamer
