### ISSUE TITLE
Tdp on chimera os

### ISSUE THREAD

**Issue by McWalters00** [ChimeraOS/chimeraos#471]
I can’t find any solution for the tdp because I’m sure aya neo air and the problem is that crankshaft doesn’t work and I have no other solution

**Comment by aarron-lee** [comment]
HandyPT's developer seems to be working to bring the missing functionality to powertools + decky-loader, see conversation [here](https://github.com/ShadowBlip/HandyPT/issues/21#issuecomment-1324042121). Decky seems to be more stable + have more developer resources thank Crankshaft, which would hopefully mean it won't break as often.

Note that I ran into the same problem on my Aya Neo Air Pro, I ended up creating a very quick and dirty [TDP app](https://github.com/aarron-lee/simple-ryzen-tdp) as a fallback for whenever crankshaft stops working.

Note that I'm **NOT** affiliated with the ChimeraOS project at all. I created this app for my Personal use only, with the intent on the app being a backup option on my Aya Neo Air Pro. I take no responsibility if you decide to try the app.

If you do end up trying the app, and need help with setup, let me know. I can create a guide with setup instructions specifically for ChimeraOS.

**Comment by McWalters00** [comment]
> HandyPT's developer seems to be working to bring the missing functionality to powertools + decky-loader, see conversation [here](https://github.com/ShadowBlip/HandyPT/issues/21#issuecomment-1324042121). Decky seems to be more stable + have more developer resources thank Crankshaft, which would hopefully mean it won't break as often.
> 
> 
> 
> Note that I ran into the same problem on my Aya Neo Air Pro, I ended up creating a very quick and dirty [TDP app](https://github.com/aarron-lee/simple-ryzen-tdp) as a fallback for whenever crankshaft stops working.
> 
> 
> 
> Note that I'm **NOT** affiliated with the ChimeraOS project at all. I created this app for my Personal use only, with the intent on the app being a backup option on my Aya Neo Air Pro. I take no responsibility if you decide to try the app.
> 
> 
> 
> If you do end up trying the app, and need help with setup, let me know. I can create a guide with setup instructions specifically for ChimeraOS.

Yes, why not, but do you have any idea when you could do this guide or not?

**Comment by aarron-lee** [comment]
Instructions for ChimeraOS 38, note that this only works in ChimeraOS 38 or newer. The app is broken/doesn't work in version 37 and lower.

just in case this helps, I threw together a simple, unedited youtube video guide here: https://youtu.be/_QlGXR1_nyE

1. In Desktop mode, download simple TDP AppImage: https://github.com/aarron-lee/simple-ryzen-tdp/releases
  - make the appimage executable in the file's properties, or with `chmod +x filename` in terminal/console
2. Download + install Appimage launcher Lite: https://github.com/TheAssassin/AppImageLauncher#differences-between-regular-and-lite-version
3. create a `/home/gamer/Applications` directory
4. move the Simple Ryzen TDP Appimage into the `/home/gamer/Applications`directory
5. download the `configure.sh` file: https://github.com/aarron-lee/simple-ryzen-tdp/blob/main/configure.sh
  - make it executable, similar to how it was done for the appimage
6. open a terminal/console, and run `which ryzenadj` to get the location of your ryzenadj file
  - note, it's included by default in ChimeraOS 38 at the `/usr/bin/ryzenadj` filepath
7. open a terminal/console where your `configure.sh` is saved, and run `sudo ./configure.sh path_from_previous_step`
  - e.g. `sudo ./configure.sh /usr/bin`
  - default password on ChimeraOS is `gamer`
8. to make sure your ryzenadj is setup properly, run `sudo ryzenadj -i` in a new terminal/console window. You should not be prompted for a password.
9. look for the `Simple Ryzen TDP` app in your desktop's app list, and open it
10. add `/usr/bin/ryzenadj` to the `ryzenadj path` input
  - I'd recommend filling in other settings here too, such as TDP Range, TDP on App Start, etc
11. open Steam, and add the app as a non-steam game
12. the app should now show up in Gaming mode

**Comment by McWalters00** [comment]
> Instructions for ChimeraOS 38, note that this only works in ChimeraOS 38 or newer. The app is broken/doesn't work in version 37 and lower.
> 
> 
> 
> just in case this helps, I threw together a simple, unedited youtube video guide here: https://youtu.be/_QlGXR1_nyE
> 
> 
> 
> 1. In Desktop mode, download simple TDP AppImage: https://github.com/aarron-lee/simple-ryzen-tdp/releases
> 
>   - make the appimage executable in the file's properties, or with `chmod +x filename` in terminal/console
> 
> 2. Download + install Appimage launcher Lite: https://github.com/TheAssassin/AppImageLauncher#differences-between-regular-and-lite-version
> 
> 3. create a `/home/gamer/Applications` directory
> 
> 4. move the Simple Ryzen TDP Appimage into the `/home/gamer/Applications`directory
> 
> 5. download the `configure.sh` file: https://github.com/aarron-lee/simple-ryzen-tdp/blob/main/configure.sh
> 
>   - make it executable, similar to how it was done for the appimage
> 
> 6. open a terminal/console, and run `which ryzenadj` to get the location of your ryzenadj file
> 
>   - note, it's included by default in ChimeraOS 38 at the `/usr/bin/ryzenadj` filepath
> 
> 7. open a terminal/console where your `configure.sh` is saved, and run `sudo ./configure.sh path_from_previous_step`
> 
>   - e.g. `sudo ./configure.sh /usr/bin`
> 
>   - default password on ChimeraOS is `gamer`
> 
> 8. to make sure your ryzenadj is setup properly, run `sudo ryzenadj -i` in a new terminal/console window. You should not be prompted for a password.
> 
> 9. look for the `Simple Ryzen TDP` app in your desktop's app list, and open it
> 
>   - add `/usr/bin/ryzenadj` to the `ryzenadj path` input
> 
>   - I'd recommend filling in other settings here too, such as TDP Range, TDP on App Start, etc
> 
> 10. open Steam, and add the app as a non-steam game
> 
> 11. the app should now show up in Gaming mode

Hi first thank you I tried it works perfectly but I have a little question that has nothing but me to go to the desktop mod I have to go through the terminal but how did you only switch the button switch to desktop mode?

**Comment by aarron-lee** [comment]
> I have a little question that has nothing but me to go to the desktop mod I have to go through the terminal but how did you only switch the button switch to desktop mode?

No idea, it already just worked for me without any changes. Perhaps a ChimeraOS developer could chime in here.

**Comment by Samsagax** [comment]
If you use Gamescope session (you need to go to a terminal and enable it once) then you can get back and forth from desktop to GamepadUI without needing to switch to a terminal.

**Comment by McWalters00** [comment]
> If you use Gamescope session (you need to go to a terminal and enable it once) then you can get back and forth from desktop to GamepadUI without needing to switch to a terminal.

How to use the gamescope session?
