### ISSUE TITLE
Lutris on chimera os

### ISSUE THREAD

**Issue by McWalters00** [ChimeraOS/chimeraos#472]
Hello, I would like to know what lutris works on chimera os? To install games via lutris

**Comment by Samsagax** [comment]
Litros is not officially supported but must games can be installed by the chimera web app. What are you trying to accomplish?

**Comment by McWalters00** [comment]
> Litros is not officially supported but must games can be installed by the chimera web app. What are you trying to accomplish?

I know it’s not very legal but I had crack spider man moral miles and when I put it in games not Steam well it doesn’t work but I had seen with lutris but so what’s the other trick ?

**Comment by Samsagax** [comment]
You can add any non-Steam games through chimera as shortcuts. As for installation, I think you are on your own.

https://github.com/ChimeraOS/chimera#steam-shortcuts-chimera---shortcuts

**Comment by McWalters00** [comment]
> You can add any non-Steam games through chimera as shortcuts. As for installation, I think you are on your own.
> 
> 
> 
> https://github.com/ChimeraOS/chimera#steam-shortcuts-chimera---shortcuts

How to put them in chimera os shortcut?

**Comment by Samsagax** [comment]
Read that friendly manual. It tells you exactly how to do it, you need to create and write a yaml file with your desired shortcuts.

**Comment by McWalters00** [comment]
> Read that friendly manual. It tells you exactly how to do it, you need to create and write a yaml file with your desired shortcuts.

When I click on the link it puts me the page at the beginning of chimera os and no indication for the shortcuts

**Comment by Samsagax** [comment]
> > Read that friendly manual. It tells you exactly how to do it, you need to create and write a yaml file with your desired shortcuts.
> 
> When I click on the link it puts me the page at the beginning of chimera os and no indication for the shortcuts

Weird... I just put the anchor link of the ChimeraOS/chimera repo README.md file and it Just Works (tm). I guess the "manual link" is: Go to ChimeraOS project on github >> chimera repository >> scroll down the Readme to the "Steam shortcuts" title.

**Comment by McWalters00** [comment]
> > > Read that friendly manual. It tells you exactly how to do it, you need to create and write a yaml file with your desired shortcuts.
> 
> > 
> 
> > When I click on the link it puts me the page at the beginning of chimera os and no indication for the shortcuts
> 
> 
> 
> Weird... I just put the anchor link of the ChimeraOS/chimera repo README.md file and it Just Works (tm). I guess the "manual link" is: Go to ChimeraOS project on github >> chimera repository >> scroll down the Readme to the "Steam shortcuts" title.

Thanks
