### ISSUE TITLE
Swap Space

### ISSUE THREAD

**Issue by j0hax** [ChimeraOS/chimeraos#473]
Is there any possibility of setting up a permanent swap file or partition? I am gaming on an older PC which has limited RAM, resulting in a complete freeze for some games that demand more memory.

PS: ChimeraOS is an awesome project, keep up the good work :)

**Comment by alkazar** [comment]
If a game needs to swap I doubt it will be playable. How much memory do you have?

But there was someone looking into doing this. It may be possible in the future.

**Comment by j0hax** [comment]
The idea is not to have a more playable game, but a more stable experience. In my case, when the system is low on memory it freezes up until a game is killed by the kernel's `oom_reaper` or I SSH into the box to manually `kill` the game. I image a relatively small swapfile (1/4 of installed memory, or maybe even just 1 GiB on every system) could be useful in these situations without wasting too much drive space.

While most gamers will have enough memory in their desktop rigs, I wouldn't be surprised if ChimeraOS is being installed to a lot of smaller HTPCs. In my scenario, I have some older games (Portal, LEGO Star Wars, etc.) running on a 2012 Mac Mini with 4 GiB RAM.

Other ideas aside from traditional swap:

- Enable [zram](https://wiki.archlinux.org/title/improving_performance#zram_or_zswap), which won't fix OOM situations on its own, but does give a little more leeway to systems strapped for memory.
- Include a userspace out-of-memory daemon, for example Fedora [switched](https://fedoraproject.org/wiki/Changes/EnableSystemdOomd#Benefit_to_Fedora) to `systemd-oomd` in 2021 to keep desktop systems more responsive.

**Comment by Samsagax** [comment]
Both zram (and zswap) and oomd can be implemented without any major modifications to frzr. Maybe we can include them. I'll check the impact and try to make a sane default.

Still. Lower than 8GB is kind of weak for gaming these days.

**Comment by CIB** [comment]
Yes, having an issue running yuzu with shader cache enabled on a 16GB handheld. I already tested this using the `swapon` command from ssh, and it does fix my problem. Is there a way to permanently enable a swap file? /etc/fstab is read-only, obviously.
