### ISSUE TITLE
Steam Interface and Games Incredibly Slow When Using Nvidia Card

### ISSUE THREAD

**Issue by patrick-13x** [ChimeraOS/chimeraos#477]
Hi,

I just installed ChimeraOS latest version and I'm running into some issues that I report here: 

1)The Steam UI and the games are INCREDIBLY slow when using Nvidia GTX 1650 card. Something like 1 FPS or less. Unusable of course, still diggin the cause. 

I really hope this issue can find a solution here cause I'd really like to try and use this new OS. 

Thanks for any help. 

Patrick

**Comment by Samsagax** [comment]
Are you sure you are using the Nvidia card? From my recollection you are in a hybrid configuration... So maybe you are using Intel card instead of your Nvidia card.

**Comment by patrick-13x** [comment]
Thanks for your reply. 
No, the interface and games are running ok when using the motherboard graphic port, but its all slowing down when the display is connected to the Nvidia GPU output.

**Comment by Samsagax** [comment]
Are you using newer GamepadUI or old Big Picture Mode session?

**Comment by joaquinvacas** [comment]
Here using a desktop board B150M-A with iGPU disabled.

GTX 1050 OC, runs fine on games but UI is full of glitches and lagging so hard.

**Comment by joaquinvacas** [comment]
> Are you using newer GamepadUI or old Big Picture Mode session?

Oh, here using the default UI, the "GamepadUI".

Tried Chimera 40, nothing changed.

**Comment by ruvaldak** [comment]
2080ti, 1440p display, just installed it today. GamepadUI is slow & laggy for me as well.

**Comment by joaquinvacas** [comment]
> 2080ti, 1440p display, just installed it today. GamepadUI is slow & laggy for me as well.

Tried mine on 4K and 1080 displays, even setting manually the resolution, doesn't change a thing.

Can't say it happened on older versions as this is my first time using ChimeraOS

**Comment by ruvaldak** [comment]
Seems better at 1080p60hz, but still chugs. 1080p 120 of higher is also relatively fine, but anything higher than 1080p becomes very buggy. Almost flickery animations, like it's playing two even frames, then two odd frames (instead of 1-2-3-4, it does 2-1-4-3, if four frames were numbered in sequence.) Also, ran a steam update on my 1440p display and it was a corrupted rainbow noise nightmare. Could still see the steam logo and progress bar, but it was heavily corrupted with graphical errors.

**Comment by Godsbane** [comment]
This is Valve's fault from what I can tell.
I've tested holo as well as simply Nobara with the new big picture. Just terrible with Nvidia.

**Comment by ruineka** [comment]
If you have a CPU with an iGPU plug into the motherboard and turn on the PC. If your motherboard supports it you will have a much better experience with Nvidia this way.

If this doesn't work try going into your bios and look for options to enable both the iGPU and dedicated GPU at the same time.

**Comment by pastaq** [comment]
> This is Valve's fault from what I can tell. I've tested holo as well as simply Nobara with the new big picture. Just terrible with Nvidia.

Nvidia not providing full Vulkan support in their Linux drivers is in no way Valves fault.

**Comment by joaquinvacas** [comment]
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3731840159844956304

Good news!

**Comment by Alan502** [comment]
@joaquinvacas How's the performance now? I'm thinking about installing Chimera on a computer with a 3060. Has nvidia fixed their issues with gamescope yet?

**Comment by pastaq** [comment]
> @joaquinvacas How's the performance now? I'm thinking about installing Chimera on a computer with a 3060. Has nvidia fixed their issues with gamescope yet?

We are removing Nvidia drivers in the next version due to continuing issues with the driver affecting non-Nvidia systems while not having full support. When Nvidia fixes their drivers we will consider adding them again.
