### ISSUE TITLE
[Fresh install] black Screen with `_` at the top

### ISSUE THREAD

**Issue by neevany** [ChimeraOS/chimeraos#482]
Version: 38-c47f2bb
Cpu: Intel i7 11th Gen with UHD Graphics
Not able to switch to tty using `ctrl+alt+f3`

**Comment by lukasgierth** [comment]
I had the same problem with my Intel i3 Cpu and RX6600 graphics card:

Seems to be a problem with the installer and NOT the 38-c47f2bb image it installs.
I used the latest prerelease installer from https://github.com/ChimeraOS/install-media/releases
It installs the same chimeraos-38 image. But works perfectly afterwards!

**Comment by Samsagax** [comment]
@neevany can you test the proposed fix?
