### ISSUE TITLE
Feature Request: Corectrl 

### ISSUE THREAD

**Issue by cpliatsikas** [ChimeraOS/chimeraos#483]
Hello ,
Just two requests to be considered
1) could you add corectrl to chimera, it's the only reason i dont use it honestly cause i need to be able to configure the fan curve and voltage on my gpu. 

thank you

**Comment by Samsagax** [comment]
Fan curve can be controlled by HHFC.
for voltage we are working on another solution since HandyPT is based on crankshaft and it is borked at the moment with a non-responsive dev.

what is your hardware?

**Comment by cpliatsikas** [comment]
I am not familiar with HHFC , does it come built-in? that'ss great news actually.

b550 board , 16gb 3200 ddr4 ram , r5 5600 and an amd rx 6700

**Comment by Samsagax** [comment]
That setup should be well supported by hhfc (assuming your Mobo has an interface in hwmon of the case fans) and for the core voltages and such there is ryzenadj that is included. With a controller on the way by @pastaq

**Comment by cpliatsikas** [comment]
so hhfc is built in ? cause as far as i know chimera has access only to flathub apps.

**Comment by Samsagax** [comment]
> so hhfc is built in ? cause as far as i know chimera has access only to flathub apps.

It is in the system. You need to configure it and enable the service. Is currently a CLI tool so you'll need access to a TTY either on the same machine of via SSH.

**Comment by cpliatsikas** [comment]
that's great ,i ll give it a try.is there maybe some kind of documentation describing all cli tools cause they may contain  solutions for other ppl issues.as far as i can tell i can see the packages in the manifest but ofc i am not familiar with all so some were overlooked .I ll also try unlocking the system and installing what i need ,just found out that this option exists.Overall i had the best experience with chimera as compared to  holoiso or simply adjusting a desktop distro to boot in to gamepadui mode but the limitations in the packages kept me away. But it's time to give it a go again . i ll try to post every issue i face along with a fix on a new thread and hopefully it will help others in the future.
