### ISSUE TITLE
Unable to proerly create manual YAML entry for Steam, launch fails

### ISSUE THREAD

**Issue by npaladin2000** [ChimeraOS/chimeraos#487]
I'm switching to desktop mode to add a game, and it works as long as I'm in desktop mode. As soon as I switch to Game Mode, any entries I created go away and have to be re-created.  This is with Chimera 38, using GamepadUI.

**Comment by npaladin2000** [comment]
Ok apparently this is a known issue, and the workaround is to manually do YAML files in ~/.local/share/chimera/shortcuts/
 but I'm not having any luck getting it running. 

Mod is in /home/gamer/.local/share/Steam/steamapps/common/FINAL FANTASY VII/
There's a soft link to the directory as well /home/gamer/FINAL FANTASY VII/

When using the real path, it just gives up (might be permissions). When I put the shortcut path in the YAML file, it tries to start and hangs up.  the "cmd" is the .exe file (SYWV5controlpanel.exe) and the compat_tool is proton_7

- banner: /home/gamer/FF7Art/ff7_grid.png
  cmd: SYWV5controlpanel.exe
  compat_tool: proton_7
  dir: "/home/gamer/.local/share/Steam/steamapps/common/FINAL FANTASY VII/"
  hidden: false
  name: Final Fantasy 7 Modded
  poster: /home/gamer/FF7Art/ff7_grid.png
  tags:
  - Mods

or 

- banner: /home/gamer/FF7Art/ff7_grid.png
  cmd: SYWV5controlpanel.exe
  compat_tool: proton_7
  dir: "/home/gamer/FINAL FANTASY VII/"
  hidden: false
  name: Final Fantasy 7 Modded
  poster: /home/gamer/FF7Art/ff7_grid.png
  tags:
  - Mods

Could use some advice here.  Not sure I'm doing this YAML right.  I should emphasize that I can add this manually in desktop mode and run it.

**Comment by pastaq** [comment]
https://github.com/ShadowBlip/steam-shortcut-manager might work for you.

**Comment by npaladin2000** [comment]
Handy, thank you.
