### ISSUE TITLE
Feature request: NintendoDS built-in support

### ISSUE THREAD

**Issue by npaladin2000** [ChimeraOS/chimeraos#489]
This might be tricky to do given the number of buttons that would need to be configured, so I understand if this would get waved off, but it would be really nice to have direct support, including being able to change screen views, swap screens, close the lid (a couple games requre this) and trigger the mic (a couple other games need this) and darn that's a lot of functions for not a lot of buttons, but if I don't ask no one can say yes, right?

**Comment by pastaq** [comment]
I'm not too familiar with NDS emulation as I lost most of my cartridges a while back. Do you have an example of how to configure this? It would likely take some doing to make it generic enough for any misc hardware to work. I.E a full desktop with a Switch Pro controller under BT vs a handheld using HandyGCCS would all need to be considered.

**Comment by npaladin2000** [comment]
Yeah, I'm pretty familiar with emulating it. I assume the best baseline would be an X-box style controller, try and fit as many functions as we can into that layout?  L2, R2, and L3 would be available to use since they don't exist on the DS itself. R stick and R3 should probably go to a virtual stylus and tap though, since not every screen is a touchscreen. So it's just a matter of figuring out which three functions should go to those buttons. Problem is, I can think of 4 candidates:

- Screen layout (switch between large/small, top/bottom, side/side)
- Screen swap (probably only makes sense in the first mode above)
- Microphone
- Lid open/close

I think most people will want both of the first two, so I'd put those on the triggers. I think Zelda requires the lid close thing, so much as it pains me the lid button should probably take priority over the mic (which is used in Mario Kart's battle mode, which I love personally).

**Comment by alkazar** [comment]
All that sounds overly complicated and unlikely to happen. Is there a simpler config that will work with a subset of games?

**Comment by npaladin2000** [comment]
You could probably just get away with the screen functions on just the triggers, or maybe even drop that and just default to the screens being side-by-side.  That would leave the only "special" thin\g as the right stick for the touch screen. Not sure one can get away without that on a DS setup since so many games rely on touching that bottom screen.  

As I recall there's a way for users to put in custom config files if they really want them? I suppose if someone wanted the extra functionality they could get it that way.

**Comment by alkazar** [comment]
I think RetroArch handles some of that. I tried it out a while back, and it worked okay. I got distracted though so haven't followed up. I'll have to give it another go.

**Comment by npaladin2000** [comment]
I probably already did most of this work when I manually added nds on my local device recently, if you want.

**Comment by alkazar** [comment]
Thanks to @npaladin2000 Nintendo DS is now available in ChimeraOS 39.
:bow:
