### ISSUE TITLE
Black screen trying to login to Epic Games

### ISSUE THREAD

**Issue by abowlofsoda** [ChimeraOS/chimeraos#491]
I've tried from many different browsers on another computer on my network.  I even tried on my phone.  I'm getting a black screen with 1 line of text:
{"redirectUrl":"https://localhost/launcher/authorized","authorizationCode":null,"sid":null}

It did have auth codes when I first tried but it went empty after logging into GOG then trying Epic Games again.

**Comment by alkazar** [comment]
You are not logged in. The link provided used to redirect to a login page if you were not logged in, but it seems that has changed. Log in to your Epic Account on the same browser first, then click on the link in the Chimera app.

**Comment by alkazar** [comment]
I am working on a much simplified login flow thanks to EGS opening up their developer tools to anyone. In the mean time I will update the copy to reflect the new state of things.

Thanks.
