### ISSUE TITLE
Distorted Audio over HDMI

### ISSUE THREAD

**Issue by InvisibleFunction** [ChimeraOS/chimeraos#500]
I used to have everything working fine but after some update I now only get distorted audio over HDMI. I'm on version 38 and I've restarted a bunch and let it do a bunch of configuration updates. I've tried with both an EVGA 2070 and a ASRock RX 5700 XT and I get the same issue with both.

This distorted audio was how everything worked after I initially installed but I was able to fix it with a setting in Settings>Audio Interface (or something like that)

Here are the settings that are currently available after I select "Reconfigure Audio":
For the device I see:
>Navi 10 HDMI Audio: HDMI / DisplayPort
>Built-in Audio: Digital Output (S/PDIF)

for audio presentation I see:
>Digital Stereo (HDMI) Output
>Digital Surround 5.1 (HDMI) Output
>Digital Surround 7.1 (HDMI) Output

And then I can select which codecs can be passed-through:
>DTS Pass-through
>AC3 Pass-through
>EAC3 Pass-through

My HDMI goes over a cat6 extender to an LG C7 TV and then the sound is connected over optical to a 7.1 receiver. I've tried all combinations of audio presentation and pass through, but I can't get it to stop making horrible noises. I swear there used to be some other option in here that fixed it. Maybe something with "PCM"? Any ideas?

**Comment by Samsagax** [comment]
I think is a duplicate of #357 could you check that?

**Comment by InvisibleFunction** [comment]
Yes, it does appear to be a duplicate. I checked and my audio was set to 10000%.
