### ISSUE TITLE
RX 6700 XT stuck at 500mhz

### ISSUE THREAD

**Issue by ibanezbass** [ChimeraOS/chimeraos#505]
As title says, RX 6700 XT is stuck at 500mhz max. I'm having trouble finding a lot of people with this issue in arch, but I did find one post from a 6650 XT that was stuck at 500mhz and the fix was to run a newer linux firmware. I'm not sure that's the issue here though.

**Comment by ibanezbass** [comment]
It's gamepadUI that's breaking it. If I boot first into desktop, the clocks are normal. Once I access gamepadUI, I get locked to 500mhz, ~47 watts

**Comment by ruineka** [comment]
> It's gamepadUI that's breaking it. If I boot first into desktop, the clocks are normal. Once I access gamepadUI, I get locked to 500mhz, ~47 watts

I have a 6700 XT and 6900 XT that I use and haven't had any issues. What brand do you have? I'm curious if its a bios thing on the card glitching out.

**Comment by ibanezbass** [comment]
It’s a Gigabyte Eagle. FWIW, I experience the same problem in HoloISO if the jupiter-hw-support package gets updated.

**Comment by schyhub** [comment]
> It’s a Gigabyte Eagle. FWIW, I experience the same problem in HoloISO if the jupiter-hw-support package gets updated.
> 
> I noticed there was a vBios update for my card that fixes this exact issue in Windows, but it appears that my card is already running the updated vBios.

That interesting. I have the exact model and it suffers 500Mhz bug when I got it long time ago. But after I updated the BIOS for the card, it works exactly as expected. Any chance you can check the vbios version?

**Comment by ibanezbass** [comment]
> > It’s a Gigabyte Eagle. FWIW, I experience the same problem in HoloISO if the jupiter-hw-support package gets updated.
> > I noticed there was a vBios update for my card that fixes this exact issue in Windows, but it appears that my card is already running the updated vBios.
> 
> That interesting. I have the exact model and it suffers 500Mhz bug when I got it long time ago. But after I updated the BIOS for the card, it works exactly as expected. Any chance you can check the vbios version?

So, I dumped the vBios last night and opened it in a text editor. The clear text shows it's running the F2 bios, which is the up to date version. However, today, I got a prompt to flash the firmware on the card from Aorus Engine. That completed successfully, but didn't make a difference in ChimeraOS. Still locked to 500 mhz in gamepadUI.

**Comment by sofakng** [comment]
Wow, I'm having this exact same issue on my reference Radeon 6700 XT.  (I'm slowly learning more about Linux and lots of issues are at least forcing me to learn even more, haha!)

I was wondering why my games are performing terribly and looking at /sys/kernel/debug/dri/0/amdgpu_pm_info shows my SCLK at 500 MHz (max).

I'll try looking at the power limit, but do you know if there is a VBIOS upgrade for the reference AMD 6700 XT?

**Comment by ruineka** [comment]
> Wow, I'm having this exact same issue on my reference Radeon 6700 XT.  (I'm slowly learning more about Linux and lots of issues are at least forcing me to learn even more, haha!)
> 
> I was wondering why my games are performing terribly and looking at /sys/kernel/debug/dri/0/amdgpu_pm_info shows my SCLK at 500 MHz (max).
> 
> I'll try looking at the power limit, but do you know if there is a VBIOS upgrade for the reference AMD 6700 XT?

I believe the problem was caused by the fact Steam gained write access to stuff it shouldn't have and it was limiting the GPU to 15W. If you installed Decky Loader with PowerTools I believe this sets up permissions for it to change these values assuming you are on a Steam Deck, not a dedicated PC.

**Comment by sofakng** [comment]
Ahh, OK ... What is the solution?

I've installed PowerTools and tried to set the GPU clocks (to 1600, which is the max the GUI displays) but it doesn't stick and just resets after setting it.

**Comment by ruineka** [comment]
> Ahh, OK ... What is the solution?
> 
> I've installed PowerTools and tried to set the GPU clocks (to 1600, which is the max the GUI displays) but it doesn't stick and just resets after setting it.

I'm assuming they set up a polkit giving Steam root permission to the values changed. I'm not entirely sure how exactly PowerTools sets up no password root permissions.

**Comment by pastaq** [comment]
PowerTools runs as root, it doesn't need polkits.

**Comment by sofakng** [comment]
Thanks so much for the help!
