### ISSUE TITLE
About Gamer user password

### ISSUE THREAD

**Issue by zhaop9** [ChimeraOS/chimeraos#507]
The password was not set during the installation process, and the admin, 12345, etc. have been tried and are unavailable. The default user name after installation is gamer. You want to provide the default password. thank you

**Comment by npaladin2000** [comment]
default password is in the Wiki FAQs

https://github.com/ChimeraOS/chimeraos/wiki/FAQ#how-can-i-access-the-terminal-from-chimeraos

**Comment by alkazar** [comment]
The default password is 'gamer'.
