### ISSUE TITLE
About installing the Plasma desktop environment

### ISSUE THREAD

**Issue by zhaop9** [ChimeraOS/chimeraos#508]
Please refer to how to install the Plasma desktop environment or how to install the Discover Software Management Center. thank you

**Comment by alkazar** [comment]
I am not sure what you are asking for.

ChimeraOS uses Gnome and the Gnome software center.

**Comment by zhaop9** [comment]
On how to solve the problem of installing applications, the Gnome Software Center seems to be unstable, with serious network delays or crashes. And I can't find the application I want, such as gnome disk tool

**Comment by Samsagax** [comment]
`gnome-disk-tool` in particular got removed from latest version inadvertedly. What are you trying to accomplish?

Installing KDE/Plasma as a desktop is not planned, nor is the idea of making ChimeraOS a general purpose distribution. It is meant to be a gaming console OS for PCs
