### ISSUE TITLE
Issues with NVIDIA Graphics Card

### ISSUE THREAD

**Issue by robarmstrong96** [ChimeraOS/chimeraos#509]
I'm using an NVIDIA RTX A2000 GPU with ChimeraOS v39 (just switched over from both Windows 11 and Manjaro which both appeared to work fine in contrast to ChimeraOS) and I'm running into a few issues. 

- The display I'm using flickers black randomly (or just cuts out completely) while in-game or using the Gamepad UI. Issue doesn't appear to occur while in Windows 11 or Manjaro with most recent NVIDIA graphics drivers. Just in case, I'm using a Hisense ULED 4K Premium 50U6G, connecting to the display using a [mini-display to display-port adapter](https://monitors.com/products/pny-adapter-91008582v3) and then a [display-port to HDMI cable](https://www.amazon.com/gp/product/B08CR2ZF9Z/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).
- I'm noticing constant stuttering while using the Gamepad UI. Doesn't appear to matter what I'm doing, as long as I'm browsing throughout the Gamepad UI, there is stuttering occurring. 
- This is (probably) not specific to NVIDIA hardware, but It appears gamescope is by default set to upscale games from a max resolution of 1280x720, at least for my 16:9 display. GamepadUI allows me to set the resolution to the highest possible resolution achievable for my display in Settings -> Display, but in game, games are maxed out at 1280x720. I can get around this by going to the game properties and setting the game resolution to anything but "Default".

Please let me know if there is any other information I can provide to help troubleshoot.

**Comment by ruineka** [comment]
Nvidia has really poor support for both gamescope and the new steam deck UI in regards to performance and artifacting. The 800P situation is the default behavior of Steam, but you can set your native display resolution in the game properties.

I don't recommend anyone try to use Nvidia at this time unless they are looking to help find workarounds and/or report issues to Nvidia in hopes to show enough demand for them to fix their drivers.

**Comment by robarmstrong96** [comment]
Ahh, I had heard [rumblings](https://forums.developer.nvidia.com/t/request-for-gamescope-and-the-vk-ext-image-drm-format-modifier/208614) about NVIDIA working on better support for gamescope, but I guess that's not the case.

**Comment by ruineka** [comment]
> Ahh, I had heard [rumblings](https://forums.developer.nvidia.com/t/request-for-gamescope-and-the-vk-ext-image-drm-format-modifier/208614) about NVIDIA working on better support for gamescope, but I guess that's not the case. 

It's better than it was but it's far from usable IMO.

**Comment by robarmstrong96** [comment]
I'll go ahead and close this as these issues don't appear to be specific to ChimeraOS, but instead NVIDIA and gamescope. Hopefully NVIDIA gets their shit together.
