### ISSUE TITLE
On how to solve the problem of installing applications, the Gnome Software Center seems to be unstable, with serious network delays or crashes. And I can't find the application I want, such as gnome disk tool

### ISSUE THREAD

**Issue by zhaop9** [ChimeraOS/chimeraos#510]
On how to solve the problem of installing applications, the Gnome Software Center seems to be unstable, with serious network delays or crashes. And I can't find the application I want, such as gnome disk tool

**Comment by Hideiuke** [comment]
You can only install flatpak softwares, because by default the root file system is locked.
The "frzr-unlock" command can be used to unlock it, i used sometimes... but i think it's not recommended.

**Comment by npaladin2000** [comment]
gnome-disk-tool isn't available in the image, but if you're looking to mount storage it can be done via the Chimera web UX. 

Remember that ChimeraOS is not a full desktop UX, it's meant to be console experience.
