### ISSUE TITLE
Mangohud overlay is in middle of screen on Intel OXP

### ISSUE THREAD

**Issue by ibanezbass** [ChimeraOS/chimeraos#514]
The mangohud overlay in gamescope is in the middle of the screen instead of the top left corner. 

![image](https://user-images.githubusercontent.com/3300345/220468724-c79886a4-7040-47ce-8bc6-e86a68dea1c4.jpg)

**Comment by alkazar** [comment]
This is a known issue with MangoHUD on displays that require orientation fixes.

See https://github.com/flightlessmango/MangoHud/issues/823

**Comment by pastaq** [comment]
> This is a known issue with MangoHUD on displays that require orientation fixes.
> 
> See [flightlessmango/MangoHud#823](https://github.com/flightlessmango/MangoHud/issues/823)

I think this is a compound issue BTW, one of which affects users over 800p. The external overlay display doesn't get scaled to the same resolution as the primary display.
