### ISSUE TITLE
WARNING:No configuration file found on first boot.

### ISSUE THREAD

**Issue by OhaDerErste** [ChimeraOS/chimeraos#517]
Im trying to install chimeraos on a Dell Optiplex with a i7 6700 and rx 6400. Im getting this error on boot: 
![SGCAM_20230224_232324290](https://user-images.githubusercontent.com/77100649/221319962-759d6658-1a78-4465-80af-97aeb6b34e8c.jpg)

**Comment by npaladin2000** [comment]
I can confirm this is reproducible, I tested on an Optiplex 7050 as well, with an iGPU, installing in UEFI mode (the current bootable USB doesn't boot in legacy mode). Same proc, the i6700, so I assume the OP is using something close to a 7050  In fairness this platform is getting a little long in the tooth, plus it's a corporate model.

**Comment by ruineka** [comment]
@alkazar 6th gen and older it would seem is broke.

**Comment by OhaDerErste** [comment]
> I can confirm this is reproducible, I tested on an Optiplex 7050 as well, with an iGPU, installing in UEFI mode (the current bootable USB doesn't boot in legacy mode). Same proc, the i7 6700, so I assume the OP is using something close to a 7050. In fairness this platform is getting a little long in the tooth, plus it's a corporate model.

should have mentioned that. its a 7040 sff

**Comment by ruineka** [comment]
> I can confirm this is reproducible, I tested on an Optiplex 7050 as well, with an iGPU, installing in UEFI mode (the current bootable USB doesn't boot in legacy mode). Same proc, the i7 6700, so I assume the OP is using something close to a 7050.  In fairness this platform is getting a little long in the tooth, plus it's a corporate model. 

Can you try copying bootloader files from boot/EFI/BOOT/* to boot/EFI/*?

Its a shot in the dark but it seems like some systems look for the bootloader files in a different location.

**Comment by ruineka** [comment]
> I can confirm this is reproducible, I tested on an Optiplex 7050 as well, with an iGPU, installing in UEFI mode (the current bootable USB doesn't boot in legacy mode). Same proc, the i7 6700, so I assume the OP is using something close to a 7050.  In fairness this platform is getting a little long in the tooth, plus it's a corporate model. 

Looking at the history of the project it would seem some UEFI systems were using a completely different path as well.

${MOUNT_PATH}/boot/EFI/syslinux/syslinux.cfg

I think a little experimenting with this could find us an answer.

**Comment by bt61** [comment]
> Im trying to install chimeraos on a Dell Optiplex with a i7 6700 and rx 6400. Im getting this error on boot: ![SGCAM_20230224_232324290](https://user-images.githubusercontent.com/77100649/221319962-759d6658-1a78-4465-80af-97aeb6b34e8c.jpg)

Did you ever solve this?  I just bought an Optiplex with the i7-6700 and was planning on buying an rx 6400, primarily to run Chimera.  Hoping I won't have any problems!

**Comment by ruineka** [comment]
> > Im trying to install chimeraos on a Dell Optiplex with a i7 6700 and rx 6400. Im getting this error on boot: ![SGCAM_20230224_232324290](https://user-images.githubusercontent.com/77100649/221319962-759d6658-1a78-4465-80af-97aeb6b34e8c.jpg)
> 
> Did you ever solve this?  I just bought an Optiplex with the i7-6700 and was planning on buying an rx 6400, primarily to run Chimera.  Hoping I won't have any problems!

It should work now as we moved to systemd-boot, just make sure you are using UEFI if your bios has an option to use Legacy/CSM. To do so disable legacy/CSM bios.

**Comment by OhaDerErste** [comment]
> > Im trying to install chimeraos on a Dell Optiplex with a i7 6700 and rx 6400. Im getting this error on boot: ![SGCAM_20230224_232324290](https://user-images.githubusercontent.com/77100649/221319962-759d6658-1a78-4465-80af-97aeb6b34e8c.jpg)
> 
> Did you ever solve this? I just bought an Optiplex with the i7-6700 and was planning on buying an rx 6400, primarily to run Chimera. Hoping I won't have any problems!

works fine now
