### ISSUE TITLE
Slow Deck Interface While Navigating

### ISSUE THREAD

**Issue by ViewInSolitude** [ChimeraOS/chimeraos#521]
I installed Chimera as a clean, fresh install, and am encountering odd performance issues within the Steam Deck interface.

I am running a NVIDIA GPU on a desktop with the Intel iGPU disabled currently. Navigating through with the different animations all appear choppy and sluggish. 

It is not unusable, but definitely is a little distracting and odd considering the hardware that is being ran. I would like to continue running this OS as I have high interest in at least trying it.

Intel Core i7-10700
NVIDIA GeForce RTX 2070 Super
32GB DDR4-3000

**Comment by alkazar** [comment]
This is a known issue with Nvidia.

**Comment by ViewInSolitude** [comment]
Ahh ok. In that case I'd imagine that is something Valve would have to fix with the interface on that level. It is still functional for now at least.
