### ISSUE TITLE
grub modification

### ISSUE THREAD

**Issue by digitalaiz** [ChimeraOS/chimeraos#522]
Hello , 

So i have unlocked the filesystem , added aur and compiled yay in order to install corectrl . 
In order to unlock the advanced corectrl options i need to add an entry in /etc/default/grub which doesn't seem to exist.I suppose is because what i am seeing is the frzr-root and not the actual root. 

Is there a way to add that entry ?

THank you in advance

**Comment by pastaq** [comment]
you need to edit the syslinux.cfg in /boot to modify the boot parameters.

Be aware that all these changes you are making will be wiped out when the system updates. What are you attempting to do with corectrl? I might be able to add it to an upcoming feature.

**Comment by digitalaiz** [comment]
so basically i want to be able to to have access to the gpu power limits and voltage in order to undervolt and OC .better performance lower power consumption which is something you want to have on a SFF console pc .

I was able to do everything by unlocking the fs except the last section "Full AMD GPU controls"as described here : https://gitlab.com/corectrl/corectrl/-/wikis/Setup#full-amd-gpu-controls

Ofc the corectrl service wont start on boot unless you switch to desktop mode ( i suppose it could be fixed by modifying the target for the service maybe ) so i am simply adding it to steam and just running it from there once i boot up the system.

**Comment by Samsagax** [comment]
If you know what you want undervolted, you can write to the sysfs files directly. Also the `amdgpu.ppfeaturemask=0xffffffff` can be acchieved by setting a configuration file for modprobe, [here is how](https://wiki.archlinux.org/title/Kernel_module#Using_files_in_/etc/modprobe.d/)

**Comment by cpliatsikas** [comment]
Thank you for the recommendation , although i am familiar with the theory i haven't messed modprobes before .I ll research on that
