### ISSUE TITLE
user "gamer" password

### ISSUE THREAD

**Issue by Grevyo** [ChimeraOS/chimeraos#532]
I'm trying to get decky loader going, trying it through console but get stuck on entering password, 
i've tried gamer and admin, and some others I may have set, wondering if anyone could help me with unlocking the account or with the default password?

**Comment by pastaq** [comment]
The username and password are both gamer

**Comment by Grevyo** [comment]
> The username and password are both gamer

I have just done a fresh install and its worked thank you, 
not sure when I changed it
