### ISSUE TITLE
Scrolling horizontal lines at 4k on Nvidia 3080

### ISSUE THREAD

**Issue by andy3471** [ChimeraOS/chimeraos#533]
I've done a fresh chimera 39 install on a PC with an Nvidia 3080 on a 4k 120hz TV. The interface is laggy as expected, but in game performance is fine. 

However, if I set my in game resolution to Native or 3840x2160, and set the game to that resolution, I will see white dots in horizontal lines scrolling up the screen, similar to what you'd see on a VHS. 

This happens in all games, but not the steam interface.

Strangely, in games like Planet Coaster, where the mouse is visible, they go away for a few seconds every time I use the mouse.

The lines go away if I select any lower resolution and upscale to my display resolution.

If I go into the global steam settings, and set my display output to 1440p, and the game to 1440p (or above),  I get the exact same issue at 1440p.

If I select any lower resolution to native, and set the scaling to "Integer", I can also replicate the issue. But any other scaling method works fine.

I suspect this is an issue with gamescope, rather than Chimera, so let me know if this is the wrong place to raise it.

**Comment by alkazar** [comment]
This is a known issue with at least the 30 series Nvidia cards and gamescope.
The 10 series doesn't seem to be affected, I have no reports either way with the 20 series cards.

A workaround I have found is to set the global resolution to 1080p, then set the individual game resolution to 1440p.
This way you get the game rendering at 1440p then downscaled to 1080p.

You may be able to do something similar with 1440p and 2160p, but my TV doesn't support 1440p so I cannot verify.

**Comment by alkazar** [comment]
Looks like there is an issue reported in gamescope for this already: https://github.com/Plagman/gamescope/issues/599

**Comment by Insta-Dead** [comment]
> Strangely, in games like Planet Coaster, where the mouse is visible, they go away for a few seconds every time I use the mouse.
This is very similar issue to Which i posted: https://github.com/ChimeraOS/chimeraos/issues/540 
Mouse Movement seems to Temp Fix 2 separate issue's with Gamescope so maybe a dpi scaling issue or full screen/borderless 
Any help be much appreciated
