### ISSUE TITLE
Lutris flatpak - Steam shortcut not showing up

### ISSUE THREAD

**Issue by aaronson2012** [ChimeraOS/chimeraos#536]
I installed the Lutris flatpak to play Overwatch 2. I tell Lutris to create a steam shortcut, but it does not show up in Steam. Lutris seems to think the shortcut is there however as I have the option to "delete steam shortcut" from the right click menu on the game.

**Comment by THFourteen** [comment]
Had the same issue. Created a desktop shortcut and then added it to steam as a non steam game in desktop mode.

**Comment by al12gamer** [comment]
Had the same issue. Got a 505 error when using the Web UI. Needed it for Diablo IV. Installing Lutris from flatpak and then Battle
Net to see if I can add it to steam that way.

**Comment by pastaq** [comment]
https://github.com/chimeraOS/chimera#steam-shortcuts-chimera---shortcuts

**Comment by al12gamer** [comment]
What sort of work would be required in order for the right click "create steam shortcut" functionality in Lutris to be working without a hitch?

**Comment by al12gamer** [comment]
Hmm, looks like adding a battle.net launcher shortcut to steam is now working in ChimeraOS. This can likely be closed.
![Screenshot from 2024-01-09 11-56-56](https://github.com/ChimeraOS/chimeraos/assets/10056498/b61e4aa0-dd50-4374-876e-08127c4cf07e)
