### ISSUE TITLE
One X Player mini 5800u (Gamescope Issue) Maybe?

### ISSUE THREAD

**Issue by Insta-Dead** [ChimeraOS/chimeraos#540]
Hello
ok so when im using Gamescope in gamepadui mode,  I enable performance overlay slider It all works but when it display's up it wont default to top left of screen Rather it pops up in the middle Center screen (slightly to one side) which is obviously annoying when trying to get frame data while playing, the odd thing is when I plug a mouse in or enable the in built mouse button on OneXplayer the gamescope always defaults to top left and then if I leave mouse still for say 2-4 secs the overlay will return to Center Screen..

feels like maybe DPI or resolution issue due to OneXplayer screen being portrait..

Not sure TBH Need help... i can provide screens if it will help

Thanks

**Comment by pastaq** [comment]
This is a known issue with left rotated displays. A bug report has been submitted to mangohud and we're waiting on a resolution.

**Comment by Insta-Dead** [comment]
Thanks for the Hasty Reply...
ok yeah good to know so next update may have a fix? also will I have to re-flash OS, Confirmed in holo iso the issue is not present but holo iso lacks a lot of support for oneXplayer e.g. left orange display switch button isn't converted into steam button.. that's why I'm here on Chimera which I prefer, just want this gamescope to work As indented, if anyone does have quick fix to this known issue I'm all ear's... otherwise happy to wait for resolution

**Comment by pastaq** [comment]
https://github.com/ChimeraOS/gamescope-session/blob/b33ae30a470bb7c5ce025b4ae2cba5ae8fe01a4a/usr/share/gamescope-session/gamescope-session-script#L13

**Comment by pastaq** [comment]
> ok so I know its known issue but I did some digging to try find a temp solution Found this Vid: https://www.youtube.com/watch?v=bNf2VIq4od8
> 
> where about is the config file if any... I would love to just Force it to bottom right If possible, any help be much appreciated since I'm very new to Chimera OS...
> 
> Thanks Again

If you'd like to test a fix, try running these commands in a terminal. This will not hold through the next version update s o you'll need to run it again  later.

```
sudo frzr-unlock
sudo pacman -S base-devel
mkdir mango && cd mango
curl -o PKGBUILD https://raw.githubusercontent.com/ChimeraOS/chimeraos/fix-mangoapp/pkgs/50-mangohud/PKGBUILD
curl -o resolution.patch https://raw.githubusercontent.com/ChimeraOS/chimeraos/fix-mangoapp/pkgs/50-mangohud/resolution.patch
makepkg -si
```

**Comment by Insta-Dead** [comment]
You Legend 10/10 fixed it... all working as intended now... about entering into terminal to save some time next update, Is it possible to paste Code in I have tried SHIFT+INSERT or CTRL+SHIFT+INSERT and few others but no luck...

Thanks for the help **pastaq** 

p.s tried to do it on console in desktop mode due to Easy Paste ability but it lacked sudo permissions I believe...

**Comment by Insta-Dead** [comment]
Keen to Donate to such a kind soul I see your very well loved by this community cheers for all the help

**Comment by pastaq** [comment]
> about entering into terminal to save some time next update, Is it possible to paste Code in I have tried SHIFT+INSERT or CTRL+SHIFT+INSERT and few others but no luck...

Ctrl+shift+v for pasting into terminals
