### ISSUE TITLE
Possible OpenGamepadUI integration?

### ISSUE THREAD

**Issue by Gamecubert** [ChimeraOS/chimeraos#543]
Would it be possible to have a version or session of chimeraos that runs opengamepadui. I understand that it is extremely early in development but for users who don't dominantly use steam it might be nice to have. It would also keep the project more open source. I understand that it may be difficult but with SDL2 gamepad support out of the box it could be a really good replacement for deckui and help differentiate steamos 3 from chimeraos in the future. If we had someone who could design a custom add-on or two for the UI I think chimeraos could have its own unique look. This is what I'm referring [to](https://github.com/ShadowBlip/OpenGamepadUI)

**Comment by Gamecubert** [comment]
I also couldn't help but notice @pastaq is already familiar with this project, particularly on the session side of things.

**Comment by pastaq** [comment]
Testing for this won't start until after v40 is released.

**Comment by Gamecubert** [comment]
Good to know. I can't wait to see your work in action on chimeraos. Should I leave this open till its implemented or close the issue? I'm kinda new to github.
