### ISSUE TITLE
chimeraos-2023.02.15-x86_64 + Atari VCS = mount: /new_root: mount(2) system call failed: No such file or directory

### ISSUE THREAD

**Issue by daniellasalle** [ChimeraOS/chimeraos#546]
So I have finally moved forward with installing ```chimeraos-2023.02.15-x86_64.iso``` on my Atari VCS and even though the whole install process went perfectly fine that the system is unbootable. See the following:

![IMG_20230326_202955_972](https://user-images.githubusercontent.com/26171838/228361317-b503b62a-ce3b-40c6-b4f7-6206c027f853.jpg)
![IMG_20230326_203048_466](https://user-images.githubusercontent.com/26171838/228361322-43317283-e90f-4876-9931-9ff0aaf4deb1.jpg)

At this point I have no idea what I should do next. Ideas on how to fix this?

**Comment by alkazar** [comment]
Did you disable secure boot in the BIOS?

Another possibility is that the installation somehow failed. Perhaps try again.

**Comment by Samsagax** [comment]
@daniellasalle did you have any news on this issue?

**Comment by daniellasalle** [comment]
Thanks for your follow-up.

I did not tried anything else mostly because of the device having turned rogue (can't change BIOS configs using latest).

I have also seen that you guys also pushed *2* updates therefore I would like to think the next time I'll try will work.

As of right now we can just cancel this and I'll reopen using current input if needed.

Cheers,




Jul 4, 2023, 08:30 by ***@***.***:
