### ISSUE TITLE
Sackboy and Gamescope/Manjaro

### ISSUE THREAD

**Issue by Mohandevir** [ChimeraOS/chimeraos#553]
I would have posted this issue in the Gamescope-Plus page, but I can't find the issue tab...

I just installed Gamescope-session with Gamescope-plus on my Manjaro rig (AMD Ryzen 5 3600 & RX 6500 XT) and it's really doing a great job. Thanks for that.

The problem is when I launch Sackboy: A Big adventure... I don't know why, when in Gamescope-session, player one is stuck on keyboard input only. There is no way I can change that. I tried changing input controls in-game, but the "=" button is grayed out in the system options and nothing works. I also tried disabling steam-input, but it's a no-go too. Googling this issue doesn't reveal lots of useful informations, aside from the fact that it's supposed to be a solved issue in the latest Sackboy update... It feels like an edge case issue... I'm at a loss.

When I switch to desktop with BPM, it just works (keyboard and controller are available for P1)... So it seems something is wrong with Gamescope-session. For the record, I tried on my Steam Deck and it runs fine. I tried ChimeraOS on my PC and it runs fine too. I tried Holoiso... The problem is back. Quite weird... I would have kept ChimeraOS, but I need access to Dolphin-Emu's per game controllers configurations (could you add a Dolphin shortcut in the Steam library, like Emudeck does? That would be another way to solve my problem).

Thanks anyway!

**Comment by ruineka** [comment]
Add `SteamDeck=0 %command%` to the launch parameters for the game.

**Comment by Mohandevir** [comment]
Aaaaah! Thank you! Problem solved!
