### ISSUE TITLE
Desktop Orientation on AYANEO Geek

### ISSUE THREAD

**Issue by K3YNE** [ChimeraOS/chimeraos#557]
On the low-end SKU (512GB - 800p Display) of the AYANEO Geek, the desktop mode cannot be rotated. Have tried all orientations/available resolutions.

**Comment by pastaq** [comment]
For a kernel quirk, this is somewhat more challenging as both the 800p and 1200p have the same DMI data.

**Comment by K3YNE** [comment]
I see, the weird thing is not even resolutions change

**Comment by K3YNE** [comment]
Closed by accident

**Comment by ruineka** [comment]
> For a kernel quirk, this is somewhat more challenging as both the 800p and 1200p have the same DMI data.
The resolution is all I need to pull to apply rotation quirks.

**Comment by K3YNE** [comment]
It's 1200x800p

**Comment by skill83** [comment]
I can confirm the issue

**Comment by pastaq** [comment]
> > For a kernel quirk, this is somewhat more challenging as both the 800p and 1200p have the same DMI data.
> 
> The resolution is all I need to pull to apply rotation quirks.

Apply, sure, but we still need to identify pretty device. The geek has two models, one with an 800p screen and one with the same 1200p screen as the 2.
