### ISSUE TITLE
GPDWIN4 Volume Keys no function

### ISSUE THREAD

**Issue by Nik123456789010** [ChimeraOS/chimeraos#558]
Had a good start with my arrived GPD Win4 and Chimera OS. But there is no reaction at the + - volume keys.

**Comment by Nik123456789010** [comment]
Oh OK. Thank you! I wonder if this is also a problem in they're Manjaro Version. I will download and try it out.

**Comment by phyerbarte** [comment]
Latest bios of win4 seems fix that, anyone tried it ?

**Comment by aarron-lee** [comment]
Works fine on bios v3.06, can confirm that it works fine on my Win 4.
