### ISSUE TITLE
ONEXPLAYER Mini Pro - sh: can´t access tty: job control turned off

### ISSUE THREAD

**Issue by BluesBrothers7** [ChimeraOS/chimeraos#559]
OneXPlayer Mini Pro - AMD 6800U

During the installation process, waiting for the installation device 30 seconds failed (did not show up after 30 seconds):
"Falling back to interactive promt" ...

" sh: can´t access tty: job control turned off"

after that i am in root.

**Comment by ruineka** [comment]
The installer fails? Are you using ventoy? If so you need to update your flash drive.

**Comment by BluesBrothers7** [comment]
i flashed with balena echter and an other USB Stick with Gnome Multiwriter. In addition external SSD Drives are not recognized as a Drive. Do you have any other hint for me, please? Thanks a lot!  04.04.2023, 01:17, "ruineka" ***@***.***>: The installer fails? Are you using ventoy? If so you need to update your flash drive.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by BluesBrothers7** [comment]
solved

**Comment by pastaq** [comment]
What was the solution in case this comes up for someone else?

**Comment by BluesBrothers7** [comment]
i used the same USB Stick, but an older version (January 2023) of ChimeraOS. That worked for me. 08.04.2023, 20:57, "Derek J. Clark" ***@***.***>: What was the solution in case this comes up for someone else?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
