### ISSUE TITLE
OneXPlayer Mini Pro - AMD 6800U -  Controller issues analog sticks

### ISSUE THREAD

**Issue by BluesBrothers7** [ChimeraOS/chimeraos#571]
I am not able to calibrate analog sticks on my OneXPlayer Mini Pro - AMD 6800U. When i try to calibrate the analog sticks on the left side, direction left is recognized, but the other directions aren´t recognized. On the right analog tick all directions aren´t recognized.

DPAD and Y, X, A, B are working correctly.

ChimeraOS 41 (2023-03-30)

**Comment by pastaq** [comment]
What are you using to calibrate the joysticks?

**Comment by BluesBrothers7** [comment]
I used "Contoller", Device Test, Start Test, "Geräteeingaben einrichten" (i don´t know what is this called in English / "configure device input"?)  08.04.2023, 20:56, "Derek J. Clark" ***@***.***>: What are you using to calibrate the joysticks?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by pastaq** [comment]
I need more information. Is this a command line tool or a GUI tool? Does it come with ChimeraOS or did you install it yourself?

**Comment by BluesBrothers7** [comment]
It is all in ChimeraOS. Accessible over "Settings". --»   "Contoller", "Device Test", "Start Test", "Geräteeingaben einrichten" (i don´t know what is this called in English / "configure device input"?) - then i tried to configure the onexplayer onboard controller.

I can provide you with a screenshot or a video if it would be helpful.

Thank you so much for your support!

**Comment by BluesBrothers7** [comment]
I made 3 short videos to show the problems i am facing and uploaded it here: 
https://ufile.io/f/9xrwg

Thanks a lot!

**Comment by BluesBrothers7** [comment]
I fixed it via Windows with OXP Game Center. 
https://www.youtube.com/watch?v=Or_k1Z53mXE

This ticket can be closed. Thanks!
