### ISSUE TITLE
Volume on the Aya Neo 2 is low

### ISSUE THREAD

**Issue by TAGE7** [ChimeraOS/chimeraos#572]
Hi there, 

As mentioned on discord, I've tested the AN2 on windows and noted the max volume on Chimera v41/42 is about 50% of the actual volume of the speakers.

About 7db difference compared to max volume on Windows.
I found a work around using the PulseAudio app, however I was asked to report the issue here.

I found that 153% volume boost via Pulse Audio is close to the same db reading as the native device in Windows.

**Comment by THFourteen** [comment]
Can confirm I have this issue on the Aya Neo Air Plus too

**Comment by dctr** [comment]
@TAGE7 for me on v42, there was a virtual audio device selected by default. if I go to audio settings, I can choose the actual audio device, and from there on it will be selected by default. and volume is normal.

the issue to me just seems that the default audio device it not detected correctly.

**Comment by Samsagax** [comment]
Closing as it is a device selection issue on the Steam client.
