### ISSUE TITLE
Aya Neo 2 headphone jack doesn't work when in ChimeraOS

### ISSUE THREAD

**Issue by TAGE7** [ChimeraOS/chimeraos#574]
Hi there,

Just follownig up to report that the AN2 headphone jack doesn't work as normal when in ChimeraOS v41
It seems maybe the audio is transmitting through the jack but not in the correct pinout?

If you put the headphones in half way there's audible audio but when the connector is fully seated you get almost no audio

**Comment by TAGE7** [comment]
@ruineka

**Comment by TAGE7** [comment]
[misclick](url)

@ruineka as requested
attached 


Headphone Jack at half way point where audio comes through
[half-jack-pwdump2.txt](https://github.com/ChimeraOS/chimeraos/files/11196708/half-jack-pwdump2.txt)

Headphone jack fully seated
[full-jack-pwdump2.txt](https://github.com/ChimeraOS/chimeraos/files/11196709/full-jack-pwdump2.txt)

Keep in mind however, that when it's half seated audio still comes out of the speakers so it may just be a not part of the issue...? idk

**Comment by Mazztwo** [comment]
Reproducing on Ayaneo 2

**Comment by ruineka** [comment]
Is this still an issue with v43 unstable? @pastaq  @alkazar 

I don't have the Aya Neo 2 to try and replicate.

**Comment by pastaq** [comment]
I don't have wired headphones lol

**Comment by Samsagax** [comment]
Does it still happen on the latest testing image?

**Comment by dctr** [comment]
Happening for me too, Anayeo 2 with v42. Plugging in headphones I can't hear any audio.

**Comment by Samsagax** [comment]
Please, could any of you try again in latest stable? Should be 43-1.

**Comment by ruineka** [comment]
> Please, could any of you try again in latest stable? Should be 43-1.

I think either Pastaq or Alkazar needs to use HDA analyze and check what happens when plugging in headphones. I would do this but I can't. The pin layout must be getting set incorrectly when fully inserted and when halfway the switch isn't activated.

**Comment by ruineka** [comment]
These devices likely need a quirk similar to the Asus Ally.

**Comment by ruineka** [comment]
I go a fix for the Aya Geek. I can't confirm the nuances for the Aya Neo 2, but the fix is likely to be similar.

https://github.com/ChimeraOS/linux-chimeraos/pull/17

**Comment by ruineka** [comment]
I got a build up for testing can anyone try the latest unstable?

**Comment by alkazar** [comment]
Yup, latest unstable fixes the headphones. Nice job!

**Comment by Samsagax** [comment]
Closing as completed
