### ISSUE TITLE
Black Screen after installing ChimeraOS

### ISSUE THREAD

**Issue by Clutterfox96** [ChimeraOS/chimeraos#584]
Installing ChimeraOS works fine but upon reboot I only get an infinite black screen and nothing happens. 
I am using an Intel i3-4130 with secure boot and csm disabled. 
what I have tried: 
- Rebooting
- Removing the install USB 
- Disabling CSM 
- Trying a different monitor with 1080p 60fps instead of my main 4K one

Any ideas how to fix this?

**Comment by Clutterfox96** [comment]
![image](https://user-images.githubusercontent.com/96124427/232020826-94a17527-f345-4d16-b66b-fe63bd55e65a.jpg)

**Comment by alkazar** [comment]
It looks like your GPU does not support the necessary Vulkan features. What GPU is it?

**Comment by alkazar** [comment]
Yeah, that is definitely not supported. Sorry.
The requirements listed on the website call for GTX 1000 series or newer.
