### ISSUE TITLE
Aya Neo 2 Minimum brightness is still too high

### ISSUE THREAD

**Issue by TAGE7** [ChimeraOS/chimeraos#586]
Hi, as written the minimum brightness of the AN2 is still too high compared to the lowest value in windows.

Hasn't just been reported by me, but others who have come from windows have noticed it as well.
This ofc impacts battery life.

**Comment by ruineka** [comment]
Does desktop mode allow you to lower the brightness more than game mode?

**Comment by TAGE7** [comment]
Doing some AB testing it looks exactly the same.
The brightness setting from game mode transfered directly to desktop mode

Also, looking at the steam console, the brightness slider outputs the following:
(from highest brightness on the slider, to the lowest on the slider.

![brightness](https://user-images.githubusercontent.com/3936755/232232829-f130bb69-9b24-417e-a13e-6f9158275832.jpg)

It doesn't seem to go to 1 or to 0 in the setting + the error you can see.
