### ISSUE TITLE
Name conflict with chimera linux upcoming

### ISSUE THREAD

**Issue by okkiv** [ChimeraOS/chimeraos#593]
Hey guys,

just a heads up, that there seems to be some shiny new linux distro on the horizon named "Chimera Linux"

https://chimera-linux.org/
https://github.com/chimera-linux

**Comment by classabbyamp** [comment]
chimera linux has existed for almost 2 years:

- https://chimera-linux.org/docs/history
- https://chimera-linux.org/docs/faq#what-about-chimeraos

**Comment by okkiv** [comment]
> chimera linux has existed for almost 2 years:
> 
>     * https://chimera-linux.org/docs/history
> 
>     * https://chimera-linux.org/docs/faq#what-about-chimeraos

True. My bad. I just found out about it in an article
