### ISSUE TITLE
Add ModemManager package to build for 4G Modems

### ISSUE THREAD

**Issue by PhoenixMage** [ChimeraOS/chimeraos#597]
A number of consoles are shipping with internal and/or USB 4G LTM modems.

Adding the ModemManager package will allow Chimera to use 4G when not connected to wifi.

I have personally tested this on a GPD Win 4 with USB 4G by running:
```
sudo frzr-unlock
sudo rm -fr /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -S archlinux-keyring
sudo pacman -S modemmanager
```

A new setting becomes available on the desktop settings to enable Mobile Internet and configure APN if necessary.

**Comment by Samsagax** [comment]
https://wiki.archlinux.org/title/NetworkManager#Mobile_broadband_support Seems simple enough and it integrates nicely into NetworkManager
