### ISSUE TITLE
Add Distrobox

### ISSUE THREAD

**Issue by tfranken90** [ChimeraOS/chimeraos#603]
Distrobox is extremely useful on chimeraOS, giving access to virtually any distributed package. It would be very nice to have it included in the base installation.

**Comment by Samsagax** [comment]
What would be the usecase for this addition?

**Comment by tfranken90** [comment]
There are just endless potential usecases. Distrobox provides containerized environments for a number of linux distributions (fedora, arch, debian, etc). Within those environments you can install  and run any package from those distributions, including GUI applications. Applications can then be exported to desktop files, added to steam, and launched from the steam deck ui. There are plenty of apps available on flathub, but having access to the distribution repositories adds a significant amount of unavailable packages (including lots of games). There are also lots of utilities that make interacting with Chimera over ssh a lot easier, like tmux. The ability to launch a terminal in gaming mode then connect to it from another computer on my network and launch youtube videos or play music is just super convenient. I basically have Fedora launcher inside gaming mode which starts gnome console running a fedora container, from there I can launch just about anything I can install, including minimal desktop environments like sway. There's definitely a lot of potential.

**Comment by Samsagax** [comment]
We include podman for container integration. But the argument of "unlimited potential and use cases" is not enough for the goals of the project. We strive to have a console experience and we obviously can't fulfill all the power user's requests for special cases.
For a full fledged distribution as you seem to want you are better off installing ArchLinux with the same configuration we do (all our packages ar public and are available in the AUR).

Closing as won't fix.

**Comment by tfranken90** [comment]
@Samsagax Seems odd to me to include podman without toolbox or distrobox, but regardless, it's easy enough to install manually for anyone who is interested.
