### ISSUE TITLE
Performance Overlay slider does not turn on

### ISSUE THREAD

**Issue by jerw84** [ChimeraOS/chimeraos#607]
On ChimeraOS 41. 12700k/RX6800. Trying to turn on the performance overlay option but the slider doesn't toggle at all.

**Comment by ruineka** [comment]
I wonder if this is related. https://github.com/ValveSoftware/gamescope/issues/107#issuecomment-1527799883

**Comment by jerw84** [comment]
Tried to run` sudo setcap 'CAP_SYS_NICE=eip' /usr/bin/gamescope ` but it says read-only file system.

**Comment by ruineka** [comment]
> Tried to run` sudo setcap 'CAP_SYS_NICE=eip' /usr/bin/gamescope ` but it says read-only file system. 

run `sudo frzr-unlock` first.

**Comment by jerw84** [comment]
Ran it, then ran the other command. Still not working :(

**Comment by ruineka** [comment]
> Ran it, then ran the other command. Still not working :(

Can you attach your `mangoapp-stdout.log` that should be located in your home folder? I think i finally was able to replicate your issue on an HP Dev One, but I'm running EndeavourOS on this.

**Comment by jerw84** [comment]
Let me see. This is going to sound super silly but is MangoHud something that I have to install after installing ChimeraOS as a third-party addon? I looked into installing it and I am stuck on the meson.build part as it says command not found when I followed the instructions on their github page.

**Comment by ruineka** [comment]
> Let me see. This is going to sound super silly but is MangoHud something that I have to install after installing ChimeraOS as a third-party addon? I looked into installing it and I am stuck on the meson.build part as it says command not found when I followed the instructions on their github page. 

It comes preinstalled and should be working out of the box.

**Comment by jerw84** [comment]
hmmm in that case I don't see the file you're looking for. I only see the standard Desktop, Documents, Downloads, etc folders. Unless it's hidden by default?

**Comment by ruineka** [comment]
> hmmm in that case I don't see the file you're looking for. I only see the standard Desktop, Documents, Downloads, etc folders. Unless it's hidden by default?
> 

You might need to press CTRL + H to show hidden files.

**Comment by jerw84** [comment]
Ah-ha! Here you go!

[2023-04-29 17:19:11.682] [info] [config.cpp:123] parsing config: '/tmp/mangohud.P51lC6xe'
[2023-04-29 17:19:11.696] [info] [overlay.cpp:800] Uploading is disabled (permit_upload = 0)
[2023-04-29 17:19:14.199] [info] [config.cpp:123] parsing config: '/tmp/mangohud.P51lC6xe'
[2023-04-29 17:19:14.199] [error] [overlay_params.cpp:715] Unknown option 'nis_steam_sharpness'

**Comment by Samsagax** [comment]
Are you using upscaling set to NIS? What happens if you turn off upscaling and restart the session?

**Comment by jerw84** [comment]
I don’t think so. NIS is for AMD cards too? I’m using rx 6800 and I didn’t do anything else for settings.

**Comment by Samsagax** [comment]
Check in the QAM for upscaling options. What do you see there?

**Comment by jerw84** [comment]
Sorry, I'm not sure how to do that. I googled QAM upscaling chimeraOS and zero search matches came up haha. One interesting thing though. I installed HoloISO on the same system just to see and gamescope worked...for 720p in HZD. It then locked my resolution to that. It stopped worked once I changed the resolution to 1440p. Weird.

**Comment by jerw84** [comment]
Good news! I reinstalled chimeraOS and gamescope seems to be working fine now. However I am locked in to 720p even though my native display is 1440p.

**Comment by pastaq** [comment]
To change the default resolution you need a custom gamescope command. I'm working on editing the wiki article to make this easier.

**Comment by ruineka** [comment]
> Good news! I reinstalled chimeraOS and gamescope seems to be working fine now. However I am locked in to 720p even though my native display is 1440p.

Are we talking about the games are 720P? You need to set your display resolution for each game in the game settings, that's a Steam thing unfortunately.

**Comment by jerw84** [comment]
Yea, the options to change the game resolution beyond 720p is locked when I try to change them in the game.

**Comment by pastaq** [comment]
> Yea, the options to change the game resolution beyond 720p is locked when I try to change them in the game.

Ah, you need to open the gear icon in the steam library entry for each game. Valve hasn't provided a way to do a global override yet, unfortunately.

**Comment by jerw84** [comment]
Ok, I didn't know you had to change the game resolution outside of the game in steam's client. Now it is running at 1440p as expected. Gamescope also works too. Very strange that it took reinstalling the OS to fix the issue. I wish I could replicate this bug for you guys. Gamescope still reads 720p at the bottom, that's nothing to worry about I assume?

**Comment by Samsagax** [comment]
> Gamescope still reads 720p at the bottom, that's nothing to worry about I assume?

This is a known MangoHud issue. It is now fixed for the upcomming v43 release. I'm  closing this one as completed. Thanks for your feedback.
