### ISSUE TITLE
Add ability to ignore or hide automatic collections

### ISSUE THREAD

**Issue by maddox** [ChimeraOS/chimeraos#608]
ChimeraOS automatically adds the "ChimeraOS Playable" and "ChimeraOS Verified" collections. Despite deleting them, they show back up on the next Steam restart.

It would be helpful to have the ability to remove these completely. I appreciate and understand why they're there, but I personally have no need for them nor want them in my list of collections.

If this should be opened on chimeraos/chimera I'll move it there, thanks!

**Comment by Samsagax** [comment]
Please move this to the chimera app repo as it is handled there
