### ISSUE TITLE
Game scope segfault

### ISSUE THREAD

**Issue by wachuwamekil** [ChimeraOS/chimeraos#609]
Version: ChimeraOS 42 (2d48971)

Issue: When launching into “game mode” gnome segfaults and reboots into desktop.  Good news in desktop is rotation is correct!  When clicking “game mode” icon same behavior.

In 41 it loads into gamescope but rotation is messed up.

Expected behavior: game scope should launch successfully at first boot, and when clicking game mode icon.

LMK what info or logs you need.

**Comment by ruineka** [comment]
Can you get me a gamescope log? It should be a hidden file in your home folder. I suspect you are having issues we've been seeing with other devices such as the Aya Air Pro, Aya Geek, etc.

**Comment by pastaq** [comment]
What hardware do you have? If it is a specific handheld the model will do, and any variant specifics (I.E. AYANEO GEEK 800p)

**Comment by wachuwamekil** [comment]
I deployed the most recent testing build and it is working as expected.  We can close this one as a fluke maybe.  I was using a pre-created iso so not sure what branch it was coming from.  

working as expected on build 8971.  Will keep open until I can upgrade to 1fb4.

**Comment by ruineka** [comment]
> I deployed the most recent testing build and it is working as expected.  We can close this one as a fluke maybe.  I was using a pre-created iso so not sure what branch it was coming from.  
> 
> working as expected on build 8971.  Will keep open until I can upgrade to 1fb4.

Not a fluke and yes I got it working, but I need to figure out a proper long term fix later.
