### ISSUE TITLE
SD Card not showing in Gamepad UI settings after formatting with Chimera App

### ISSUE THREAD

**Issue by wachuwamekil** [ChimeraOS/chimeraos#611]
Build: 4728e72
Device: Intel HD615/GPD Win2
Bios: 2.13
Problem:  After formatting an SD card on the Win2, and rebooting system the SD card does not show up in the GamepadUI under "settings".  Unable to install a game from within GameMode to this drive.

Troubleshooting:
SD card (8GB) shows as successfully formatted in the Chimera OS web app.  
lsblk command shows that the card is mounted to the /run/media/gamer/{GUID} dir
Navigating to the path shows that there is a steamapps directory structure on the sdcard
Reviewing Journelctl I can see that the device is mounted, and system thinks all is well.

**Comment by pastaq** [comment]
I have done some work to fix this recently. Can you see if this issue persists on the testing channel?
`sudo frzr-deploy chimeraos/chimeraos:testing`
