### ISSUE TITLE
MangoHud configuration ignored for steam applications

### ISSUE THREAD

**Issue by JimMadge** [ChimeraOS/chimeraos#614]
I'm finding that the MangoHud configuration (at `/home/gamer/.config/MangoHud/MangoHud.conf`) is ignored for applications launched through steam, but not otherwise.

If I launch a game using mangohud, I can toggle the display using the _MangoHud default_ key combination "Shift_R+F12". The _MangoHud default_ overlay is then shown. This is irrespective of the settings in `/home/gamer/.config/MangoHud/MangoHud.conf`. For example, the _ChimeraOS default_ toggle key bind "F3".

However, if I "Switch to Desktop", open an terminal and run `mangohud vkgears` then the hud is displayed according to the configuration in `/home/gamer/.config/MangoHud/MangoHud.conf` as I would expect.

Also, possibly unrelated.
MangoHud doesn't seem to run without setting `mangohud %command%` in launch options.

OS Version: 1
OS Build: 453df5f

**Comment by alkazar** [comment]
This is probably an issue you need to bring up with Valve and Steam. The Steam client generates the Mangohud configuration and I am not sure you can modify it.

Try searching for or creating an issue here:
https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by JimMadge** [comment]
An update,

With the launch options
`MANGOHUD_CONFIGFILE=/home/game/.config/MangoHud/MangoHud.conf mangohud %command%` it works as expected.

(Presumably overriding what has been set elsewhere)

I'm not sure if exporting `MANGOHUD_CONFIGFILE` in [https://github.com/Samsagax/steamos-compositor-plus/blob/master/usr/bin/steamos-session](steamos-session) would help (as the config was set there previously). I will try that.
