### ISSUE TITLE
GPD Win 4 Stutter with 60hz

### ISSUE THREAD

**Issue by Nik123456789010** [ChimeraOS/chimeraos#620]
Thank you for supporting the GPD Win 4 in experimental. Maybe you see this: https://www.reddit.com/r/gpdwin/comments/12xb363/gpd_win_4_stutter_for_all_units/

Maybe you want/can add a fix in the next releases. Thank you and br

Nik

**Comment by pastaq** [comment]
The latest BIOS release enables flashing the screen firmware.

**Comment by Nik123456789010** [comment]
Yes, it’s a Windows Tool for the IC Update itself, have worked for me under Windows to go. Thank you!
