### ISSUE TITLE
Gamepadui-with-qam hangs when switching to desktop

### ISSUE THREAD

**Issue by ibanezbass** [ChimeraOS/chimeraos#621]
Using an Intel OneXPlayer, gamepadui-with-qam hangs at "Switching to Desktop". Works fine when using gamepadui without qam.

**Comment by pastaq** [comment]
Hey to a TTY and update the package manually
```sudo frzr-unlock
sudo pikaur -Sy opengamepadui-bin
reboot```

**Comment by ibanezbass** [comment]
Confirmed that this fixes it. Sorry for the delay.
