### ISSUE TITLE
NVIDIA Flickering

### ISSUE THREAD

**Issue by reboun** [ChimeraOS/chimeraos#623]
I cannot play a game because it looks like this: 
![IMG20230521111739](https://github.com/ChimeraOS/chimeraos/assets/124934245/d574ed60-d3d7-4b7b-b5be-f6aea171a3b6)
GPU: NVIDIA RTX 2060

**Comment by rfrayer420** [comment]
Same issue with GTX 1080 and Xeon-1230

**Comment by reboun** [comment]
> Same issue with GTX 1080 and Xeon-1230

I fixed it. `sudo pacman -S gamescope`. It will ask if you want to replace `gamescope-plus`, just accept it.

**Comment by Samsagax** [comment]
@reboun can you test if installing gamescope-git from the AUR also solves your problem?

**Comment by reboun** [comment]
> @reboun can you test if installing gamescope-git from the AUR also solves your problem?

I don't really want to break things by trying it.
