### ISSUE TITLE
No AMD driver loaded

### ISSUE THREAD

**Issue by pimboli** [ChimeraOS/chimeraos#634]
Hi, on my system with a 7900 I only see mesa driver and the FPS are horrible low.
I guess this is because no amd pro drivers are loaded?

How can I activate/load them in chimeraos?

Thanks

**Comment by pastaq** [comment]
The AMDGPU driver is built into the kernel. What CPU do you have? If it has an iGPU it might be using that instead.

**Comment by pimboli** [comment]
Hi,

Just solved my problem.
I use a riser card wich was incompatible with pcie gen4.
After setting pcie to gen3 in bios all works fine.

I thought the open source drivers amd gpu would not be good enough and that I would need the closed source version.
