### ISSUE TITLE
Gamepadui resolution and refresh issues

### ISSUE THREAD

**Issue by enterra2010** [ChimeraOS/chimeraos#638]
Running ChimeraOS on my custom desktop for gaming on my 4k TV.

I find that certain games (Plague Tale Innocence, Diablo II: Res, etc.) will not allow me to change the resolution in the properties of the game while in gamepadUI. If I do, the game will crash and often, the whole system crashes as well. I also find that no games will recognize my 120Hz display and remains at 60Hz.

Mind you, all of this works perfectly fine in desktop mode.... although thats not optimal for a living room setup.

I saw in a previous issue that you could modify the compositor config to resolve but I also saw that that was for the previous big picture mode and it doesn't work with GamepadUI.

Go easy on me.... Linux and Github newb, here. I'm happy to provide anything needed! Just let me know!

**Comment by enterra2010** [comment]
System Specs:
5900x
RX 7900 XTX
32GB DDR4 3600

**Comment by pastaq** [comment]
There's an option in the game settings for resolution, have you tried setting that?
