### ISSUE TITLE
AYANEO Air Pro - Missing right channel audio with aya-air-audio scipt - with fix!

### ISSUE THREAD

**Issue by scapeghost** [ChimeraOS/chimeraos#650]
I've got an AYANEO Air Pro 5825U with the audio phase issue (one internal speaker's polarity is wrong from the factory). This can be tested with [this youtube video](https://www.youtube.com/watch?v=kUT6ZhFdLkA), for example. I tried enabling the device-quirks script **aya-air-audio.service** in ChimeraOS 42 with the command `systemctl --user enable --now aya-air-audio.service` and found that right-channel audio wasn't playing on my device, only left (or left-channel playing from both speakers). After some troubleshooting, I fixed the issue by editing /etc/device-quirks/scripts/ayaneo/air/audio-phase-fix and altering the 3rd line from:

`    pactl load-module module-ladspa-sink sink_name=ladspa_out sink_master=$master plugin=inv_1429 label=inv`

to:

`    pactl load-module module-ladspa-sink sink_name=ladspa_out sink_master=$master plugin=inv_1429 label=inv channel_map=front-right`

adding `channel_map=front-right` to the end of the line. It seems like without this parameter, the sink defaults to the left channel, causing the script to create two left channels.

I confirmed proper left/right audio and phase after applying this quick fix. The file must be edited as su of course, and requires either a reboot to take effect, or you can run the command `/etc/device-quirks/scripts/ayaneo/air/audio-phase-fix restart` from the console.

**Comment by pastaq** [comment]
Cool, can you PR your changes to this repo? https://github.com/ChimeraOS/device-quirks

**Comment by scapeghost** [comment]
Added PR https://github.com/ChimeraOS/device-quirks/pull/53 ... hoping I did that correctly!

**Comment by pastaq** [comment]
Thanks for your contribution!
