### ISSUE TITLE
Black Screen on ASUS ROG STRIX B550-F Gaming

### ISSUE THREAD

**Issue by grayhax** [ChimeraOS/chimeraos#656]
ChimeraOS installs just fine but when I boot into the installed version of ChimeraOS, It just goes to a black screen and nothing happens.

**Comment by ruineka** [comment]
What are your complete specs?

**Comment by grayhax** [comment]
I have an AMD Ryzen 5 5600x 6 core, AMD Radeon HD 3870, 16 GB of ram, x64, 512 GB M.2 SSD and the ChimeraOS install is located at the 256 gb inland regular ssd.

**Comment by ruineka** [comment]
> I have an AMD Ryzen 5 5600x 6 core, AMD Radeon HD 3870, 16 GB of ram, x64, 512 GB M.2 SSD and the ChimeraOS install is located at the 256 gb inland regular ssd.

I'm not sure that GPU supports the vulkan extensions needed unfortunately.

**Comment by grayhax** [comment]
Oh. Alright then.
