### ISSUE TITLE
For the love of god git rid of gnome

### ISSUE THREAD

**Issue by bluedinosaur139** [ChimeraOS/chimeraos#660]
and please just use kde plasma like every other sensible build. The desktop is so bare it is worthless and just wastes data.

**Comment by bluedinosaur139** [comment]
or be smart enough to offer choices at time of download or something, no one likes being forced to have a shitty desktop.

**Comment by npaladin2000** [comment]
I agree, the desktop is there BECAUSE it's bare. It's there because some functions require a desktop in order to happen and that's it.  If you're using it that often then you're really not using the distro for it's intended purpose.

**Comment by SirKiren** [comment]
With the state of Wayland support, Gnome and KDE are the most viable choices. While I don't personally care for Gnome for general use, it has some advantages for touch based devices several of which are likely to be used with ChimeraOS. 

For all devices it is adequate for it's purpose as a secondary interface for things which can't be done from the default gaming interface.

**Comment by bluedinosaur139** [comment]
ok let me be a little nicer then, it is an amazing os that could be a daily
driver if only you allowed it to be, you can still act like a control freak
in chimeraos, but it literally is not hard at all to offer an option for a
different DE, you just decided forcing people to do it your way was the way
to go. Just fork that distro and git rid of gnome alltogether and put kde
back where it belongs

**Comment by Samsagax** [comment]
> ok let me be a little nicer then, it is an amazing os that could be a daily driver if only you allowed it to be, you can still act like a control freak in chimeraos, but it literally is not hard at all to offer an option for a different DE, you just decided forcing people to do it your way was the way to go. Just fork that distro and git rid of gnome alltogether and put kde back where it belongs

Is nice when you answer your own questions.

ChimeraOS is not intended to be a general purpose distro. It may never be, and it won't in the foreseeable future. It is what it is a console distro. Anyway. The project is very easily forked. We even have a full wiki on how to do it. It is intended to be what you want to be. We even provide some of our packages in the AUR for building your own Arch distro if you want with the same functionality but less "constrained". I do use them in my general purpose machine. I don't have ChimeraOS on my general purpose machine, I have plain Arch and some of our packages installed for when I want to use gamescope-session.

Closing as the concern has been addressed.

**Comment by bluedinosaur139** [comment]
OK not gonna be happy until you make one for me, I want chimera of with KDE
and not immutable.  I realize it is easy to unlock and have already done so
as well as install KDE, but switching to KDE is a pain in the ass, I dare
you to do what I said and make it work. If you do I will wire you 100 use
with venmo AFTER I test it and it does what I want. Fine are you worth my
money?

**Comment by bluedinosaur139** [comment]
Chimera os*
Wire you*

**Comment by bluedinosaur139** [comment]
Wire you 100 usd*

**Comment by pastaq** [comment]
I already have $100 and you're not worth our time.
Here's the guide on how to fork: FITFO
https://github.com/ChimeraOS/chimeraos/wiki/Development#forking[FITFO](https://github.com/ChimeraOS/chimeraos/wiki/Development#forking) 
Have fun and go away.

**Comment by bluedinosaur139** [comment]
like i give a shit i already know how to log into windows and just because
i am better than you i will tell you for free
***@***.***
pass :fuckmicrosoft
this works during install for win 10/11
it will error then continue with install and make a local account

**Comment by 143mailliw** [comment]
I think if every single Linux distro except for ChimeraOS is broken on your computer, you probably have bigger issues than whether or not you're using Gnome or KDE.

**Comment by bluedinosaur139** [comment]
Tbh I think it's my mobo. Gigabyte h610m never buy budget

**Comment by bluedinosaur139** [comment]
manjaro fixed my issues, that and not even bothering with the gamescope-session-git trash you made
