### ISSUE TITLE
On-screen keyboard not opening on Ayaneo 2 using LC

### ISSUE THREAD

**Issue by dctr** [ChimeraOS/chimeraos#661]
To my understanding, on Ayaneo 2, the LC button should bring up the on-screen keyboard. (Looking at HandyGCCS confic, LC is mapped to OSK.) For me it does not bring it up though, neither in SteamUI nor in games, on ChimeraOS v42.

When tapping into the SteamUI search bar, and the OSK opens automatically, pressing LC does close it.

**Comment by alkazar** [comment]
On the Aya Neo 2, the RC button brings up the keyboard. However, this only works when in game.

**Comment by dctr** [comment]
my apologies @alkazar , I _did_ mean RC. LC is for the Chimera app, and that works as expected.

**Comment by Samsagax** [comment]
@dctr Does it work on current stable?

**Comment by dctr** [comment]
Yes, working now, thanks @Samsagax
