### ISSUE TITLE
Audio not working Asus Ally v43

### ISSUE THREAD

**Issue by zackmd1** [ChimeraOS/chimeraos#664]
Just installed ChimeraOS v43 (downloaded from main webpage) on to my Ally. Everything seems to be functioning except audio. Volume buttons do not work/change system setting. System identifies “Family 17h/19h HD Audio Controller” but again no audio. Any tips on how to fix? Mic seems to be functioning.

**Comment by pastaq** [comment]
You need to enable firmware overrides

https://github.com/ChimeraOS/chimeraos/wiki/General-Configuration#firmware-overrides
