### ISSUE TITLE
Add swap memory

### ISSUE THREAD

**Issue by gifter77** [ChimeraOS/chimeraos#668]
Some emulators such as Yuzu can be very memory heavy. Right now when running out of memory, ChimeraOS just locks up. Adding some swap memory could fix this issue. To avoid slowing down when RAM is still available, the swappiness value could be set to something very low.

For instance I was getting Yuzu constantly lock up on my Rog Ally with heavy games, which I fixed by adding a 16GB swap file.

**Comment by davralin** [comment]
Dupe: #473

**Comment by Samsagax** [comment]
Closing as duplicate
