### ISSUE TITLE
ROG Ally Suspend Issues

### ISSUE THREAD

**Issue by MrTripiode** [ChimeraOS/chimeraos#669]
When using the ROG Ally controls I got a noticeable delay between press and firmware seeing the press. Sometimes it even does not see it at all.

I’m using the latest version and I have firmware overrides enabled for audio

**Comment by pastaq** [comment]
What part of the controller, the normal gamepad buttons or the special face buttons?
Have you adjusted TDP at all?

**Comment by MrTripiode** [comment]
Every buttons seems affected by the issue. Just installed the OS logged into Steam and played a game.

tales of berseria to be exact but it happens on Steam too 

No others settings were changed

**Comment by pastaq** [comment]
Is it just the buttons that are lagging or are other elements of the UI slow?

**Comment by MrTripiode** [comment]
Only the buttons, the interface and touch screen does not seems to be affected

**Comment by kalanihelekunihi** [comment]
It would be useful setting up the utility jstest, as it will show you the inputs that the kernel sees, as it sees them.
If you then recorded video of testing, it would allow us to measure "button press -> action".

If you are not comfortable with the terminal, there are also GUI versions such as jstest-gtk

This test will give some useful data, validate your assumptions, and scope the problem as "issue exists within hardware -> kernel", or "issue exists in userland".

**Comment by MrTripiode** [comment]
Okay so i did some tests and the issue only append after suspend. Rebooting does not fix the issue but a full shutdown does. Issue is visible with jstest.

I saw from the website that system suspend is not supported on the ally so i can close the issue if you want.

I will disable suspend for now. 

I will try to make a video tomorrow

**Comment by pastaq** [comment]
You can keep it open, this is a new symptom for suspend. Before this it was only noted that the n-key device disappeared. I'll change the issue name and we can consolidate the suspend issues we discover here. Thanks

**Comment by stevemurr** [comment]
Hi, 

I also observed degraded joystick input after resume. [I created a video demonstrating this behavior](https://youtu.be/IppJsUPR3a0). Please let me know if you'd like me to run any other tests.

**Note**: I recorded the handheld using my phone so the joystick and screen were in view. Let me know if you have a preferred method for these kinds of recordings.

**Note**: As of 9:15 PST YouTube reports 40 mins until HD quality is available.

**Comment by felipejfc** [comment]
not a solution but meanwhile this is fixed in handycon you can try steam-patch https://github.com/Maclay74/steam-patch
it has another way of dealing with the keys that is not affected by this problem you're describing

**Comment by fkysly** [comment]
I have the same problem. everything work perfectly when boot on, but press the power button to suspend, then press to resume, Rog Ally's Main Button, Decky Button not working anymore, other Buttons like ABXY, has a delay.

[](https://cdn.discordapp.com/attachments/1118341089355636776/1140653914019078205/IMG_9572.mp4)

**Comment by pastaq** [comment]
Try updating HandyGCCS. I recently adjusted some latency related things and increased the process priority.

TBS this isn't inherently a HandyGCCS issue, but a suspend/disappearing nkey issue. The delay comes from the constant reprobing while looking for the nkey device after it disappears. If we solve that this symptom goes away.

**Comment by pastaq** [comment]
Instructions:

```
sudo frzr-unlock
sudo pikaur -Sy handygccs-git
sudo systemctl restart handycon
```

**Comment by fkysly** [comment]
> Instructions:
> 
> ```
> sudo frzr-unlock
> sudo pikaur -Sy handygccs-git
> sudo systemctl restart handycon
> ```

thx, but I have already update HandyGCCS, question still be there.
Yeah, you reply is right, the main point is the rog suspend/resume problem, it's the only problem to Rog Ally use ChimeraOS. So, Can we solve the suspend problem? Or it's depends on linux kernel update?

**Comment by s0541822** [comment]
> > > Instructions:
> > > ```
> > > sudo frzr-unlock
> > > sudo pikaur -Sy handygccs-git
> > > sudo systemctl restart handycon
> > > ```
> > 
> > 
> > thx, but I have already update HandyGCCS, question still be there. Yeah, you reply is right, the main point is the rog suspend/resume problem, it's the only problem to Rog Ally use ChimeraOS. So, Can we solve the suspend problem? Or it's depends on linux kernel update?
> 
> finally, I use the steam-patch, and disabled HandyGCCS can solve this problem.

Does this mean you need to run the commands everytime you suspend/resume the device?

**Comment by pastaq** [comment]
> > > > Instructions:
> > > > ```
> > > > sudo frzr-unlock
> > > > sudo pikaur -Sy handygccs-git
> > > > sudo systemctl restart handycon
> > > > ```
> > > 
> > > 
> > > thx, but I have already update HandyGCCS, question still be there. Yeah, you reply is right, the main point is the rog suspend/resume problem, it's the only problem to Rog Ally use ChimeraOS. So, Can we solve the suspend problem? Or it's depends on linux kernel update?
> > 
> > 
> > finally, I use the steam-patch, and disabled HandyGCCS can solve this problem.
> 
> Does this mean you need to run the commands everytime you suspend/resume the device?

This isn't required anymore as the latest HandyGCCS is already installed by default. It's not a magic cure-all though, this was a minor QOL improvement that enabled redetection of the devices in some scenarios. Other issues exist still that aren't covered by HandyGCCS.

**Comment by HansWorst77** [comment]
> This isn't required anymore as the latest HandyGCCS is already installed by default. It's not a magic cure-all though, this was a minor QOL improvement that enabled redetection of the devices in some scenarios. Other issues exist still that aren't covered by HandyGCCS.

Thank you for your reply. 
I guess I will still wait for further development of ChimeraOS before switching from Win11. Though I'm really looking forward to run Linux on it, it sounds like there are still issues that I don't want to deal with yet.

**Comment by al12gamer** [comment]
While I don't personally have a ROG Ally, a friend of mine does. They have kept the original drive running Windows around for the sole purpose of booting into it occasionally and running BIOS updates, as they have mentioned ASUS have been putting out a lot. If anyone with these suspend issues is on the latest bios, are you still experiencing them?

**Comment by jackgllghr** [comment]
Supposedly these fixes have worked to enable sleep for Nobara distro as shown in "The Casual Gamer PH"s Yourube channel, not sure if applicable here:

https://github.com/jlobue10/ALLY_Nobara_fixes

**Comment by pastaq** [comment]
> Supposedly these fixes have worked to enable sleep for Nobara distro as shown in "The Casual Gamer PH"s Yourube channel, not sure if applicable here:
> 
> https://github.com/jlobue10/ALLY_Nobara_fixes

Most of these were developed in collaboration with @jlobue10 on our discord. The relevant patches have been applied and sleep should be functional on the unstable channel currently.

**Comment by jlobue10** [comment]
Yes, Luke Jones made the major breakthrough for functional sleep, and the relevant kernel patch has been upstreamed.
