### ISSUE TITLE
Screenshot not working when using gamescope-session in ArchLinux

### ISSUE THREAD

**Issue by last-partizan** [ChimeraOS/chimeraos#689]
This isn't related to ChimeraOS as such, i'm using `gamescope-session` in ArchLinux, and when i try to make screenshot in a game - nothing happens.

I'm using gamepad DualShok4, and pressing "Logo + R1". Same keybinding works when running Steam Big Picture mode in normal Gnome session, but not in gamescope-session.

Does it work in ChimeraOS? Any ideas how to fix it in my case?

**Comment by Samsagax** [comment]
I came across this one. The screenshot is taken and you will see it in the game post game.

It won't show the toast notification for some reason. Seems to be a client issue.

**Comment by last-partizan** [comment]
No, after closing the game - no new screenshots is created at all.

So, this is something different.

**Comment by last-partizan** [comment]
Hmm, but seems like this is unrelated to `gamescope-session`.

I tried running `steam -gamepadui -steamdeck -steamos3` in Gnome, and it too wasn't able to make screenshots.
