### ISSUE TITLE
Audio overrides skipped on ROG Ally BIOS v323

### ISSUE THREAD

**Issue by ecarney36** [ChimeraOS/chimeraos#701]
Before installing ChimeraOS I updated to BIOS version 323. When trying to use firmware overrides for the Ally it skips implementation since it’s for v319. Through someone’s video before the release of Chimera 43, their console says “Adding rog_ally_v319_acpi_override to bootloader” whereas when I enter the same command ‘sudo frzr-tweaks’ it skips it for not finding anything. Firmware overrides are enabled (=1).

**Comment by ashtophet** [comment]
The overrides for 323 aren't there yet, to use them:
https://github.com/ChimeraOS/device-quirks/issues/65#issuecomment-1646405499
