### ISSUE TITLE
Invisible steam overlay during gameplay

### ISSUE THREAD

**Issue by S1ngl3-x** [ChimeraOS/chimeraos#708]
Hello, 

ever since the big update in Chimera 43 my gaming steam overlay is invisible. When i press PS button on my DualSense I can hear the menu sounds and can even use PS button + X to start using right menu overlay and change sound volume without being able to see anything. Update 43-1 didn't help with this issue.

For example it forces me to close games by pressing PS button and then blindly by memory go menu item down -> Home -> Game Detail -> close.

Everything worked fine in v 42.

System spec:
OS Version : 43-1
OS Build : 788f4bb
Kernel Version : 6.3.9-chimeraos-1
Mesa 23.1.3

Steamdeck channel : Stable
CPU : AMD Ryzen 7 5700X
GPU : AMD Radeon 7900 XT
RAM Size : 32GB

I will gladly provide any additional information if I get instructions on how to debug gaming mode.

Thank you for your great work
Cheers

**Comment by Teonyr** [comment]
I'm facing the same issue.
Found out it seems to have to do with HDR. 
If I switch on "experimental HDR support" in settings and turn on HDR, then the overlay works perfectly fine. 
Disabling HDR again makes the overlay invisible again.

**Comment by S1ngl3-x** [comment]
I can confirm HDR is the issue. However it's not really a solution since turning it on just makes everything washed off.

Not sure if the problem is at chimera or at valve here.

**Comment by S1ngl3-x** [comment]
I am currently running with HDR enabled because it now worls much better. I guess we can close it since 1) it's probably issue on Valve's side 2) low priority.
