### ISSUE TITLE
Bluetooth devices (including Xbox One S and DS4 controllers) not pairing correctly via SteamOS bluetooth settings

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#71]
Upstream bug report for Steam:
https://github.com/ValveSoftware/steam-for-linux/issues/6756

A workaround to successfully pair a bluetooth device is to use `bluetoothctl` from the command line and follow the connection instructions here (no need for the xpad neo driver): https://atar-axis.github.io/xpadneo/#connection

If you have already attempted to pair the device in the UI, you must first run the `remove <device id>` command in `bluetoothctl` before following the instructions linked above.

**Comment by jayarnielsen** [comment]
This is pretty much preventing me from using this distro :disappointed:

**Comment by jayarnielsen** [comment]
This is pretty much preventing me from using this distro :disappointed: I can pair from the UI once but on subsequent boots the controller (xbox one) keeps flashing between "connected" and "unpaired" until I delete an reconnect.

**Comment by alkazar** [comment]
This seemed quite promising (see the Auto pairing / trusting / no PIN section):
https://www.raspberrypi.org/forums/viewtopic.php?t=235519

However, the problem persisted.

**Comment by alkazar** [comment]
To fix this you can set `AlwaysPairable = true` in `/etc/bluetooth/main.conf` under the `[General]` section.

This fix will be included in the next version of GamerOS.
