### ISSUE TITLE
Installation media stuck on 1%

### ISSUE THREAD

**Issue by chelaxian** [ChimeraOS/chimeraos#711]
When try to install ChimeraOS with latest image on UEFI PC it start downloading 43-1 last update. It stucks on 1% and after some time stops with Failed status. Internet connection is OK. What can cause the problem?

**Comment by Samsagax** [comment]
That indeed is strange. What is your network hardware? The download wouldn't even start if the problem was caused by connection. Could you try again?

**Comment by chelaxian** [comment]
tried different install-media versions, tried using VPN on router, tried different etrhernet and wi-fi - same result - installation failed.
![image](https://github.com/ChimeraOS/chimeraos/assets/69438111/056a90ca-0654-495f-a426-3048de28cfe8)
![image](https://github.com/ChimeraOS/chimeraos/assets/69438111/9bbd1ee2-f0f1-4692-b8a2-5073727d2a71)
![image](https://github.com/ChimeraOS/chimeraos/assets/69438111/7f617472-3a9f-4b9d-9a1d-bd8c1e960640)

**Comment by Samsagax** [comment]
Are you behind a proxy or a VPN? The download doesn't seem to start and curl just gives up.

**Comment by chelaxian** [comment]
The problem is solved. Problem was that installer find another arch OS on disk (it was holoiso) and ask me to repair it. I used to chose repair instead of wipe disk and new install. After chose right option all installed with no problem
