### ISSUE TITLE
Screen stuck at UEFI splash screen on boot after update.

### ISSUE THREAD

**Issue by jempson** [ChimeraOS/chimeraos#715]
After installing the latest steam update my ChimeraOS box will boot and I can hear the Steam BigPicture sounds when I push a button on the remote, but the UEFI Dell splash image stays up on the screen.  I can get the image to go away if I stop lightdm, but I can not get bigpicture to work since installing the latest updates.

I have ssh access and chimera web access to the machine and would like to fix this issue rather then reinstall.

Please let me know what information you need to assist with this?

I am running this on a Dell XPS with an nVidia RTX 3060 graphics card.

**Comment by alkazar** [comment]
Nvidia is not supported. Sorry.
