### ISSUE TITLE
ROG Ally, game mode not start after Firmware Update Tool 3.8.0.002

### ISSUE THREAD

**Issue by davnozdu** [ChimeraOS/chimeraos#718]
I am have dual boot (windows + chimeraos) and today I am install Firmware Update Tool 3.8.0.002 for fix gamepad bug.
After flash this firmware ChimeraOS cannot start in Game mode and boot in desktop mode.
I am try recovery 100% work backup 43.1 version but same problem.
I am read, if chimeraos not detect hame controller, boot in desktop mode.
I am try change to developer build 44, same problem

**Comment by ruineka** [comment]
Try holding the power button for 10 seconds and try again. If that doesn't work try holding it for 40 seconds to completely clear out the EC and then try it again.

**Comment by davnozdu** [comment]
> Try holding the power button for 10 seconds and try again. If that doesn't work try holding it for 40 seconds to completely clear out the EC and then try it again.

Super, thanks.
I am try your case, after reset long boot in Asus logo (flash EC) and then Chimera boot in game mode.
Thanks
