### ISSUE TITLE
Regarding the Issue of Sleep and Wake-up

### ISSUE THREAD

**Issue by ppouerct** [ChimeraOS/chimeraos#737]
When the device is in sleep mode, pressing the volume keys or other function keys wakes up the device, but the controller does not cause a wake-up, which can easily lead to accidental activation. I would like only the power key to be able to wake up the device. Additionally, disconnecting and connecting the power also causes a wake-up, which doesn't happen on SteamOS.

**Comment by pastaq** [comment]
Can you edit /etc/device-quirks/device-quirks.conf and change `USB_WAKE_ENABLED` from 1 to 0, reboot, and see if the issue persists?

**Comment by ppouerct** [comment]
> Can you edit /etc/device-quirks/device-quirks.conf and change `USB_WAKE_ENABLED` from 1 to 0, reboot, and see if the issue persists?

Still there, the device is aya one air 1s

**Comment by honjow** [comment]
As far as I know, the Air 1s cannot enter sleep mode; the screen simply goes dark, while the fan continues to operate. My Neo 2s also experiences the same situation.

**Comment by pastaq** [comment]
They are sending me a geek 1S at some point. This will probably need to wait until that is delivered, assuming it's the same on all three

**Comment by ppouerct** [comment]
> They are sending me a geek 1S at some point. This will probably need to wait until that is delivered, assuming it's the same on all three

Is there no other way? I can help with testing.

**Comment by savierxu** [comment]
i am having the same sleep issue on Aya Neo Geek 1S. The sleep only shutdown the steam console/big picture mode, but the fan, the backlight and joystick ring lights are all on. And it can be waken by ayaneo button. 

This happens on both ChimeraOS and Holoiso. 

Any fix so far?

**Comment by pastaq** [comment]
We don't have a device to work on. This device will likely need community support to resolve.

**Comment by Gaarindor** [comment]
Currently have the issue on an Ayaneo 2s.
ChimeraOS details:
OS Version: 44-1
OS Build: 4b7363e
Kernal: 6.5.6-chos1-chimeraos-1

Confirmed same issue is occurring when using systemctl suspend.
Ran  journalctl --reverse to capture.
Logs show that the device goes into suspend:
`Nov 19 09:20:34 chimeraos systemd-sleep[4523]: Entering sleep state 'susp
end'...`
But then drops out pretty quickly:
`Nov 19 09:20:40 chimeraos systemd-sleep[4523]: System returned from sleep
 state.`

Will need someone with a bit more background on what actually sticks out as an issue.
[systemctl suspend gamer journalctl output.txt](https://github.com/ChimeraOS/chimeraos/files/13402950/systemctl.suspend.gamer.journalctl.output.txt)

Full journalctl attached.

**Comment by Gaarindor** [comment]
Ran freedesktops [s2idle script](https://gitlab.freedesktop.org/drm/amd/-/blob/master/scripts/amd_s2idle.py) to grab more details.

Results are showing the below:
`2023-11-27 10:27:21,765 WARNING:	🚦 The kernel didn't emit a message that low power idle was supported   
2023-11-27 10:27:21,765 WARNING:	🚦 AMD-PMC driver is missing                                             
2023-11-27 10:27:21,765 WARNING:	🚦 Shenzhen Longsys Electronics Co., Ltd.  missing ACPI attributes`


I am going to follow up with Aya about the nvme (Shenzhen Longsys Electronics Co.) and BIOS conifg for s2idle. 

Full output: 
[s2idle_report-2023-11-27.txt](https://github.com/ChimeraOS/chimeraos/files/13473086/s2idle_report-2023-11-27.txt)

**Comment by Gaarindor** [comment]
Got my hands on an Ayaneo2 (6800U) with working sleep. 
Interesting find in /sys/power/mem_sleep:
Ayaneo2: Supports s2idle and deep. Deep is enabled
Ayaneo2s: Only supports s2idle

**Comment by pastaq** [comment]
> Got my hands on an Ayaneo2 (6800U) with working sleep. Interesting find in /sys/power/mem_sleep: Ayaneo2: `Supports s2idle and deep.` `Deep is enabled` Ayaneo2s: `Only supports s2idle.` `s2idle is enabled`
> 
> s2idle the issue? why is deep not supported on the ayaneo2s? Seems general issues revolving around sleep across Linux distros deep is the solution to fix sleep.

Microsoft has been strong arming vendors into supporting modern sleep so they can push updates to the system while it is idle. Deep sleep is being deprecated and all 7000 series we've seen so far have issues with sleep in Linux because of this.

**Comment by HishamBS** [comment]
Any solution to this issue ?
I am still facing this using ayaneo 2s and Chimeraos 46

**Comment by pastaq** [comment]
> Any solution to this issue ? I am still facing this using ayaneo 2s and Chimeraos 46

https://github.com/ChimeraOS/chimeraos/wiki/Community-Guides#enable-modern-sleep

**Comment by HishamBS** [comment]
> > Any solution to this issue ? I am still facing this using ayaneo 2s and Chimeraos 46
> 
> https://github.com/ChimeraOS/chimeraos/wiki/Community-Guides#enable-modern-sleep

Thank you very much , this worked

**Comment by fedatomateus** [comment]
Somebody has a video taught to make because I couldn't.
