### ISSUE TITLE
Cannot login http://chimeraos.local/ (Blank page after password)

### ISSUE THREAD

**Issue by daniellasalle** [ChimeraOS/chimeraos#739]
Am trying to access ```SSH``` on a fresh ```chimeraos-2023.07.06-x86_64.iso``` install and following 
[the FAQ](https://github.com/ChimeraOS/chimeraos/wiki/FAQ) I am capable of accessing ```http://chimeraos.local/``` but when I input the password (```gamer```) the page goes blank.

I have tried with another browser and it seems it's giving me an error 500 (Internal server error).

**Comment by npaladin2000** [comment]
The password for the web interface isn't the SSH password, it appears on the device's screen when you connect via HTTP.

**Comment by daniellasalle** [comment]
Sadly there is none on neither browsers:
![Screenshot at 2023-08-23 20-54-58](https://github.com/ChimeraOS/chimeraos/assets/26171838/6bfdc929-cae5-4b22-9303-0b3c4f66ce10)
