### ISSUE TITLE
Missing Refresh Rate Slider on ROG Ally and AYANEO 2S

### ISSUE THREAD

**Issue by honjow** [ChimeraOS/chimeraos#744]
When attempting to adjust the refresh rate settings on the ROG Ally  , I noticed that the refresh rate slider is missing. This prevents me from easily modifying the monitor's refresh rate settings to suit my preferences.

Similarly, when using the AYANEO 2S , I encountered the same issue – the refresh rate slider was nowhere to be found in the QAM.

I've also been informed by a friend that the AYANEO 2 ,  also lacks the refresh rate slider functionality.

![image](https://github.com/ChimeraOS/chimeraos/assets/14888379/00720bcb-951c-4cee-9059-d102da74cddf)

**Comment by ruineka** [comment]
To enable refresh rate changing on these devices enable developer mode in steam and check the "Enable refresh rate changing with external displays" option.

**Comment by honjow** [comment]
> To enable refresh rate changing on these devices enable developer mode in steam and check the "Enable refresh rate changing with external displays" option.

Thank you. Working on rog ally. Additionally, the absence of refresh rate range sliders for neo2s and neo2 is likely due to the variable "STEAM_DISPLAY_REFRESH_LIMITS." I have added it and it's resolved.

**Comment by lm209** [comment]
> > To enable refresh rate changing on these devices enable developer mode in steam and check the "Enable refresh rate changing with external displays" option.
> 
> Thank you. Working on rog ally. Additionally, the absence of refresh rate range sliders for neo2s and neo2 is likely due to the variable "STEAM_DISPLAY_REFRESH_LIMITS." I have added it and it's resolved.

How do you add the variable? What File have you edited?
