### ISSUE TITLE
LLVM 16 breaks Valve games

### ISSUE THREAD

**Issue by alkazar** [ChimeraOS/chimeraos#752]

**Comment by NeroReflex** [comment]
Is this llvm fault or glibc?

**Comment by wantija** [comment]
Team Fortress 2 is the big game that needs user workarounds. It does not work with proton and you need to install lib32-gperftools from the AUR, remove `libtcmalloc_minimal.so.4` in the game's bin folder, then make a symlink of `/usr/lib32/libtcmalloc_minimal.so.4` to the same folder. I do not know of any other multiplayer source games that would need this workaround.
