### ISSUE TITLE
Ayaneo Air 1S support

### ISSUE THREAD

**Issue by kristoffertell** [ChimeraOS/chimeraos#755]
I currently have chimeraos-44_8f62901 (with firmware overrides active) installed on an external SSD which I've been able to boot to on my Air 1S to try it out without wiping the internal drive. I know the Air 1S is not fully supported yet but I figured I might as well report my findings.

Things that worked out of the box include:
:white_check_mark: Running various games through Steam in big picture mode. Haven't done any extensive performance testing yet.
:white_check_mark: The Aya and "=" buttons work as expected (Aya button acts as Home/Xbox button to bring up the left menu in Steam and the "="-button brings up the right menu. LC and RC buttons bring up the on-screen keyboard).
:white_check_mark: Performance overlay and framerate limiter seem to work as expected.

These are the issues I've run into so far:
:x: No sound from internal speakers (bluetooth audio works fine though, I guess it's a driver issue with the I2S amp they seem to be using).
:question: When activating "Game mode", Steam big picture mode is not using all the screen space (there is a black border all the way around the screen).
:heavy_exclamation_mark: Stick LED ring control: Found a workaround by forking and updating `ayaled`. See first edit below.
:question: Haven't figured out a way to tweak TDP and fan speed settings properly yet. Steam's own TDP settings doesn't seem to do anything and PowerTools doesn't seem to recognize the GPU.

If there's anything I can help out with just let me know. I'm a developer myself with a bit of Linux experience. Although I'm not super familiar with Arch in particular (worked mostly with Debian).

I'll be editing this as I encounter more issues, or figure out how to get stuff working.

### EDIT 1:
I suspected the LEDs on the AIR 1S could be controlled the same way as the Air and Air Pro, as the Air 1S seems to be mostly the same as those models besides the APU. But since the `ayaled` tool is apparently not maintained anymore I forked it and simply added "AIR 1S" as a supported device in the same category as the Air, Air Pro, Ayaneo 2 and Geek.

Available here:
https://github.com/kristoffertell/ayaled2

**Comment by pastaq** [comment]
You should be able to tweak TDP with the `chimera-session gamepadui-with-qam` session. For audio we need to patch in the mapping for the amp.

**Comment by kristoffertell** [comment]
Found a workaround for the LEDs that seems to work. Edited original post.

> You should be able to tweak TDP with the `chimera-session gamepadui-with-qam` session.

It doesn't seem to want to start up at all unfortunately. `chimera-session gamepadui` starts up and mostly works (except the black border mentioned) but `chimera-session gamepadui-with-qam` just gives a black screen with a blinking cursor at the top left, seemingly forever.

**Comment by pastaq** [comment]
That's good to know for the LED's. AYANEO Platform is another driver i need to get around to writing at some point to  control these things. I'm not sure exactly what to do with ayaled since Maya dropped the project and the AUR points to her repo. Mark it as unmaintained and get permission to take it over for now might work.

**Comment by luluco250** [comment]
Got Arch installed on my Air 1S Ultra, I can confirm the internal speakers don't seem to work, though the headphone jack does.

I was able to control the TDP with RyzenAdj (`sudo ryzenadj -a 5000 -b 5000 -c 5000` would set it to 5W for example), might be an issue with the frontend used by ChimeraOS.

That said, I'm using the `amd_pstate=guided` kernel parameter so that power management is more or less automatic, I don't feel the need to actively change the TDP.

Btw I couldn't get your `ayaled2` fork to install through the AUR, it complains about `main.rs` missing for some reason.

**Comment by tsheehan95** [comment]
Hi, 

I'm wondering if there have been any new updates regarding the internal speakers in the air 1s. Have any of you folks found a solution?

**Comment by nawafcs** [comment]
am having the same problem with ayaneo air 1s 
i can see the new sound driver (aya sound fix) but no sound

**Comment by ruineka** [comment]
> am having the same problem with ayaneo air 1s 
> 
> i can see the new sound driver (aya sound fix) but no sound

The work being done is on unstable, but there are a few things going on to make everything stable still. You will need to provide the firmware from the Aya windows driver package at /usr/lib/firmware/aw87xxx_acf.bin.

We should have this all working out of the box in the coming updates.

**Comment by ruineka** [comment]
> Couldn't find this file aw87xxx_acf.bin

In the driver package provided by aya it is named `awinic_smartk_acf.bin`. You will rename this to `aw87xxx_acf.bin`

**Comment by luluco250** [comment]
@nawafcs if you'd like I wrote an AUR package to automate this process: https://aur.archlinux.org/packages/aw87xxx-acf-firmware

It downloads the drivers from Ayaneo (sorry for the nearly 1GB download, blame them) and installs it to the correct path.

@ruineka please let me know if it works well!

**Comment by nawafcs** [comment]
Thanks I'll try that,
Just need to put it there right? 
/lib/firmware/aw87xxx_acf.bin

**Comment by luluco250** [comment]
> Thanks I'll try that, Just need to put it there right? /lib/firmware/aw87xxx_acf.bin

Sorry, ended up renaming the package, here: https://aur.archlinux.org/packages/aw87559-firmware

You should unlock root if you haven't done so with `sudo frzr-unlock` and then install the package with `pikaur -S aw87559-firmware`.

**Comment by nawafcs** [comment]
I have download the file (1 gb) file but don't know what to do i run the command but msg searching
Sorry don't have experience with linux

**Comment by nawafcs** [comment]
Thanks i found how, just waiting for the result

**Comment by nawafcs** [comment]
The sound still not working

**Comment by ruineka** [comment]
> The sound still not working 

Can you try plugging in a pair of headphones? There has been a report of a system having sound out of the speakers only when headphones are plugged in. I am tracking down why the pin layout is looking different among devices.

**Comment by luluco250** [comment]
> The sound still not working

What's the output of `ls /usr/lib/firmware/aw*`?

**Comment by nawafcs** [comment]
The headphones works, but the speakers are the problem
![17146618902472554117479517260170](https://github.com/ChimeraOS/chimeraos/assets/3319144/016c7b55-37ad-4811-85d0-c2610725f990)

**Comment by ruineka** [comment]
> The headphones works, but the speakers are the problem
> 
> ![17146618902472554117479517260170](https://github.com/ChimeraOS/chimeraos/assets/3319144/016c7b55-37ad-4811-85d0-c2610725f990)
> 
> 

Okay. What is the output of ```sudo dmesg | grep -i awinic"```

**Comment by ruineka** [comment]
> Really long long text, anything specific? 

If it read the chip id and successfully parsed the firmware.

**Comment by nawafcs** [comment]
dont know why the code u mension stop working i use another one to get the details and save it in to pdf formate 
[chimeraos.pdf](https://github.com/ChimeraOS/chimeraos/files/15193541/chimeraos.pdf)

**Comment by its-Jassie** [comment]
Latest stable version (ChimeraOS 46) fixes audio with the inclusion of [new firmware files](https://github.com/ChimeraOS/chimeraos/commit/2ae2da734ae95740b6a3caa19fee55e559c8364d)

I am currently using decky plugins [SimpleDeckyTDP](https://github.com/aarron-lee/SimpleDeckyTDP) for TDP control and [HueSync](https://github.com/honjow/HueSync) for LED control. Both are working well. 

Switching between game mode and desktop mode is also working well for me.
