### ISSUE TITLE
Stuck on old video driver 4.6 mesa 23.1.3

### ISSUE THREAD

**Issue by Ajwag22** [ChimeraOS/chimeraos#756]
My video drivers are months out of date. I do the regular system updates but it just stays stuck on video driver 4.6 mesa 23.1.3. I am running ChimeraOS on a 5800x3d rx 6900XT system and don't have many issues with anything but would like to try to play Starfield and can't because of these old drivers. Any help on  how to update?

**Comment by lm209** [comment]
Switch to Unstable build.

**Comment by lm209** [comment]
> My video drivers are months out of date. I do the regular system updates but it just stays stuck on video driver 4.6 mesa 23.1.3. I am running ChimeraOS on a 5800x3d rx 6900XT system and don't have many issues with anything but would like to try to play Starfield and can't because of these old drivers. Any help on how to update?

Do you use Stable 43-1?

**Comment by pastaq** [comment]
Updates are done via the frzr utility when a system image has been tested and patched to ensure as close to a seamless transition as possible. We are currently in the testing phase for v44 which will come with a bump to the current mesa drivers. Please be patient while we work to ensure the most stable image possible.
