### ISSUE TITLE
Ayaneo Air Plus Controls

### ISSUE THREAD

**Issue by OnePieceIsRealllll** [ChimeraOS/chimeraos#758]
Hey, i downloaded ChimeraOS on my Ayaneo Air Plus device and the buttons are delayed. I uninstalled it and reinstalled it and its still acting up. I tried HoloISO and the face buttons work fine but the orientation is upside down so I went back ChimeraOS knowing that its not my device. Is there a way to fix this issue?

**Comment by pastaq** [comment]
This issue is resolved in the latest kernel. We should be releasing an update in the next couple of days that will eliminate this bug.
