### ISSUE TITLE
Consider re-adding Nvidia support as optional package

### ISSUE THREAD

**Issue by stevefan1999-personal** [ChimeraOS/chimeraos#759]
Sure, I do get why Chimera don't want to support Nvidia since SteamOS is AMD based, but I have my gaming handheld (more specifically Ayaneo Geek) have USB4/TB3 support where I can slot in my RTX 2070 with a TB3 eGPU enclosure as my choice for dGPU gaming, and potentially VR support.

I just want to see if we can still install the proprietary Nvidia drivers so that we would know whether the eGPU would function correctly, although given others said it, the drivers were removed from the repository tree, so I assume nor would nouveau. There's no need for the ChimeraOS team to support it, but the possibility shouldn't be eliminated as such.

I would also try to see if I can build the official "open source" Nvidia drivers (according to Linux people, anything that is not GPL or copyleft is not open source to them anyway), but those are not for gaming, and is rather for scientific use. 

Well, the final resolution would be to use OVMF and PCIE passthrough and run Windows on it. That would take a big toll on performance but at least it will work out of the box (I did it before on Proxmox)

**Comment by pastaq** [comment]
At this time the benefits don't outweigh the negatives, so it won't be included in the image. You can always do a `frzr-unlock` and install the nvidia driver manually, but you will need to do this every update. You can also pin version 42 as that has the best nvidia support, or try BazziteOS who have an nvidia specific image.
