### ISSUE TITLE
How to add non steam game

### ISSUE THREAD

**Issue by mindtheegab** [ChimeraOS/chimeraos#771]
hi, apologies for the silly question but i cant find a way to add a game like from Lutris , i only see steam,gog and epic as options, tried from tty but pacman is not working

**Comment by parth-menon** [comment]
You can just open Steam in Desktop mode and add it as a non steam game

**Comment by mindtheegab** [comment]
i meant with lutris, also why pacman doesnt work?

**Comment by parth-menon** [comment]
> i meant with lutris, also why pacman doesnt work?

Do 

sudo frzr-unlock

Then pacman should work

**Comment by mindtheegab** [comment]
thank you! did i miss this from the docs?

**Comment by pastaq** [comment]
> thank you! did i miss this from the docs?

It's in the docs. We don't recommend installing things with pacman as the changes with be overwritten during system updates. Unlocking and installing packages is available only to test updated packages or candidate packages in a developer environment, or in rare cases a developer will direct users to install something.
