### ISSUE TITLE
right menu disappears when releasing xbox button

### ISSUE THREAD

**Issue by mindtheegab** [ChimeraOS/chimeraos#773]
the xbox+A combination to open the right overlay menu is not working properly, the mement you release the xbox button the menu disappears

same exact thing with a ps4 controller

**Comment by pastaq** [comment]
This is a known issue with steam at the moment. It seems to be triggered if you use the b button to close the menu instead of the combo you used to open it. Some folks have reported they fixed it temporarily by opening the OSK with steam+x

**Comment by RodrigoPrestes** [comment]
Looks like they fixed.
Reads from the [October 25th patch notes](https://store.steampowered.com/news/app/1675200/view/3714966246894291121)  (third to last on the general section).
> Fixed a case where the Main Menu or the Quick Access Menu would be immediately dismissed after opening.
