### ISSUE TITLE
http://chimeraos.local not accessible when both wifi & lan are connected

### ISSUE THREAD

**Issue by daniellasalle** [ChimeraOS/chimeraos#783]
Checking ```ip a``` I see both of my network adapters that have a different IP: 192.168.137.117(WiFi) and 192.168.137.120(RJ45)

From another computer, the DNS answers:
```
PING chimeraos.local (192.168.137.120) 56(84) bytes of data.
64 bytes from 192.168.137.120 (192.168.137.120): icmp_seq=1 ttl=64 time=0.512 ms
64 bytes from 192.168.137.120 (192.168.137.120): icmp_seq=2 ttl=64 time=0.984 ms
...
```

But when I access http://chimeraos.local I get 404

Lastly, checking under ```ss``` I did not see anything listening on port 80.

**Comment by alkazar** [comment]
The service is no longer on port 80 because it was found to interfere with some game launchers.

You must connect to port 8844.

**Comment by daniellasalle** [comment]
Accessing both 192.168.137.117:8844 & 192.168.137.120:8844 both displayed the Chimera webpage.

Thanks a lot for another flawless support case <3
