### ISSUE TITLE
[bug] Consider removing Legion Go Refresh Rates from gamescope plus due to bugs

### ISSUE THREAD

**Issue by aarron-lee** [ChimeraOS/chimeraos#802]
In gamescope-plus, currently the Legion Go has `STEAM_DISPLAY_REFRESH_LIMITS=60,144` set as the fresh rates.

There are a few bugs I noticed surrounding this:

1. If I set a refresh rate to an arbitrary value between 60 and 144, the screen becomes a fuzzy gray screen, and there's no way to revert it back immediately. I ended up hooking up an external monitor for to revert the settings
2.  the FPS frame limiter is buggy when the refresh rate slider is enabled. e.g. When I'd try to set the FPS to 72 while in 144Hz refresh, it would not actually limit refresh rate to that number. It would be wildly off, making the fps limiter untrustworthy. Similar issues happen while at 60Hz.
3. When changing back and forth between 60 and 144Hz, eventually the slider would get "stuck", making it difficult for to switch the refresh rate again without rebooting the steam client

I'll document more of the bugs when I encounter them, but I'd recommend removing the slider altogether until it's been more thoroughly tested and bugfixed.

https://github.com/ChimeraOS/gamescope-session/blob/cd59422ff9ba2f5719d61c4801ad56d786e21caf/usr/share/gamescope-session-plus/device-quirks#L232

**Comment by ruineka** [comment]
Could you test with `--generate-drm-mode fixed` to see if there is a change in this behavior?

**Comment by aarron-lee** [comment]
> Could you test with `--generate-drm-mode fixed` to see if there is a change in this behavior?

Nice, a lot more of the refresh rates seem usable to me, albeit you start temporarily seeing large fuzzy lines on the screen as you go down in refresh rate. Once the fuzzy lines go away, it seems to work fine now.

It seems to work from 144Hz down to 120Hz or so, around 90Hz if you are willing to wait for the fuzzy lines to disappear. Once you start going below 90Hz, the fuzzy lines become persistent until 60Hz.

it partially fixed the problem with the frame limiter, but not completely. the 144hz framerate limit is more accurate, and frame limits on other resolutions like 120Hz seem accurate, but the framerate limiter at 60Hz is wrong.

60 Hz with a 60 frame limit I get 30fps, at 30 frame limit I get 21 fps, at 15 frame limit I get 12 fps.

**Comment by aarron-lee** [comment]
resolved, refresh rates have been removed
