### ISSUE TITLE
44.1 switching from desktop to game mode black bars

### ISSUE THREAD

**Issue by tcaduto** [ChimeraOS/chimeraos#804]
Just installed 44.1 on a all amd system and when I switch to the gnome desktop then back to game mode it leaves black borders all around so the picture does not full the screen.   Restart needed to fix it.

RYZEN 5700X CPU
Radeon 5700xt gpu
32gb ram
ASROCK B550 PHANTOM GAMING ITX MB

**Comment by sonalder-darlene** [comment]
Why is it closed ? I still have this issue on my living room PC running ChimeraOS latest version

Ryzen 5 3600
Radeon RX 6600

**Comment by NeroReflex** [comment]
> Why is it closed ? I still have this issue on my living room PC running ChimeraOS latest version
> 
> Ryzen 5 3600 Radeon RX 6600

It is closed because the issue of one year ago was solved. Open a new one as you probably have some other problem.
