### ISSUE TITLE
ChimeraOS Verified Linux Native games not launching

### ISSUE THREAD

**Issue by Adictya** [ChimeraOS/chimeraos#818]
Steam shows running but stops and returns to the game screen without showing anything else. The games run fine when launched manually through their executables or sh files.

Observed this behavior with the following games:
- Celeste
- Limbo
- Super Meat Boy

Trying to collect more information on why, but unable to. Happy to work on the fix as well, just need to understand if I can see the error logs somewhere or what steps I can take to diagnose this issue.

Searching online it is just recommended to run it via proton. But not all games are compatible eg, Super Meat Boy doesn't run well on Proton.

**Comment by alkazar** [comment]
I am unable to reproduce the issue. All three of those games work out of the box for me.

I noticed that all these games use the Steam Linux Runtime 1.0. It is likely that the runtime files have become corrupted somehow.

Try verifying the integrity of the game files, and if that still doesn't help try running `steam-runtime --reset`.

**Comment by Adictya** [comment]
Thanks for the reply. I verified both the game files as well as all the Steam runtimes (scout, soldier, etc) and ran the command as well. But it's still the same.

But yeah I think you are right, the problem does seem to be with the steam-runtime since the game executables/scripts are never run and it's not just v1 since Super Meat Boy uses soldier.
