### ISSUE TITLE
作者您好，请问如何在奇美拉OS下安装kde桌面并将其设为默认启动

### ISSUE THREAD

**Issue by 1224848464** [ChimeraOS/chimeraos#824]
由于我之前使用steam os的经历，导致我认为gnome没有kde顺手，我在安装kde后试图用systemclt设置默认启动，但系统好像不允许我这么做，请问如何解决

**Comment by pastaq** [comment]
We have no plans to support KDE. The desktop is not for regular use, it is a utility for occasionally configuring the system. KDE will be removed during updates automatically and your system will break.

Google Translation:
我们没有计划支持 KDE。桌面不是经常使用的，它是偶尔配置系统的实用程序。 KDE 将在更新期间自动删除，并且您的系统将崩溃。
