### ISSUE TITLE
Chimera unstable: can't switch to desktop mode anymore 

### ISSUE THREAD

**Issue by CapitaineJSparrow** [ChimeraOS/chimeraos#836]
I want to report here since it's the place, but since today the switch to desktop mode isn't working anymore using chimera unstable. At least 2 different persons are experiencing the problem 

Link to discord ticket if relevant: https://discord.com/channels/560281725175988233/1190195409616916550

I don't have any logs file since I'm stuck in gaming mode but feel free to tell me what are the debugging steps which can help 

Edit:
Device: Asus ROG ally 
Build: a109866 (latest unstable)
Kernel: 6.6.7-chos4

**Comment by alkazar** [comment]
Can you try the latest `testing` build?

**Comment by CapitaineJSparrow** [comment]
Can't reproduce in latest testing
