### ISSUE TITLE
Update hardware support page

### ISSUE THREAD

**Issue by falhumai96** [ChimeraOS/chimeraos#856]
Based on the new changelog for ChimeraOS 45, the hardware support page seems to be outdated for the ROG Ally (not sure about the other hardware). Based on the 45's changelog, you mentioned that audio (I presume you mean speakers?) no longer requires BIOS override to work properly, though it still mentions that it does in that page. I am also wondering what else have been fixed for the Ally (I've seen demos of Gyro and suspend/resume to be working (at least the latter works on NobaraOS and perhaps the patches have been added to ChimeraOS)), as I am looking forward to installing it on my personal handheld 😊.

**Comment by alkazar** [comment]
Thanks. I updated the information on the website.
