### ISSUE TITLE
How can I completely disable sleep transition?

### ISSUE THREAD

**Issue by WeslyG** [ChimeraOS/chimeraos#860]
I use intel nuc 12 for chimeraos and besides the system itself, my device also works in web server mode (docker jellyfin and possibly something else later).  I use egpu for games, and hardware acceleration of jellyfin video encoding and everything works fine, however, when my TV is turned off, the nuc goes into sleep mode, and becomes unavailable via ssh. I want to turn it off completely, and leave it running always, regardless of any external factors. He should always be in touch and available. I disabled switching to power saving mode in the steam ui and as long as my TV is connected, it works fine, however if I turn it off, it stops working. Are there any recommendations on how I can fix this?

**Comment by pastaq** [comment]
https://www.tecmint.com/disable-suspend-and-hibernation-in-linux/

**Comment by WeslyG** [comment]
Thank you, it really helped!
