### ISSUE TITLE
Suggestion: Add driver for the Xbox wireless dongle (xow)

### ISSUE THREAD

**Issue by WeslyG** [ChimeraOS/chimeraos#861]
Have you considered adding an xow driver to chimeraos? I've tested this manually and it works great. Seems like this could be useful not only to me, but to many who will be building a home console on a pc base and want to use the xbox adapter it is much more convenient than bluethooth. What do you guys think about this?

https://github.com/medusalix/xow

**Comment by alkazar** [comment]
xow is the old driver, xone is the newer one which ChimeraOS already includes. I use it every day.

Does the xbox dongle not work for you?

**Comment by ruineka** [comment]
> Have you considered adding an xow driver to chimeraos? I've tested this manually and it works great. Seems like this could be useful not only to me, but to many who will be building a home console on a pc base and want to use the xbox adapter it is much more convenient than bluethooth. What do you guys think about this?
> 
> https://github.com/medusalix/xow

The xbox dongle should already work OOTB I use it in my systems. Xow was replaced with the xone-dkms module.

**Comment by WeslyG** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUUSgWWOmhz4XyhZjCY8p8Peil4AJZM9nNLkB5FQMWrWQOx18pGDjBL/ZsRj4JFWgLf+e4QADotLAJH8bXobscBtV/e5kePYhnsSB69QJDU+ssdBlpefqdcMLv0dgJs6aVl49hj2dTkLUMaSgPd8XCinDyYVPiSpxTHVfYJ0StwMKbNvTfDA4xMlf5iOiigCu0tTvsV3YTBVmcH6f5mdq6Dm3N2qETusVx1zi76Tm6knRV/wSjR9QT2jg9qWNhmVEHsruC2zYWtYUyY9rGZPyyiB0GjZUi7qIshD+Z8mG/eU8XsB2jdYinPS4dCu4fi40IgW7IAYozWGkPLic2PQD0GgtuxP9Klah7qRzj9ccpBlYwkt+ZXVAaAbAI390lWUS+heII3TgjB5fTR4bqTfGFfscGUmYIoQEj9vOQZr5nuENMXH2zV4REYnbZvIgOMpa7W+5q3n4FQ3Dr9Mk3CFwXfbTlVvqQLj6uA7aMWY/7thzG3MKxfNUlE9eOYfG57ICTjSq7/j90u/IMi69WP1X4hAKiKT837d774sA/wGZZaQ3N/IXewt0argSeXVCX0BDaWgTvO/ryPeSv1XWHwDJpyKNpahCgZbHD88gHVXz2Hsenk99+uwR46AaRARthdMnWTdVH48GF/le3o37BvnwiWFaMnvTm7pnFErgDMBHyww== WeslyG-PC

**Comment by WeslyG** [comment]
I reinstalled chimeraos again from scratch, and the dongle did work correctly without xow.  Wow, thank you for that! That's really cool!
