### ISSUE TITLE
RefreshRate/FPS slider no longer working after v45

### ISSUE THREAD

**Issue by Adictya** [ChimeraOS/chimeraos#863]
The combined (refresh rate + fps) slider is no longer able to change the refresh rate.

Device: GPD Win4 pro (amd 7840u)

**Comment by aarron-lee** [comment]
That's something steam changed, not sure if chimeraOS devs will be able to do much about it.

Try disabling the unified slider under display settings, and manually change the refresh rate there

**Comment by Adictya** [comment]
Thanks for the info. Was a bit unclear on how each is managed since the UI updated for me after the update but it makes sense. 

Closing the issue since it's not relevant.
