### ISSUE TITLE
[package request] Please add transmission-cli to the base packages

### ISSUE THREAD

**Issue by mdeguzis** [ChimeraOS/chimeraos#877]
I don't think there is a base simple CLI-focused client to handle torrents. This package is super* small at around MB

https://archlinux.org/packages/extra/x86_64/transmission-cli/

**Comment by ChaosBlades** [comment]
I get it, super small. But why? Deluge, qBittorrent, Transmission, and even Transmission Remote along with several other torrent clients are already on flathub. So what is the point in adding this? I would understand if no decent clients are on flathub but there are plenty on offer.

**Comment by mdeguzis** [comment]
It's extremely minimal and made for the CLI. Why would I install one of those bloatwares? Simple daemon with webui over local network.

**Comment by npaladin2000** [comment]
If that's the case, can't you just drop the transmission-cli binary in your home directory and run it from there?  Seems to me that an actual CLI torrent solution is a fairly limited use case and not something a lot of people would be interested in.

**Comment by mdeguzis** [comment]
> If that's the case, can't you just drop the transmission-cli binary in your home directory and run it from there?  Seems to me that an actual CLI torrent solution is a fairly limited use case and not something a lot of people would be interested in. 

Is the CLI inside the flatpak files? Nit home to check. Ideally, I just want the daemon ability built in so I don't have to launch the GUI really.

**Comment by npaladin2000** [comment]
The CLI binary is available to download from https://transmissionbt.com/download , and you can set it up as a user-mode systemd service.

**Comment by mdeguzis** [comment]
> The CLI binary is available to download from https://transmissionbt.com/download , and you can set it up as a user-mode systemd service. 

Not sure why we're arguing over including it by default so I don't need to add yet another thing to my setup script. Guess I lost this battle then. Closing
