### ISSUE TITLE
Controller doesn’t work anymore in GeForce now 

### ISSUE THREAD

**Issue by StefanoBalocco** [ChimeraOS/chimeraos#882]
Hello,
Since around 2-3 weeks when I launch a game through GeForce Now in deck mode (via Flatpacked chrome), controller doesn’t work in the game.
If I switch to desktop mode and launch GeForce now in the same chrome, all works fine.
Also after quitting  chrome in deckmode, steam menu doesn’t appear anymore.

Previously all worked as expected.

**Comment by glikched** [comment]
Try disabling Steam Input.

**Comment by StefanoBalocco** [comment]
> Try disabling Steam Input.

That's works, thanks!
