### ISSUE TITLE
Chimeraos stuck on installation 

### ISSUE THREAD

**Issue by lowbots** [ChimeraOS/chimeraos#890]
Installation won't seem to finish. It just gets stuck at one point and restarts. I turned security boot off, I tried turning on and off csm support, switching storage boot option control from uefi to legacy to uefi, enabled svm. been switching those options but still the same.

I have no experience in coding and linux, it's my first time trying to install linux os

![Screenshot_2024-03-10-18-00-10-83_99c04817c0de5652397fc8b56c3b3817](https://github.com/ChimeraOS/chimeraos/assets/162956030/830d628c-58f9-4960-a021-9eb7ce50d8a8)

**Comment by glikched** [comment]
Could you provide more info i had this issue on an old Arch Linux install. Tell me about what hardware are you trying to use and whetere you have any bios option modified from defaults.

**Comment by lowbots** [comment]
cpu is ryzen 5 4600g, mb is gigabyte a520m ds3h, os is windows 10, connected to the Ethernet, no Bluetooth in mobo but i have a Bluetooth receiver plugged in

so far i tried disabling safety boot, i tried to enable/disable csm support then tried legacy then uefi, enabled/disabled svm

the counter doesn't end just like in the pic and it just restarts, boot to installation and i try again. but same results

**Comment by glikched** [comment]
I think this is caused by your eth entering a powersaving state. That debugging show old bugs from old kernels.

**Comment by glikched** [comment]
Can you enter windows and specify from any device info app to tell me what Realtek Wireless chip you have ?

**Comment by lowbots** [comment]
> Can you enter windows and specify from any device info app to tell me what Realtek Wireless chip you have ?

I will send an image later when i get home. thank you for the the response and giving me an idea

**Comment by lowbots** [comment]
update: I just updated the realtek drivers and tried to install again, it's not stuck anymore. thank you so much with the help
