### ISSUE TITLE
Robocop crashes on startup with new CPU/Mobo but same GPU

### ISSUE THREAD

**Issue by jayp76** [ChimeraOS/chimeraos#895]
I have a small ITX build with ChimeraOS.
Robocop was running "fine" on the old Mini ITX System with Intel i5 4570.
I reinstalled ChimeraOs with the new Mobo and AMD CPU and the game crashes after the Intro Videos.
The GPU is the same. What can i check to find what the culprit is?
Also a strange behaviour of the new system is that ChimeraOS does not shut down fully when triggering shutdown or reboot.
The system exits out of SteamOS and stays on CLI output. I have to manually power of or reset.

Old system:
i5 4570, 16GB RAM, H81 Mobo, Vega64 GPU

New system:
AMD 7700, 32GB RAM, B650i Mobo, Vega64 GPU

**Comment by pastaq** [comment]
Did you intend to close this right away?

**Comment by NeroReflex** [comment]
@pastaq he probably realized a new mesa version fixes such game in particular.
