### ISSUE TITLE
Proxmox with AMD GPU passthrough black screen

### ISSUE THREAD

**Issue by mkuznetsov** [ChimeraOS/chimeraos#896]
Latest release. Installed successful on ProxMox VM with AMD iGPU 780M or 610M. But after installation first launch is black screen. Tried hdmi cable plug in, nothing is outputted via hdmi (in some os don't activated gpu without monitor). 

Can I get some ssh access to check logs or install sunshine for streaming? How cat I check installation without gui? Are there any rescue mode with console output?

SteamOs installed with same hardware, but I need heroic with another stores. Holo Os don't try yet.

**Comment by mkuznetsov** [comment]
I was able to login into desktop, console TTY. I opened Steam as an app and login. GUI was ok and fast. But than I switched chimera-session to steam or steam-plus or opengamepadui I get a black screen. 
I tried clean install on external drive and boot from it. Same black screen.

**Comment by honjow** [comment]
Is it an unstable version? It might be due to mesa 24.0.2.

**Comment by mkuznetsov** [comment]
it is 2024.02.04 stable version, that currently on site. I download it from site. I usually don't use night builds for first installation of product. 
It looks like steam have some init problems, because desktop have no issue to render with same igpu passthrough. I played on same igpu in windows with steam, but I want higher fps and better gamepad support.

**Comment by mkuznetsov** [comment]
Any updates from team?

**Comment by NeroReflex** [comment]
I am interested in such a setup too, but downsides of doing something like that outweight the convinience for a very limited number of ppl skilled enough to pull this off anyway.
