### ISSUE TITLE
Steam Controller not recognized in Retroarch

### ISSUE THREAD

**Issue by skimmedtrollingcustard** [ChimeraOS/chimeraos#904]
I am using the Steam Controller wireless and it has been working flawlessly with Steam games, locally installed games running through proton or bottles, and flathub games. However, whenever I load an emulated game that was install through the web interface, Retroarch complains that 360 controller is not configured and I have no control within the game. I have tried with nothing except the Steam Controller connected with same result. It is recognized and works fine if I load roms in Retroarch in desktop mode. From what I have gathered, I would expect the Steam controller to work with Retroarch OOTB but does not. Wired Switch Pro Controller and keyboard and mouse will work in Retroarch if this helps with troubleshooting.

**Comment by alkazar** [comment]
This is a known limitation. Please see this documentation for a workaround:
https://github.com/ChimeraOS/chimeraos/wiki/Troubleshooting#the-steam-deck--steam-controller-do-not-work-with-the-built-in-retroarchemulators
