### ISSUE TITLE
Is there any chance of including gvfs-nfs?

### ISSUE THREAD

**Issue by mjsf12** [ChimeraOS/chimeraos#915]
I use NFS to fetch ROMs from my NAS. Currently, I have to mount it using mount (or add it to /etc/fstab), but it would be more convenient to just use Nautilus for this. Today, I tried unfreezing the system and installing this library, and I can simply use it through Nautilus. Could this library be included by default?
Sorry if something doesn't make sense, English is not my first language.

**Comment by NeroReflex** [comment]
@mjsf12 thanks for your feedback. Can you create a PR about this and provide info about how much space the new packages takes up?

**Comment by alkazar** [comment]
> I tried unfreezing the system and installing this library

Which library?

**Comment by mjsf12** [comment]
I don't know what methodology you use to measure package size, but it would only install two packages:
libnfs -> 757.5 KB
gvfs-nfs -> 50.2 KB
So it would be around 807.7 KB.
If you have your own methodology, please explain it to me.

**Comment by mjsf12** [comment]
> > I tried unfreezing the system and installing this library
> 
> Which library?

gvfs-nfs

**Comment by NeroReflex** [comment]
> I don't know what methodology you use to measure package size, but it would only install two packages: [libnfs](https://archlinux.org/packages/extra/x86_64/libnfs) -> 757.5 KB [gvfs-nfs](https://archlinux.org/packages/extra/x86_64/gvfs-nfs) -> 50.2 KB So it would be around 807.7 KB. If you have your own methodology, please explain it to me.

Answering for future reference: exactly what you did.

PR merged: thank you.
