### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by rage1337** [ChimeraOS/chimeraos#916]
Hi,

thank you very much for your work on this amazing piece of software!

### Type
> Feature Request

### Description
> Please add a writable, system-wide folder that is included in /etc/profile or similar solution

### Example Use Cases
> Advanced use cases, will not interfere with basic user, can be used for e.g. mounting network drives

### Benefits
> Users can modify the system without the need to deactivate the write-protection; Out-of-the-box users are not impacted; reduction of opened issues for scripting use cases

**Comment by alkazar** [comment]
`/etc` is already writable through use of an overlay.
