### ISSUE TITLE
Duplicated controller input game mode

### ISSUE THREAD

**Issue by S1ngl3-x** [ChimeraOS/chimeraos#918]
The fix in 45-1 didn't help "Fixed a bug when using steam-plus session where input devices were being duplicated in steam".
All controllers show duplicated. Bluetooth section shows 1, but Controller sections shows 2 controllers. Tested with 2 dualsense and 1 dualshock. In desktop mode steam properly detects only 1 controller.

### As-Is
A single dualsense controller is detected as 2 controllers: PS5 controller and PlayStation 5 controller. This causes a lot of issues and makes the gamemode almost unusable.

### To-Be
Steam gamemode properly detects a single controller as 1 controller.

### Context
ChimeraOs: 45-1
Steam Version: 1710458266
CPU: AMD Ryzen 7 5700x
RAM: 32GB
GPU: AMD Radeon RX 7900 XT

**Comment by pastaq** [comment]
Are you using the steam-plus session?

**Comment by S1ngl3-x** [comment]
Yes, I thought it's used automatically. I quickly checked the supposed config location and found nothing.

After several hours I gave up, switched to Bazzite linux and that solved the issue.
