### ISSUE TITLE
Issue shutting down and suspending

### ISSUE THREAD

**Issue by lucassbod** [ChimeraOS/chimeraos#921]
I just install ChimeraOS 45-1 and I am not able to suspend/sleep, shut down, or reboot the system with Steam UI, Console, or Desktop mode. I re-install the OS to make sure everything went well, the rest of the system works fantastically. I installed Chimera on a Aya Neo 2021 Pro, and when I try to reboot/shut down the system begins the action and it hangs. When I suspend/sleep it immediately freezes. I try waiting for over 10 minutes for all the action but nothing happened. The only way I can power off the system at the moment it to hold the power button for 10 second. I am not the most knowledgeable person when it comes to linux but if there is any other info I can provide let me know. I added a screenshot of what the system looks like when this happens. This is on a fresh OS install.
![IMG_0681](https://github.com/ChimeraOS/chimeraos/assets/41765159/50db9481-4043-4e53-a2b8-46ced6d196a3)

**Comment by pastaq** [comment]
I'm aware of this issue and am looking into the cause. I had thought it was due to adding the dkms module for the bmi160 but that wasn't the reason. It started happening partway through development of v45-1 IIRC, so perhaps reverting to v45 will help you avoid this issue.

**Comment by lucassbod** [comment]
Thank you for the quick reply, would you happen to know the best way to download older versions? or do I have to build the iso my self? 

Again sorry new to linux

**Comment by NeroReflex** [comment]
@lucassbod  sudo frzr-deploy chimeraos/chimeraos:45

**Comment by lucassbod** [comment]
Everything seems to be working. You guys are awesome.

**Comment by jboy042487** [comment]
Man, I hate to be a pest, but I am new to all of this. I just installed Chimera OS on my Ayaneo Geek and now it wont shut off or suspend. The screen stays on or turns right back on and nothing I do has worked. I see that you shared: sudo frzr-deploy chimeraos/chimeraos:45, but what exactly do I need to do?

**Comment by lucassbod** [comment]
@jboy042487 Once the system start up. Enter desktop mode and open a terminal. Then you can run the command. It will install an older version of the OS. It help a lot of you use a mouse and keyboard, made my life easier. Also I don’t think it will ask you for a password but if it does it should be gamer.

**Comment by jboy042487** [comment]
Youre awesome thank you. It'll have to wait until I get off of work. Some
how through about 4 restarts it final did suspend and turn off properly.
Idk what the change was but I did move to an unstable version before the
restart.
