### ISSUE TITLE
Unstable builds do not boot.

### ISSUE THREAD

**Issue by ClaudeLib** [ChimeraOS/chimeraos#923]
If I choose unstable builds in the installer, the following reboot results in this wall of text:

> [FAILED] Failed to start Create Swap File.
> [DEPEND] Dependency failed for Swap.
> [FAILED] Failed to start Load/Save OS Random Seed.
> [FAILED] Failed to start Create Swap File.
> [DEPEND] Dependency failed for Swap.
> [FAILED] Failed to start Load/Save OS Random Seed.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to listen on GnuPG network certificate management daemon for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache (access for web browsers) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache (restricted) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent (ssh-agent emulation) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG public key management service for /etc/pacman.d/gnupg.
> [FAILED] Failed to start D-Bus System Message Bus.
> [DEPEND] Dependency failed for Network Manager.
> [FAILED] Failed to start User Login Management.
> [FAILED] Failed to start "Bluetooth workaround".
> [FAILED] Failed to start Mount removable media on nvme0n1p1.
> [FAILED] Failed to start Mount removable media on nvme0n1p2.
> [FAILED] Failed to start Mount removable media on sda1.
> [FAILED] Failed to start Mount removable media on sda2.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start User Login Management.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start Avahi mDNS/DNS-SD Stack.
> [FAILED] Failed to start User Login Management.
> [FAILED] Failed to start User Login Management.
> [FAILED] Failed to start D-Bus System Message Bus.
> [FAILED] Failed to start User Login Management.
> [FAILED] Failed to start Light Display Manager.
> [FAILED] Failed to start User Login Management.

Screenshot (or rather photo) of the error in case any typos slipped through the OCR:
![-2147483648_-210197](https://github.com/ChimeraOS/chimeraos/assets/5920490/0bf61d63-0db2-4461-a731-236da78cd7ef)

Enabling or disabling hardware overrides makes no difference.

My system is all AMD.
Motherboard MSI X570-A PRO, firmware 7C37vHM
CPU AMD Ryzen 9 5900X
GPU AMD Radeon RX 6900 XT

At the moment of the shot I was trying to install the 703cd8c build, but really, I've been trying to install the 46 version for maybe two months and never had any luck. The stable build 9a95912 installs and boots and plays just fine. I considered installing stable and then switching to unstable to see if this works, but the "OS Update Channel" setting in Gamescope only has the "stable" option. I may try install version 46 on my LCDeck and report here.

**Comment by NeroReflex** [comment]
This is what I investigated yestarday: https://github.com/ChimeraOS/chimeraos/issues/919

**Comment by ClaudeLib** [comment]
Out of curiosity I tried installing unstable on my LCDeck. Unsurprisingly, the result is the same.
If I install stable first and *then* migrate to unstable (yeah, I figured out how to do it), then on the next boot it flashes this:

> [FAILED] Failed to activate swap Swap.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to start Network Time Synchronization.
> [FAILED] Failed to listen on GnuPG network certificate management daemon for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache (access for web browsers) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache (restricted) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent (ssh-agent emulation) for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG cryptographic agent and passphrase cache for /etc/pacman.d/gnupg.
> [FAILED] Failed to listen on GnuPG public key management service for /etc/pacman.d/gnupg.

Then the screen turns black and the input indicator (underscore) blinks endlessly in the upper left corner.

**Comment by NeroReflex** [comment]
This should fix the problem: https://github.com/ChimeraOS/chimeraos/pull/924 I am a waiting for someone else on the team to merge that and test

**Comment by ClaudeLib** [comment]
Now I know that the build e2914e1 does not have the changes from the commit #924, I still felt like giving it a try, since the changelog mentions partitions handling. Now the system does boot, but in a strange way. First it shows these lines in some fancy font:

> [FAILED] Failed to mount /etc.
> [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache (restricted) for /etc/pacman.d/gnupg.
> [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache (access for web browsers) for /etc/pacman.d/gnupg.
> [DEPEND] Dependency failed for GnuPG public key management service for /etc/pacman.d/gnupg.
> [DEPEND] Dependency failed for GnuPG cryptographic agent (ssh-agent emulation) for /etc/pacman.d/gnupg.
> [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache for /etc/pacman.d/gnupg.
> [DEPEND] Dependency failed for GnuPG network certificate management daemon for /etc/pacman.d/gnupg.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to mount /etc.
> [FAILED] Failed to start Create System Users.
> [FAILED] Failed to activate swap Swap.
> [FAILED] Failed to start Mount removable media on nvme0n1p1.

After which it clears the screen, shows "Downloading configuration updates..." and boots into Gamescope. I can't switch to desktop though, as it just goes back to Gamescope. Gamescope itself seems to work fine though, as I'm able to log into my Steam account and download and play games.

**Comment by ruineka** [comment]
> Now I know that the build [e2914e1](https://github.com/ChimeraOS/chimeraos/commit/e2914e1146e6778f5dcf9fc45b64f3d4664daf5d) does not have the changes from the commit #924, I still felt like giving it a try, since the changelog mentions partitions handling. Now the system does boot, but in a strange way. First it shows these lines in some fancy font:
> 
> > [FAILED] Failed to mount /etc.
> > [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache (restricted) for /etc/pacman.d/gnupg.
> > [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache (access for web browsers) for /etc/pacman.d/gnupg.
> > [DEPEND] Dependency failed for GnuPG public key management service for /etc/pacman.d/gnupg.
> > [DEPEND] Dependency failed for GnuPG cryptographic agent (ssh-agent emulation) for /etc/pacman.d/gnupg.
> > [DEPEND] Dependency failed for GnuPG cryptographic agent and passphrase cache for /etc/pacman.d/gnupg.
> > [DEPEND] Dependency failed for GnuPG network certificate management daemon for /etc/pacman.d/gnupg.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to mount /etc.
> > [FAILED] Failed to start Create System Users.
> > [FAILED] Failed to activate swap Swap.
> > [FAILED] Failed to start Mount removable media on nvme0n1p1.
> 
> After which it clears the screen, shows "Downloading configuration updates..." and boots into Gamescope. I can't switch to desktop though, as it just goes back to Gamescope. Gamescope itself seems to work fine though, as I'm able to log into my Steam account and download and play games.

Please try to update to unstable now. It should be fixed.

**Comment by ClaudeLib** [comment]
Yep, seems fixed now. Except it gives me this on each boot:

> [FAILED] Failed to activate swap Swap.
> [FAILED] Failed to start Mount removable media on nvme0n1p1.

and this on each shutdown:

> [FAILED] Failed unmounting /etc.

The good sign was that it immediately asked me to update the Steam client, like stable builds do, and which the build e2914e1 did *not* do yesterday, despite me manually checking for updates.
However, switching to Desktop Mode is a total dice roll, more often than not it just leaves me on a blank screen, which the stable builds did much rarer. Is there maybe a key combo which reboots the system gracefully? Because the power button just sends it to sleep, leaving me with no option other than hard reboot.

**Comment by ruineka** [comment]
> Yep, build [f120b1c](https://github.com/ChimeraOS/chimeraos/commit/f120b1cb862cb2e44c3bafb91c85615225506193) seems to have it fixed now. Except it gives me this on each boot:
> 
> > [FAILED] Failed to activate swap Swap.
> > [FAILED] Failed to start Mount removable media on nvme0n1p1.
> 
> and this on each shutdown:
> 
> > [FAILED] Failed unmounting /etc.
> 
> The good sign was that it immediately asked me to update the Steam client, like stable builds do, and which the build [e2914e1](https://github.com/ChimeraOS/chimeraos/commit/e2914e1146e6778f5dcf9fc45b64f3d4664daf5d) did _not_ do yesterday, despite me manually checking for updates. However, switching to Desktop Mode is a total dice roll, more often than not it just leaves me on a blank screen, which the stable builds did much rarer. Is there maybe a key combo which reboots the system gracefully? Because the power button just sends it to sleep, leaving me with no option other than hard reboot.

I made some more changes, can you check and see if the boot is seamless now on unstable?

**Comment by ClaudeLib** [comment]
At first everything was fine, no errors whatsoever. But a couple of reboots later the same messages started popping up, both during startup and shutdown.
