### ISSUE TITLE
Frequent wake from sleep

### ISSUE THREAD

**Issue by leonardwohl** [ChimeraOS/chimeraos#945]
Chimeraos PC will wake from sleep multiple times a day without any user input.

Notes:
* this happens with all peripherals turned off, including the HDMI-CEC enabled tv
* the tv doesn't turn on, but the computer fans spin up
* occasionally, when I return to the PC, it will be on in desktop mode, and won't be able to load into game mode without restarting

System specs:
* GPU: Radeon RX 6750 XT 12GB
* Motherboard: GIGABYTE B550I AORUS PRO AX
* CPU: AMD Ryzen 9 3900X

**Comment by NeroReflex** [comment]
This is something I encounter with my RX 6750 XT as well and is not limited to chimeraos since I observed this with arch too. My cpu is a R9 5900x

**Comment by mathmolina** [comment]
It's also happening to me and I actually have an RX 6750 XT, has anyone here figured out what to do?

**Comment by NeroReflex** [comment]
> It's also happening to me and I actually have an RX 6750 XT, has anyone here figured out what to do?

Probably the way to go is to make sure it's the kernel and in such case open an issue in theirs gitlab

**Comment by NeroReflex** [comment]
My issue disappeared and the problem might have been vram too full. Anyway user did not provide additional details: closing for now.
