### ISSUE TITLE
ROG Ally sleep mode not working

### ISSUE THREAD

**Issue by Porroe** [ChimeraOS/chimeraos#949]
I am using latest chimeraOS on a ROG ally and every time I put the device to sleep I can hear the fans still on and if I leave it overnight the battery will be depleted in the morning.

**Comment by NeroReflex** [comment]
I have a rog ally as well as a few other team members and this never happened at least to my knowledge. We had a few users report this proble, they were able to fix somehow (we believe) but nobody ever explained how. I think it's some third party software/extensions, so I would try to remove any of those and see if the issue goes away

**Comment by honjow** [comment]
Perhaps it is because of this  https://github.com/ChimeraOS/device-quirks/pull/99

**Comment by NeroReflex** [comment]
> Perhaps it is because of this [ChimeraOS/device-quirks#99](https://github.com/ChimeraOS/device-quirks/pull/99)

But it doesn't happen on my fork and neither on unstable last rime I tested it....

**Comment by honjow** [comment]
I have verified this situation on my own device. To the best of my knowledge, bazzite also deals with this to fix ally's sleep.

**Comment by antonmarin** [comment]
Hi! Seems like workaround: in file /etc/device-quirks/systemd-suspend-mods.conf remove or comment line with mt7921e

- edit with `sudo vim  /etc/device-quirks/systemd-suspend-mods.conf`. default pass is gamer
- to enter insert mode press "i"
- in the beginning of line with mt7921e place "#" char to set it as comment
- to exit - press "esc" to exit insert mode, press ":" to enter command, write "wq!" to write and quit

helped for me.

another way can be just `sed -i 's/mt7921e//g' /etc/device-quirks/systemd-suspend-mods.conf` but i didn't test it

**Comment by NeroReflex** [comment]
This issue is fixed. Closing it.
