### ISSUE TITLE
InputPlumber: Every gamepad is defaulted to Xbox generic

### ISSUE THREAD

**Issue by HiveHivemind** [ChimeraOS/chimeraos#950]
After a month without updating, just installed 46_b439e0c and lost all of my controllers specific functionalities (haptics, touch bar, gyro, LED color). DS4 and DualSense, wired or bluetooth, are interfaced as "InputPlumber Gamepad" and defaulted to the Xbox generic layout. 
Running ChimeraOS on desktop.

It seems the InputPlumber ([edf600f commit](https://github.com/ChimeraOS/chimeraos/commit/edf600f2fbd1b0499c5d48d139f39aafae8b2bac)) was the cause. 

Manually rolled back /usr/bin/chimera-session changes, removed inputplumber-bin, installed handygcc-git, while keeping everything else intact as 46_b439e0c. They are now back working again.

System Report attached
[systemreport-20240511021124.txt](https://github.com/ChimeraOS/chimeraos/files/15281356/systemreport-20240511021124.txt)

**Comment by pastaq** [comment]
Unstable builds are unstable by nature and intended for development testing.
