### ISSUE TITLE
ASUS Rog Ally - How to setup extra buttons

### ISSUE THREAD

**Issue by antonmarin** [ChimeraOS/chimeraos#956]
In https://chimeraos.org/hardware/ i see that extra buttons of Ally are supported out of the box but can't locate where to setup it. In Controller settings, i see original xbox 360 controller, so there is no extra buttons.

Is there any documentation how to customize it or my installation is broken?

**Comment by pastaq** [comment]
Customization is fairly limited in the current version. This will be improved in v46.

**Comment by xGDNAx** [comment]
Hello, something has happened with the Ally Controller buttons.

When I test the buttons only P4 works for both buttons.

**Comment by pastaq** [comment]
Which buttons?

**Comment by xGDNAx** [comment]
The extra Buttons M1/M2

**Comment by pastaq** [comment]
This is a somewhat inconsistent bug with the Ally gamepad driver. Usually you can get them to behave correctly after a single suspend/resume cycle. We have a fix pending for this in 46-2 that should come out this week.

**Comment by pastaq** [comment]
> In https://chimeraos.org/hardware/ i see that extra buttons of Ally are supported out of the box but can't locate where to setup it. In Controller settings, i see original xbox 360 controller, so there is no extra buttons.
> 
> Is there any documentation how to customize it or my installation is broken?

BTW, this is now supported in v46. You can use steam input to map them when using the xbox-elite2 or dualsense 5 edge profiles. xbox-elite2 is the default.

**Comment by NickM-27** [comment]
how do we change the profiles between xbox-elite 2 and dualsense 5 edge?
