### ISSUE TITLE
When I install chimeraos and restart the PC, I keep getting a blank screen.

### ISSUE THREAD

**Issue by Shiraga12** [ChimeraOS/chimeraos#971]
And there's nothing I can do except use the built-in terminal.

**Comment by alkazar** [comment]
Please provide your hardware information. In particular, your GPU is important.

**Comment by Shiraga12** [comment]
GPU: Intel 4th Generation Core Processor Family

**Comment by Samsagax** [comment]
That is way too old. It won't support the Vulkan extensions needed for gamescope to work in embedded mode.
We clearly state Intel gpus are not supported (because Intel drivers are a disaster right now). Some would be lucky it works, but there is no guarantee.
