### ISSUE TITLE
Linux games are downloading Windows version when they shouldn't

### ISSUE THREAD

**Issue by zezba9000** [ChimeraOS/chimeraos#986]
@alkazar So noticed Windows version of Yooka-Laylee game was downloading incorrectly on ChimeraOS. While on Ubuntu 24.04 it correctly downloads Linux version. The OS probably shouldn't be deciding what game binary a developer chooses. Reason being is the Linux version loads much faster and has less crashes on Intel Arc hardware vs Proton. And its also so easy to just force a game to download the Windows version anyway by force enabling Proton (but not the other way around). Not being able to play Linux versions of games is rather annoying & has its own issues.

**Also I should point out gamescope is failing to boot on ChimeraOS while it works on BazziteOS.**

This is on MSI-Claw while testing XInput mode switching in Gnome session.

**Comment by alkazar** [comment]
1. Yooka-Laylee is not forced to download the Windows version, you must have done that yourself on accident.
2. We do sometimes override the Linux version because Linux ports are often broken in one way or another.
3. We strive to provide the best out of the box experience to users by pre-configuring things.

**Comment by zezba9000** [comment]
"EDIT: As you can see here (see the Steam Deck Compatibility section), Valve has configured the game to use Proton."
-- Odd as Steam on Ubuntu doesn't and the Linux version runs better & doesn't crash.

For gamescope differences between Bazzite and Chimera, why would Chimera not work and Bazzite work? Could something more compatible with Intel GPUs be used as a fallback when detected?
